### ISSUE TITLE
RunSingleInstance issues

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#668] opened 2015-09-07 22:57 UTC
@UniversalMediaServer/developers @SubJunk 
While testing the isAdmin() under Windows 10 and Linux, I stumbled over something else (as usual). While I think having a mechanizm to ensure only a single instance is smart, especially since UMS claims several ports (http server and web interface that I can think of), I don't really get the implementation:
- Why stop the old process instead of refusing to start the new?
- Why, if we are to stop the old process, do we forcibly terminate it so that is has no chance to close connections, files, the database etc. in a controlled manner. It's asking for corruption of data imo.
- Why the PID file implementation? I know it's a common way to do it under Linux, but placing the .pid file under the users home directory doesn't preven UMS from being started multiple times, it only prevents it being started multiple times by the same user. I will still have the same port conflicts if started by different users. Under Windows it makes even less sense.

I'd recommend that we did a rethink of this, and prevented UMS starting up it an instance is already running in the same OS (that is, independant of by which user) if "single instance" is selected.

I'm not quite sure how to do it under Linux, and I have no idea regarding OS X, but under Windows it seems like the simple way would be to run:

```
tasklist /FI "WINDOWTITLE eq Universal Media Serve*" /V /NH /FO CSV
```

From my testing this seems to work for non admin users as well, so there's no requirement that the user is admin for this to work. If such a process exists, UMS should simply generate a message that it's already running and then die.

The pidfile system under Linux doesn't allow non admin users to do this check, but one might be able to parse `ps` output to do the same. The problem, if I'm not mistaken, is that `ps` syntax isn't standardized under Linux, so it could be hard to find a way to make that work. Another option is to use [D-Bus](https://en.wikipedia.org/wiki/D-Bus), but I'm unsure if this is widely enough adopted.

I have no idea about OS X, but it might be that the Linux solution could also be used on OS X.

What do you guys think?

**Comment by SharkHunter** [comment] 2015-09-08 06:28
The whole idea of the single instance is to solve a problem that if you restart UMS you're sure that the old instance doesn't hang around. The pid file stuff is standard in Linux (and will work in OSX since it is BSD based) and it is a common way to deal with this problem. The pid file wasn't placed under the users home directory before and the location of the file can be changed but I doubt that is a problem very few people uses this in some multi-user environment so stopping and starting is most likely done from the same user.  

Killing the old instead of preventing a new to be started is how I wanted it, if I start a new UMS the old one should die. I don't want to start looking around in the system to kill processes etc.

As for data corruption well that can occur if the process crashes,the computer reboots,power is cut etc. If you're afraid of it you should most likely shutdown UMS manually. This is to avoid having 2 instance running which causes problems which are hard to see.
Besides I've used this for a long time now and so far now data corruption seen...

**Comment by Nadahar** [comment] 2015-09-08 14:31
@SharkHunter Thanks for the explanation, is makes a bit more sense to me now. But, has it been a problem that UMS has been hanging if you restart it? If so, how is that restarting done? 

As long as you're talking about "one instance per user" (assuming a single user system), the pid file location as it is works fine (since you don't have to deal with any file permission headaches), but that makes me wonder about the admin/root requirement. I'm not sure about Linux (My ESXi just had a disk crash, so all my VM's are currently unavailable and I can't test it right now) but on Windows you're allowed to kill/end instances owned by you without being an admin. Do you remember which exact situation made the admin/root permissions necessary? The reason I started looking at this at all is that I "fixed" ```isAdmin()``` so it also works under Linux, and that made this stop working under Linux as ```isAdmin()``` has always replied ```true``` under Linux until now. Therefore it's necessary to figure this out and see when admin/root is actually needed and not.

Most Linuxes today deprecate using root and many even disables the root user forcing people to su when root is needed. That in itself makes it "multi user" in the way that when you su you also change home folder. 

Another thing is that I think it could be worth trying a "softer" kill than -9 at first, wait some seconds and then do -9 if it hasn't shut down gracefully. I'd also think it could be a good idea to give both options, "don't start a second" and "kill old" in the config, as "don't start a second" is what "single instance" usually mean - and what I'd expect and find most useful.

**Comment by SharkHunter** [comment] 2015-09-08 15:03
@Nadahar - isAdmin was needed since most users installs UMS as admin on windows and then running it as regular user X which makes premissons for writing files (for example the pid file) a mess.
Yes most linuxes don't use root and most people don't run linux at all. People that  run linux  see this issue once and the they always run it as su. The whole idea with single instance is to make sure that you don't get 2 UMS instances of which one will not work. If you're starting one you would like to kill the old one way or the other. Under Linux if you can't kill the old process due to lack of permissions then you're back to square one. This solves the case 90% of the user sees the remaining 10% is most likely smart enough to know how to get around it.

**Comment by Nadahar** [comment] 2015-09-08 16:50
@SharkHunter I'm sorry for the long respose time today, I'm in the middle of rebuilding the crashed ESXi server so I don't have much time to check things right now. But, from what I can see I just discovered a whole new problem: I was thinking, why do the user have permission issues with the pid file when it's in the profile directory, but ```%programdata%``` which is the default profile folder is read-only for non-admin Windows users.

That means that logfiles won't work and saving any changes to UMS.conf won't work if your user isn't admin. That's pretty bad imo, especially as Windows 10 gets more widespread where they have really hidden to option to make a local admin beyond the "average user". 

As I see it, we should consider moving the profile folder for Windows into the user folder, and that would at the same time ensure that admin wasn't needed for the pid file.

I completely agree that running 2 instances of UMS is useless, if anyone for some reason want to do that they'd have to create different profiles for the two assigning different ports. I have a hard time to se what that would achieve. What I'm not that convinced about is that killing the old process is what most users would expect or want. The de facto standard seems to be the opposite, it prevents a seconds instance from starting up, and that's what I'd expect and want. If you forget that UMS is running and starts it, it could already serve some other renderer in the house - why would you abrupt that and start it again instead of just letting the existing instance run?

That's why I proposed that we could make it an option to do one or the other. Alternatively, UMS could ask (if not headless) if you want to do this or that. If headless it could abort and inform that you'd have to start it with a certain switch (e.g -K) for kill the previous.

**Comment by SubJunk** [comment] 2015-09-18 21:54
I thought the programdata folder had free permissions for users. If you're right that the users directory has more open permissions then I agree we should move the UMS folder to there.

**Comment by Nadahar** [comment] 2015-09-18 22:02
Only administrators have write permissions in ProgramData, but all authenticated users have read permissions. The UMS installer however make the UMS folder writable by the local ```users``` group. As long as the installer creates the folder, it should work.

**Comment by SubJunk** [comment] 2015-09-18 22:25
So is your recommendation still to use the user folder, to solve cases where the installer fails to create the programdata one?

**Comment by Nadahar** [comment] 2015-09-18 22:54
No, I'm more undecided at the moment. I think having a shared configuration for all users is what you'd normally want for UMS, especially if it's going to be run as a service at some point. A fallback to the users home folder might be an idea to try to play it safe.

My main point with this issue isn't the user folder though, but the way single instance is enforced. I think it's a bad idea to terminate the running process when UMS is started for several reasons. First because it could require administrator/root permissions depending on the situation/OS, and also because there's no way to do a graceful shutdown of another process under Windows (unlike Linux if you drop -9). That means that you get corruption of the database, incomplete logfiles, possible corruption of configuration files, abrupted renderer service (if someone else is using UMS while someone is unfortunate and click the icon) and in some cases renderers hanging (I've managed to get both software and hardware renderers to hang by terminating UMS, requiring me to actually unplug the power to my Onkyo to get it going again). It think that preventing startup for the second process would make much more sense, and it would also work regardless of permissions. I'm not sure I see what's gained by maintaining a PID file either, compared to simply listing running processes and parse that. I think it at the very least should be an option, and I think the default should be to abort the launch of the second process.

**Comment by SubJunk** [comment] 2015-09-19 00:02
I agree that aborting the launch of the second process is the best thing to do and that's what I had assumed would happen with this feature. I would support those changes being made.

WRT the users folder, I agree it would be good to test with non-admin accounts

**Comment by Nadahar** [comment] 2015-09-19 00:08
> WRT the users folder, I agree it would be good to test with non-admin accounts

I've already tested with a non-admin account and that worked. What I haven't yet tested is a non-admin account without a password. The reason for this, is that the group that is given permissions is the ```users``` group which by default consists of the ```authorized users" group. According to Microsoft, all users "that's been through the login process" is in this group. I just want to make sure that simply clicking on the name (which is what you do without a password) qualifies - especially since I know that there's certain things in Windows that's not available for users without passwords. My guess is that it will work though.

**Comment by Nadahar** [comment] 2015-09-19 13:29
I just tested with a standard user without password, and it counts as "authorized" so there should be no problem using ```ProgramData``` as long as the installer sets the permissions.

**Comment by SubJunk** [comment] 2015-09-19 23:05
Nice one

**Comment by Nadahar** [comment] 2018-09-01 19:51
Yet another issue that is ignored.

**Comment by dyorgio** [comment] 2018-10-19 13:56
Hi guys,  I jsut want to show another way to handle SINGLETON PROCESS feature.
Using file locking:
```java
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;

/**
 * Create a lock file to only permit one instance of application run.
 *
 * @author dyorgio
 */
public class SingletonProcess {

    private static File lockFile;
    private static UnlockShutdownHook unlockShutdownHook;
    
    public static boolean isRunning(String name) throws IOException {
        return isRunning(name, null);
    }

    public static boolean isRunning(String name, String contents) throws IOException {
        lockFile = new File(DirectoriesUtil.getWorkingDirectory(), name + ".lock");
        if (!lockFile.exists()) {
            lockFile.createNewFile();
        }

        FileChannel fileChannel = new RandomAccessFile(lockFile, "rw").getChannel();
        FileLock lock = fileChannel.tryLock();

        if (lock == null) {
            fileChannel.close();
            return true;
        } else if (!StringUtils.isNullOrEmpty(contents)) {
            fileChannel.write(ByteBuffer.wrap(contents.getBytes()));
            fileChannel.force(true);
        }

        Runtime.getRuntime().addShutdownHook(unlockShutdownHook = new UnlockShutdownHook(fileChannel, lock));

        return false;
    }

    public static boolean unlock() {
        if (unlockShutdownHook != null) {
            unlockShutdownHook.run();
            lockFile.delete();
            return true;
        }
        return false;
    }

    private static class UnlockShutdownHook extends Thread {

        private final FileChannel fileChannel;
        private final FileLock lock;

        public UnlockShutdownHook(FileChannel fileChannel, FileLock lock) {
            this.fileChannel = fileChannel;
            this.lock = lock;
        }

        public void run() {
            try {
                lock.release();
            } catch (Exception e) {
            }
            try {
                fileChannel.close();
            } catch (Exception e) {
            }
        }
    }
}
``` 

DirectoriesUtils.getWorkingDirectory() needs to be replace by your "working dir" logic.

To use it, just put it on first  line of main method:

```java
if (SingletonProcess.isRunning("activities", HostInformation.getPid())) {
    LOGGER.warning("Process already running! Exiting...");
     return;
}
```

On example  I  put current pid on file to use it on external processes... just an example.

To solve "gracefull shutdown" problem in my applications I put a deamon thread  to verify working dir for a ".shutdow" file, when it detects one, start the gracefull shutdown.

Theses techniques are OS independent.

**Comment by SubJunk** [comment] 2018-10-20 08:38
@dyorgio thanks!

**Comment by SubJunk** [comment] 2018-10-20 08:38
@dyorgio thanks! Would you consider making a PR?

**Comment by dyorgio** [comment] 2018-10-21 18:55
Hi @SubJunk, I think that this Issue is very old and contains a lot of ideas to solve/improve some problems/flows in this project.
My suggestion is first of all create a project/milestone with separed and very well explained requeriments before start coding.
To me just include utility class, use it in main and make a PR is easy, the problem is to know what kind  of problems its can brings together. (I don't have this knowledge)

**Comment by SubJunk** [comment] 2020-03-08 20:31
I think @SharkHunter explained and defended the existing implementation nicely so I'm closing this

**Closed by SubJunk** 2020-03-08 20:31 UTC
