### ISSUE TITLE
Duplicated subtitles in the TRANSCODE folder

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#1338] opened 2017-07-13 21:58 UTC
There is a bug introduced in f2c74f5 when in the TRANSCODE folder are duplicated the external subtitles for players. This is made during producing the TRANSCODE folder content. We want to make all possible combination of the players, audio and subtitles and for that the database should not be involved. It seems to me that the database record is added to the TRANSCODE folder but is wrong because the external subtitles are not properly recognised and are taken as embedded.

**Comment by valib** [comment] 2017-07-29 22:21
@Nadahar have you registered this issue? To be more precise in description of this issue when the database is deleted or reset it works. But when the UMS is started for the second time the record from the database is added to the TRANSCODE folder and doubled the combination of the player, audio and subtitles which are already there because the external subs file name is not stored in the database. This item added to the TRANSCODE folder is wrong because the ID number is greater then 100 but without the external file name it is recognised as the embedded subs.

**Comment by Nadahar** [comment] 2017-07-29 22:28
@valib I haven't looked at it, as I really don't know too much about how the TRANSCODE folder/subtitles selection work. I understand what you're saying, that they are registered twice (once from the cache and once from actual parsing), but I'm not sure what the problem is: 
* If not enought information to use the subtitles is stored in the cache, why are they being stored in the cache at all?
* If subtitles are found in the cache, why is it still being parsed? That kind of defeats the purpose of caching.
* Is there any information that should be stored in the cache that isn't, so that is the reason for the problem?
* If the subtitles for some reason has to be parsed each time regardless of the cache, why use the cache for subtitles at all?

If you could answer these questions I might understand more about the problem.

**Comment by valib** [comment] 2017-07-29 22:45
@Nadahar I think that the concept when renderer is always checking the folder is OK because users can in the mean time delete or add  media items and subs. I think that we should store in the database only thumbnails because those are realy time consuming but the rest could be done on the fly.

**Comment by Nadahar** [comment] 2017-07-29 23:11
@valib That conflicts somewhat with what @SubJunk is doing in 7.0.0, The only way I see to resolve this, is to first define clearly how it's supposed to work, and then make it work that way. If the solution is not to store subtitle information in the cache at all, so be it, but remember that people can also access video via the media library. I don't know if subtitles are being scanned if they are access that way.

**Comment by Nadahar** [comment] 2017-07-31 11:42
@SubJunk This is a discussion where I think you need to be involved. It's not that I don't want to help solve this, I just can't find a practical solution to something before the goal is clearly defined. How do we want subtitles and caching to be handled, do we want them to be cached or do we want to scan for them each time?

I think there are multiple factors to take into account here, like when browsing is done exclusively from the media library while also taking into account that users might add subtitles after adding the video itself expecting the new subtitles to be picked up. It should work both if the subtitles are added while UMS is running or not, which is different to us (just the former is picked up by ```FileWatcher```).

I know too little about videos and subtitle handling to be able to make a recommendation of how I think it should work, so I think we need a discussion where all factors are taken into account and the best solution is found before any implementation is started.

**Comment by SubJunk** [comment] 2017-08-01 05:47
It's an important discussion for sure. I think right now we have a good design where you can either browse your folder structure, or browse the media library.
I personally only use the media library now, and when I look at our competitors like Plex and Serviio that's how they primarily do it too. It's just so convenient for users to have content organized automatically, and that's too complex to do in realtime so we do need caching/databases.

I'd like to see the subtitles info be stored in the database fully.

**Comment by Nadahar** [comment] 2017-08-01 15:36
@SubJunk The current "design" isn't working properly, that's why we need to define how we *want* it to work and then implement that. It's not about whether you should be able to browse via the media library or the folder structure, the only "correct" thing to do is to offer both IMO.

This is about how/when subtitles should be resolved. As I see it there are conflicting needs:
* To properly handle external subtitles when using the media library, it necessary information about the external subtitles must be stored in the database.
* To allow users to add subtitles to the library that will be picked up without rescanning the library, they need to be resolved each time a video is accessed.

I don't know if there is ```TRANSCODE``` folders when browsing the media library (haven't used it for a long time). If it isn't, the problem might be somewhat smaller as you don't need to present all possible combinations and subtitles could be resolved when playback is started (to pick the correct default one).

When it comes to rescanning folders when browsing I don't remember how the implementation is when using the media library. That's probably changed in 7.0.0 anyway. What is the current strategy when using the media library (we might as well forget about the media library in 6.x as that doesn't really work very well anyway)? Is the folders containing the listed antries "refreshed"/resolved when browsing the media library? I can't see how that could be practical, it would be a very slow process so I'm assuming that media library browsing is purely done via the database. In that case, there isn't really possible to make the media library "discover" subtitles added after the last scan, is it?

I'm not sure about the "discovery" logic in 7.0.0, do you start an automatic scan each time UMS is started and then keep it updated with ```FileWatcher```? If so, subtitles could be handled entirely via the database, given that ```FileWatcher``` also picks up new files and manages to "attach" them to the correct video. I don't know if that's the case though.

I know this can be difficult, but I think this warrants some in-depth analysis to make the right design decision. Making wrong design decisions causes so much changes and bug fixing later on.

When it comes to the media library being preferrable to browsing folders most of the time, it's what I've been trying to tell you the whole time. I don't know where UMS' preference to folder browsing came from, I've never understood it and never agreed to it. Folder browsing mostly makes sense when you have a small number of shared files, or with to maintain a very specialized structure.

**Comment by SharkHunter** [comment] 2017-08-01 19:37
The folder browsing has been there since day0 it is the PMS/UMS way. "I never understood and never agreed" no you weren't in the project (neither was I) at that time. And just beacuse you don't understand things doesn't mean that it is just something you can ignore.  I don't use Plex/Serviio etc. since they ONLY have a media library which I find sooo annoying. I know where I want my media I don't want some stupid piece of silicon to do that. On top of that using a media library makes dynamic content a real pain in the ***. But now I retired (which looks like a smart move) so you can do as you please. But like I said the folder browsing is the KSP for UMS.

**Comment by Nadahar** [comment] 2017-08-01 19:53
@SharkHunter I don't understand why you start that all over again, you've said it many times before. I don't consider it at "killer feature" that you ususally describe it as, but I've never suggested that it should be removed.

The current discussion isn't about removing it either, it's about getting subtitles to be correctly discovered both when browsing by folder and when using the media library.

**Comment by SubJunk** [comment] 2017-08-02 06:38
> I'm not sure about the "discovery" logic in 7.0.0, do you start an automatic scan each time UMS is started and then keep it updated with FileWatcher? If so, subtitles could be handled entirely via the database, given that FileWatcher also picks up new files and manages to "attach" them to the correct video. I don't know if that's the case though.

Yes that's how it works in 7.0.0 so barring bugs (there are sure to be some that we will find out about after its release) it should keep itself in sync. The rescanning also happens when using the normal non-media-library browsing, as it always did.

> I know this can be difficult, but I think this warrants some in-depth analysis to make the right design decision. Making wrong design decisions causes so much changes and bug fixing later on.

Agreed. I'm not sure what there is to make a decision on though, if there are duplicate entries in a folder then that seems like a bug regardless of different decisions we want to make

> When it comes to the media library being preferrable to browsing folders most of the time, it's what I've been trying to tell you the whole time. I don't know where UMS' preference to folder browsing came from, I've never understood it and never agreed to it. Folder browsing mostly makes sense when you have a small number of shared files, or with to maintain a very specialized structure.

Yeah both are good for different situations so I agree it's good to have both. I use both regularly.

It would be good to use 7.0.0 as the reference for discussion since there are relevant changes in there, as you said @Nadahar

**Comment by Nadahar** [comment] 2017-08-02 10:49
@SubJunk It you look at the reason for the duplicate entries you will see that it's because of the non-coherent design. The reason it manifested now is probably because some other bug has been fixed in the database code. The reason there are double entries is because one set is from the "real time scan" of the folder while the other comes from the database. As I see it this bug can't be solved without first firguring out how we *want* it to work.

According to [this thread](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=10375) the "real time scan" doesn't actually manage to attach subtitles to the correct video as it is today. @valib Is that correct?

**Comment by valib** [comment] 2017-08-02 12:18
@Nadahar that is correct. Checking for subtitles is done only during browsing. The only way how to add subs corectly is to add new video together with subtitles in one step and then browse the folder. Not to add only video then browse the folder and additionally add subs.

**Comment by Nadahar** [comment] 2017-08-02 12:24
@valib I'd say that is a problem as well. I'd say it's very likely that users will add subtitles later, if they discover that no internal subtitles are available or that sound is bad or the language difficult to understand.

**Comment by SubJunk** [comment] 2017-08-03 06:43
@Nadahar that thread seems to be about version 6.7.2 so they aren't using the realtime scanning

Having said that, I don't think the current 7.0.0 would do it either. I'll add it to the checklist for that branch since I think it's a good feature to have.

**Comment by SubJunk** [comment] 2021-06-26 08:17
This was confirmed fixed a while back

**Closed by SubJunk** 2021-06-26 08:17 UTC
