### ISSUE TITLE
[BUG] Several instances of UMS are run at the same time (headless)

### ISSUE THREAD

**Issue by 444nonymous** [UniversalMediaServer/UniversalMediaServer#1365] opened 2017-08-17 08:12 UTC
The option "run only a single instance of UMS" only works with GUI.

If you start the server headless with no GUI, it will create new javaw.exe processes every time you start UMS. It does not matter  if the new instances are run as headless or GUI.

Fix: If you try to start a new headless UMS instance, it should not be allowed.

But If you try to start a new GUI UMS instance over a headless one, the GUI could be loaded for that headless process. If not possible, the headless process could be terminated and the GUI one started (it should have priority).

**Comment by 444nonymous** [comment] 2017-08-17 10:43
I've checked again and it also happens when UMS GUI is launched first. So several instances of UMS are run at the same time no matter what.

I'm using command line "UMS.exe profile=profile". Always same profile and command-line to start UMS.

**Comment by Nadahar** [comment] 2017-08-17 11:52
This is more or less a duplicate of #668.

**Closed** 2021-07-11 22:19 UTC
Labels: duplicate
