### ISSUE TITLE
Movies Not Working UMS 6.0.0.a1

### ISSUE THREAD

**Issue by F1Fan3** [UniversalMediaServer/UniversalMediaServer#768] opened 2015-12-25 15:23 UTC
Some movies, both AVI and MKV shows up as 976kb on my Samsung smart Tv. There are generally big 8-10GB files. Works perfectly on my computer or if I play it directly from a hardrive. Just when using UMS, it will not play.

Any thoughts on what the issue could be?

**Comment by WolfganP** [comment] 2015-12-25 16:28
In my Samy a similar issue arises when the media has an incompatible container. But it's difficult to say what may be wrong w/o logs, please follow http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

**Comment by F1Fan3** [comment] 2015-12-26 18:57
The logs arent showing anything though. See attached

**Comment by F1Fan3** [comment] 2016-01-05 13:46
Help...please...

**Comment by Nadahar** [comment] 2016-01-05 14:11
Can you tell me the name of one of the files that won't play that's captured in the debug log?

**Comment by F1Fan3** [comment] 2016-01-05 14:23
INFO  2015-12-26 20:54:40.984 [StopPlaying Event] Stopped playing The Martian.mkv on your [TV]Samsung LED48
DEBUG 2015-12-26 20:54:40.984 [StopPlaying Event] The full filename of which is: D:\Movies\2015\The Martian\The Martian.mkv and the address of the renderer is: 10.0.0.6

**Comment by valib** [comment] 2016-01-05 14:27
@F1Fan3 you set the TRACE mode too late. There are missing info in the log why UMS decided not to stream the mkv file and start to transcoding it. Please set the TRACE mode immediatelly after the UMS start and after that try to play that video again.

**Comment by F1Fan3** [comment] 2016-01-05 14:41
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/78526/ums_dbg.zip)

Is that correct?

**Comment by F1Fan3** [comment] 2016-01-05 14:45
@Valib Have no idea how to make a renderer  config file? Total noob. Is there a guide?

**Comment by valib** [comment] 2016-01-05 14:56
@F1Fan3 simply click on the renderer icon at the UMS Status tab. The dialog will appear and click on the small icon on the right with tooltip "Customize the device". Then save the proposed file which after that will be automatically opened. At the end of the file write SupportedInternalSubtitlesFormats = SUBRIP,ASS,TEXT,MICRODVD,WEBTT,SAMI,PGS and close it. Close UMS and after restart the configuration should be working.

**Comment by F1Fan3** [comment] 2016-01-05 15:17
Working, thanks!!!

But there are other movies that don't either. Logs attached.

Is this a Samsung problem? 

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/78569/ums_dbg.zip)

**Comment by valib** [comment] 2016-01-05 17:35
@F1Fan3 the problem is here:
```TRACE 2016-01-05 17:07:25.146 [New I/O worker #14] File "300.mkv" will not be streamed because the bitrate is too high.```
In the Samsung-NotCD.conf there is a ```MaxVideoBitrateMbps = 25``` and your videos are about 14,7 Mbps so you can try to add  to your [TV]SamsungLED48-098968.conf line
```MaxVideoBitrateMbps = 0```
which means No limit.

But what is strange that your TV doesn't play videos when they are transcoded.

**Comment by F1Fan3** [comment] 2016-01-18 17:37
@valib 

Thanks. Did that, still didn't help. It seems every movie I download now doesn't work.

Series works just fine. Any other suggestions?

**Comment by valib** [comment] 2016-01-18 20:39
@F1Fan3 have you tried to play that files from the TRANSCODE folder? There are for each files all possible combination how to play them and one of them is "No transcoding". And as obvious we need the TRACE.log

**Comment by F1Fan3** [comment] 2016-01-22 20:33
So the original file in the transcoding folder works.

I've also noticed that files that are 976kb now works, but I can't forward or rewind. Before, it would not work at all.

See My Name is Khan and Hero in logs.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/101397/ums_dbg.zip)

**Comment by SubJunk** [comment] 2022-10-03 02:39
Stale

**Closed by SubJunk** 2022-10-03 02:39 UTC
