### ISSUE TITLE
Problems with Xbox

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#476] opened 2015-02-01 23:48 UTC
@SubJunk I don't know if it is relevant to issues commented e.g. here http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=2901&start=20 but the Eclipse is reported a dead code in the Request.java at the line 613 and the RequestV2.java at the line 667. The `containerID` is always null at that positions.

**Comment by SubJunk** [comment] 2015-02-02 03:48
@valib I just checked in Eclipse and I don't get that error but I do get 4332 errors in the project that I'm pretty sure aren't errors, which is similar to what I've always got with Eclipse, maybe I didn't set up the Eclipse project correctly or something.

**Comment by SubJunk** [comment] 2015-02-03 19:15
@UniversalMediaServer/developers does anyone have an Xbox 360 and/or Xbox One? We are getting lots of reports of bugs on them and I don't have one to test.

**Comment by valib** [comment] 2015-02-03 22:46
@SubJunk  I don't like consoles since they are only crippled PCs sold for much money :)

**Comment by SubJunk** [comment] 2015-02-05 08:23
@valib I've been discussing it with @SharkHunter lately and hopefully he'll look into it. It seems that all of the trouble with Xbox 360 was caused originally by the global ID commit at 7ddcda0
I have borrowed an Xbox 360 for testing which has let me narrow this down a lot but I'll have to give it back soon.

**Comment by SubJunk** [comment] 2015-02-09 22:36
@UniversalMediaServer/developers I just reproduced some really weird behavior on the Xbox 360 that may help explain our different experiences. I went into UMS 5.0.0 via Xbox 360 and it got it right - it displayed the proper folders straight away. But then I went out of the server and back in (just the B button then the A button) and then instead of my folders I got just one folder "TEDTalks (video)". Then when I did B and A again the same thing happened.

**Comment by SubJunk** [comment] 2015-02-09 22:41
Here are logs for that. I notice the error in the logs "GlobalIdRepo: id not found: 15", could it be related?
http://www.universalmediaserver.com/forum/download/file.php?id=1935

**Comment by Luxton79** [comment] 2015-03-15 14:01
I have an xbox that won't show the UMS server at all, I'd be happy to help test...

**Comment by SubJunk** [comment] 2015-03-22 21:55
@Luxton79 please provide logs from this version :) http://www.spirton.com/uploads/UMS/UMS-e305fe0.exe

**Comment by Luxton79** [comment] 2015-03-24 15:16
Sorry for the delay, I didn't see the email about your response...

I've tried with both the version you posted here and the released 5.1.0, both still have the same issue, the XBOX 360 won't show UMS.  The IP address of my XBOX is 10.0.10.71, you'll see it in the logs.

Cheers!!

http://www.calgarypitbull.com/ums_dbg.zip

**Comment by ExSport** [comment] 2015-03-24 16:02
Your XBOX 360 was detected as Xbox360 and after reading additional info it reassigned to "Bedroom" renderer as you probably defined on XBOX. Maybe this additional parameter in reply force UMS to endlessly redetect this renderer so you don't see it on XBOX. I checked your log from mobile only so quite limited reading to go deeper. I suppose @skeptical will see exactly what is wrong here.
Definitely UMS see XBOX and communicates with it what is good info.
@skeptical : Very nice changes in network logging, much more readable :+1:

**Comment by skeptical** [comment] 2015-03-24 20:24
@Luxton79 try this [fix](http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15596#p15596) with ums 5.1.0 (not the debug version posted here), and let us know if visibility improves.

@ExSport Nothing escapes you :+1:, you may have just solved part of the visibility issue :). I doubt that network logging has improved that much, you're just getting a lot more practice reading those messages lately.

**Comment by Luxton79** [comment] 2015-03-25 13:37
Nice find, but unfortunately it didn't change anything... :(

UMS still sees the xbox, but the xbox doesn't see it.

**Comment by Luxton79** [comment] 2015-03-25 13:44
The log file can be found here: http://www.calgarypitbull.com/ums_dbg_2.zip

**Comment by skeptical** [comment] 2015-03-25 15:16
@Luxton79 It probably doesn't matter, but your log shows you're using the debug version with the patch, not official ums 5.1.0 (see [above](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/476#issuecomment-85677950)).  Try it that way too (no need to post logs unless you notice something different).

**Comment by Luxton79** [comment] 2015-03-25 15:23
I noticed that too and redownloaded and installed the full version, same results :(

**Comment by valib** [comment] 2015-03-25 17:43
@skeptical  what about to consider that problem is not in UMS but in Xbox360? It doesn't communicate at the DLNA level. Wrong setting? Wrong player? What is confusing users is that when UMS recognises renderer at the UPnP level it is shown as connected. But in reality it is not connected util it starts DLNA communication.

**Comment by skeptical** [comment] 2015-03-25 21:01
@valib Could be, googling 'xbox upnp' seems to bring up a lot of users with network configuration/connectivity issues, though  I think we also have reports saying it recently stopped working (presumably due to changes in ums or xbox firmware). What say you @Luxton79 :)?

In any case @ExSport has a point, ```isXbox360()``` would have been returning ```false``` for a device named "Bedroom" before dfbb44d.

**Comment by Luxton79** [comment] 2015-03-26 12:39
It did indeed stop working more recently... I'm not sure if it was a change in the xbox firmware or UMS, but I know PMS still works (although it doesn't want to play a LOT of the files I have).

If anyone has suggestions on network settings to give a shot, I'm more than happy to try them out and report back.

**Comment by valib** [comment] 2015-03-27 09:42
@skeptical I have an idea related to my previous commit. To distinguish between UPnP connection before the DLNA starts the renderer icon could be gray and in the filename label could be e.g. "Waiting for DLNA connection". After cuccesfull DLNA connection the icon will change to the color. Is it possible?

**Comment by skeptical** [comment] 2015-03-27 12:20
@valib Your point is that the icon should reflect whether the device is "ready" or not (insofar as streaming is concerned anyway), which is a good idea (though I doubt that seeing an unchanging grey xbox icon will really make the users here any happier :-). Anyhow it's of course possible since we can trigger icon color (or add a little "green light", or erase an initial "red light", etc) once the http server sees the device.

Tracking partial vs full connection state is interesting (we already sort of see it sometimes when the icon changes after recognition or priority is adjusted in the second stage). The sequence is accidental, sometimes we get dlna before upnp and sometimes vice-versa, which leads to occasional weirdness due to persistent holes in my recognition "logic" :-).

**Comment by Luxton79** [comment] 2015-03-27 13:20
Interesting side note.... if I click on the xbox with in UMS, I can select and play a video on it successfully.

**Comment by skeptical** [comment] 2015-03-27 13:41
@Luxton79 your xbox is in a "upnp-ready" state, since you can see the icon (and your logs show we've successfully subscribed to its services) so it's remote-controllable.  For some reason it's not finding us as a mediaserver though.

**Comment by skeptical** [comment] 2015-03-27 13:52
@valib come to think of it, the device isn't "ready" in the sense you mean until we receive an actual browse request, since in @Luxton79's case he can push to the xbox, which would result in http requests that would trigger ```RendererConfiguration.resolve()``` even though the xbox isn't showing us as a mediarenderer. It's never as simple as it first seems :).

**Comment by valib** [comment] 2015-03-27 21:11
@skeptical I am not sure if Xbox is in that case sending http request. @Luxton79 can you provide log for the remote control plaiyng?

**Comment by skeptical** [comment] 2015-03-27 21:52
@valib  pushing just involves sending a resource uri to the renderer, after that everything happens the same as if the user had browsed the resource and pressed play.

**Comment by valib** [comment] 2015-03-27 22:53
@skeptical  I again checked the log provided by Luxton79 and I think that problem is in his Xbox. He has in the network also an iPad which is responding correctly and send `GET /description/fetch HTTP/1.1.` but it doesn't communicate at the UPnP level. I also tested UMS with Kodi and it works correctly at the UPnP level and also at the DLNA level. It seems to me that his media renderer doesn't support the DLNA.

**Comment by skeptical** [comment] 2015-03-27 23:10
@valib he says it worked until recently, and of course most renderers including kodi can see ums. The issue is why we have recent reports that some devices have stopped seeing ums, even though ums can see them (reported for Xbox, Samsung, bravia). It seems to have to with network topology.

BTW, how did you solve the (long ago) issue where your TV was hidden behind a second router?

**Comment by valib** [comment] 2015-03-27 23:34
@SubJunk we have problems only with vendors who implemented DLNA in their own way. That's why we have quite a lot of the exceptions for them in the UMS. The issue with my TV I solved when I set the second router to the Client mode. This solution has a side effect that the TV doesn't communicate at the UPnP level but the DLNA works perfect.

**Comment by SubJunk** [comment] 2015-03-27 23:54
@valib yes I think that's a good idea. Maybe we could have a renderer config setting to enable or disable UPnP, so when it is false we use the pre-5.0 functionality?

**Comment by valib** [comment] 2015-03-28 00:20
@SubJunk I think that it is possible to postpone the part of the UPnP communication (the remote control) until the DLNA recognition will be finished.

**Comment by skeptical** [comment] 2015-03-28 08:27
@valib not all xboxes/bravias/samsungs have this problem with 5.x, e.g. @SharkHunter's bravia is OK +his xbox too (although newer firmware showed some other issues I think), and @Optimusprimeums' samsungs are good too (usually anyway, he says he saw the issue once or twice but can't reproduce it).
I don't think it's a general problem with those manufacturers.

**Comment by Luxton79** [comment] 2015-03-29 00:05
I have a PS3 that works great in the network as well.  I have another PS3 in my bedroom with the XBOX, but it has an issue at the moment, which is why I switched over to use the XBOX, unfortunately I also don't know exactly when it would have stopped working exactly.

If it's the name of the XBOX, let me know what I should name it and I'll absolutely change it, even if just for testing!

I have an LG 55LS5700 that doesn't see UMS either, but I never use it as a media server directly (oddly, it DOES see the media server from my NAS box, which is a shyte media server... and 2 of my laptops)

**Comment by skeptical** [comment] 2015-03-29 15:54
@Luxton79 the name issue is already fixed, so no need to rename anything. Your patch test above showed that it's not directly relevant to your main issue: ums server visibility. If your xbox had been able to see ums in the first place, then the naming issue could have prevented seeing individual files, but we're not there yet :).

**Comment by Luxton79** [comment] 2015-03-30 12:29
hmm, I can try that... although, they're both on a gig switch in my room, so i don't think that's going to make a difference...

**Comment by skeptical** [comment] 2015-03-30 14:40
@Luxton79 Best would be if it's plugged into one of your router's ethernet ports if possible.  I just want to know if the visibility issue is still present with a direct simple connection (and attach logs if there's a difference). Thx :).

**Comment by Luxton79** [comment] 2015-03-30 14:57
I have a slightly more complex network setup that most will... I have 15 computers running in my house, including a rack of servers.  Without physically moving either the xbox and TV 2 floors away, or bringing my media server box upstairs, this will be the most direct route.  Currently, there's a GB router in my room, connected through the house to another gig switch in my basement, which the media server is connected to.  The PS3 that sits beside the XBOX in my room is able to see the UMS without an issue (when it doesn't have issues, lol).

**Comment by skeptical** [comment] 2015-03-30 15:27
@Luxton79 lol "slightly more complex" :D.  I leave it to you to decide where to find a "good" connection point for comparison, then.

**Comment by Luxton79** [comment] 2015-03-30 22:15
lol, yeah, a tad more complex :).

As this was the way it was working before, I'm leery to mess with anything in case it ends up causing a red herring when debugging.

**Comment by SubJunk** [comment] 2015-03-31 22:06
Summary:

There are two Xbox bugs that were introduced in 5.0:

The first is that when Xbox users enter the media server from the Xbox, they are shown photo folders. It was caused by the global ID commit 7ddcda0. Reverting to before that commit fixes it. It doesn't look like it's going to be fixed so maybe we should revert the global ID parts of the update.

The second is related to network discovery, which is getting a lot of attention already and will hopefully be fixed/workedaround by a renderer-level option to toggle UPnP.

**Comment by Luxton79** [comment] 2015-03-31 23:46
That's fantastic @SubJunk .

Let me know and I will do whatever I can to help!

**Comment by SubJunk** [comment] 2015-04-01 09:16
@Luxton79 thanks!

@UniversalMediaServer/developers here's another report and potential tester http://www.universalmediaserver.com/forum/viewtopic.php?f=11&t=3220

**Comment by SubJunk** [comment] 2015-04-07 01:26
@Luxton79 please try this version http://www.spirton.com/uploads/UMS/UMS-e6baf09.exe

**Comment by skeptical** [comment] 2015-04-07 02:36
@Luxton79 to be a little clearer, there are 2 things to try:
* Shut down UMS, set this in ```Microsoft-Xbox360.conf``` and restart
```sh
UpnpAllow = false
```
If still no joy, shut down ums again, set this in ```UMS.conf``` and restart
```sh
upnp_enable = false
```
Remove the settings afterward if they're not effective, and TRACE logs for each test would be great :).

**Comment by Luxton79** [comment] 2015-04-11 13:07
Hey... sorry for the delay, I've been out of the country.

I've tried the version you posted here, I downloaded the version from the website, and let the auto-updater run to download a version, but every time I try to start it up I'm told there's a new version and I need to updated it.... any way to get around that?

**Comment by SubJunk** [comment] 2015-04-11 21:36
@Luxton79 it would be best to ignore updates if you're using the version I uploaded (http://www.spirton.com/uploads/UMS/UMS-e6baf09.exe)

**Comment by Luxton79** [comment] 2015-04-12 16:26
That would be ideal... but every time I start the app, it tells me there's an update.  If I cancel, it closes and won't load the rest of the app.  I'm guessing there's a command line switch?

**Comment by skeptical** [comment] 2015-04-12 17:05
@Luxton79 in ```UMS.conf```:
```sh
auto_update = false
```

**Comment by SubJunk** [comment] 2015-04-13 00:17
@Luxton79 it would be great to get logs after the program fails to load when you cancel the update. I just tested it and the program loaded after I clicked the Close button in the update window, so it looks like you're experiencing a bug with the updater.
Please upload C:\ProgramData\UMS\debug.log after reproducing the bug, and link to it here so we can see what's going on

**Comment by Luxton79** [comment] 2015-04-13 08:54
hmm, it appears the update thing was my fault... I was modding UMS.conf in C:\Program Files\ instead of C:\ProgramData\... oops!

I've updated the correct config file, but now the GUI won't show up at all, not even the icon in the notification area... the debug file can be found here: http://www.calgarypitbull.com/debug.zip

**Comment by SubJunk** [comment] 2015-04-13 09:11
Can't see anything in the logs, maybe try selecting the Clean Install option?

**Comment by Luxton79** [comment] 2015-04-13 13:52
Clean install worked!

I can now see UMS on my xbox!! But everything comes up as if it were all pictures... but everything (movies/tv/music/etc) is in the picture directory.  Any idea?

**Comment by Luxton79** [comment] 2015-04-13 15:20
Incidentally, it works perfectly on my PS3...

**Comment by skeptical** [comment] 2015-04-13 16:11
@Luxton79 so far so good :-). I'm assuming (with clean install) that your ```Microsoft-Xbox360.conf``` now says ```UpnpAllow = false```?  If so, for comparison could you please generate logs for ```UpnpAllow = false```, ```UpnpAllow = postpone```, and ```UpnpAllow = true```?

**Comment by Luxton79** [comment] 2015-04-13 16:50
Ok, log files with all three settings...

http://www.calgarypitbull.com/ums_dbg-upnp_changes.zip

that has 3 zip files for each setting.... let me know what else I can do :)

**Comment by skeptical** [comment] 2015-04-13 19:44
Thx, so ```upnpAllow``` setting makes no difference it seems, the critical thing was the clean install (as you already pointed out, but it helps to confirm :-). If you add a local video folder on the machine running UMS to your shared folders is it also empty like your NAS video folders?

**Comment by SubJunk** [comment] 2015-04-13 20:12
@Luxton79 it's interesting that the clean install made the difference, thanks for the testing! Also the picture folder bug is a known one that was introduced after 5.0.0-a1

@skeptical the folder issue is summarized at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/476#issuecomment-88267182

**Comment by Luxton79** [comment] 2015-04-13 20:16
More than happy to help, UMS is a wicked product!

**Comment by skeptical** [comment] 2015-04-13 21:37
@SubJunk my bad, didn't read your photo folder description closely enough :P, now I remember, and @SharkHunter's own xbox(es) didn't have this problem even though some obviously do.  It seems it should be possible to feed pseudo-paths that would satisfy the xbox, though I don't have one myself to try :).

**Comment by SubJunk** [comment] 2015-04-13 22:31
@skeptical I can probably borrow an Xbox 360 again to run tests

**Comment by SubJunk** [comment] 2015-04-14 07:24
Here are a couple more potential testers for us too http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=3218

**Comment by SubJunk** [comment] 2015-04-15 06:53
@skeptical another person's detection issues have been fixed by using JRE 8 instead of JRE 7 http://www.universalmediaserver.com/forum/viewtopic.php?p=16026
How strange

**Comment by skeptical** [comment] 2015-04-15 11:49
@SubJunk yeah, it may also have to do with doing an actual clean install in the process of switching JREs.  We have examples of the visibility issue with JRE7 too, as I recall.  Some of the head-scratching is due to the fact that all we know is whatever the affected users happen to mention.

Btw I have a shot-in-the-dark fix for the xbox/globalid thing, will put it up for shooting down soon :).

**Comment by SubJunk** [comment] 2015-04-15 21:47
@skeptical I haven't noticed examples of the issue with JRE 7 but at first I wasn't paying attention to the JRE version so must have missed it. That's exciting about the globalid thing!

**Comment by skeptical** [comment] 2015-04-16 14:40
@SubJunk don't get your hopes up too much, it's just a stab :)

@Luxton79 can you please try [this patch](http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=16065#p16065) and post TRACE logs either way (using official UMS 5.1.2).

**Comment by SubJunk** [comment] 2015-04-18 04:31
It seems that the patch by @skeptical has worked for one forum user, yay!

**Comment by Luxton79** [comment] 2015-04-20 15:01
It works!  Looks great!

http://www.calgarypitbull.com/ums_dbg-04-20.zip

Again, sorry for the delay... had some family issues out of town.  Back for a while now though!

**Comment by skeptical** [comment] 2015-04-20 16:43
@Luxton79 thx :). Can you please post logs showing an attempt at playback?

**Comment by Luxton79** [comment] 2015-04-23 13:11
Absolutely, here ya go!

http://www.calgarypitbull.com/ums_dbg-04-23.zip

**Comment by Luxton79** [comment] 2015-04-23 13:51
Now... if only there was a way to get the xbox to play the next file in sequence... I like Microsoft, but damn, that should at least be a selectable setting! lol

**Comment by Luxton79** [comment] 2015-04-29 12:18
So, I've run into something new, and I'm not sure if it's something I've done, or something in the new version.  On both my PS3 and xbox, the audio on a lot of the videos I have comes through like chipmunks... which, while hilarious, makes it difficult to watch anything.  The video is normal speed, but the audio is SUPER fast.

Any ideas what I may have done, or what might help?  Like I said, I'm not sure if it's the new version or not, which is why I'm posting here and starting a new thread.

**Comment by SubJunk** [comment] 2015-04-29 20:04
@Luxton79 that can be caused by AviSynth, check the engine order :)

**Comment by valib** [comment] 2015-04-29 22:19
@SubJunk  I think that this is a FFmpeg bug. I have the same problem for some videos with resolution less than SD or HD. Mencoder works OK.

**Comment by SubJunk** [comment] 2015-04-30 07:20
@valib would be keen to grab logs and a test file. I remember MEncoder used to have that problem with Game of Thrones files because the previews are in 2.0 audio but the main show is 5.1, and MEncoder didn't like the switch. I haven't seen it with other files though.

**Comment by Luxton79** [comment] 2015-04-30 13:56
I did indeed change the order of the engines, but that was a while ago... maybe I just haven't tried any files before that are messed up now.  I had to change them though because my stupid xbox doesn't like the mencoder engine and won't play much at all when that's primary...

**Comment by SubJunk** [comment] 2015-04-30 19:46
@Luxton79 the default order is FFmpeg, MEncoder, tsMuxeR, and the others disabled. You might want to try a clean install which will reset your settings.

**Comment by valib** [comment] 2015-05-09 22:58
@SubJunk  sorry to be so late but I was on holiday abroad. The log for not synchronized videos is at http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=16370#p16370

**Comment by Sami32** [comment] 2016-07-23 00:25
@SubJunk @valib Could this issue be closed now ? if the audio fast speed is really a FFmpeg issue.

**Comment by SubJunk** [comment] 2020-02-24 03:16
It looks like the main issue here was resolved by @skeptical and then we were getting sidetracked down other bugs so I'm going to close it. It was cool to read through it all and see all of this collaboration. Thanks everyone

**Closed by SubJunk** 2020-02-24 03:16 UTC
