### ISSUE TITLE
UMS scans the entire disk instead of chosen media folder

### ISSUE THREAD

**Issue by TacticalCode** [UniversalMediaServer/UniversalMediaServer#1411] opened 2017-10-31 08:26 UTC
I downloaded the latest UMS yesterday to test streaming to a FireTV Stick. I'm running Linux (arch) and started UMS by typing java -jar ums.jar in a terminal. After setting some options with help of the first-start-wizard and GUI, I added a folder to share and noticed strange things coming up in the terminal I launched UMS in:

> INFO  00:01:05.869 [main] Universal Media Server is now available for renderers to find
> INFO  00:02:35.330 [AWT-EventQueue-0] Setting default renderer to "Chromecast"
> INFO  00:03:04.407 [AWT-EventQueue-0] Setting Audio thumbnails import: None
> WARN  00:04:55.787 [Library Scanner] Can't read directory: /boot/lost+found
> WARN  00:04:56.008 [Library Scanner] Can't read directory: /etc/audisp/plugins.d
> WARN  00:04:56.448 [Library Scanner] Can't read directory: /etc/cups/ssl
> WARN  00:04:56.811 [Library Scanner] Can't read directory: /etc/libvirt/secrets
> WARN  00:04:56.827 [Library Scanner] Can't read directory: /etc/luks-keys
> WARN  00:04:56.837 [Library Scanner] Can't read directory: /etc/lvm/cache
> WARN  00:04:56.889 [Library Scanner] Can't read directory: /etc/NetworkManager/system-connections
> WARN  00:04:56.895 [Library Scanner] Can't read directory: /etc/openvpn/client
> WARN  00:04:56.896 [Library Scanner] Can't read directory: /etc/openvpn/server
> WARN  00:04:56.902 [Library Scanner] Can't read directory: /etc/pacman.d/gnupg/openpgp-revocs.d
> WARN  00:04:56.902 [Library Scanner] Can't read directory: /etc/pacman.d/gnupg/private-keys-v1.d
> WARN  00:04:56.938 [Library Scanner] Can't read directory: /etc/polkit-1/rules.d
> WARN  00:04:56.963 [Library Scanner] Can't read directory: /etc/samba/private
> WARN  00:04:57.372 [Library Scanner] Can't read directory: /etc/sudoers.d
> WARN  00:04:57.449 [Library Scanner] Can't read directory: /etc/vmware/ssl

I can confirm 100% there is only 1 path in "Shared folders", which is within my home directory, and it does not contain spaces. So why is UMS scanning (presumably) my entire disk and all other mounted disks, instead of just the specified media folder?

As I saw that pop up in the log, I hit CTRL-C and rm -r'd UMS to hell, so I don't have my config that was used or verbose logs. But everything I configured was through UI, and if at all, I changed settings to yield more privacy. I think I remember setting some option not to connect to networks for meta info on files. Would be interesting to see if UMS honored that, or sent information about files outside the media dir to the internet, too.

UMS/LibraryScanner shouldn't try to access anything outside my home directory if not explicitly configured to do so.

**Comment by Nadahar** [comment] 2017-10-31 13:12
@TacticalCode Although you don't specify which version, it seems that you have tested the latest release candidate of 7.0.0, because it has a bug that makes it scan the entire harddrive on startup.

If you use the latest stable version, which is 6.7.4, you shouldn't experience that. It should be added though, that you need to push the "restart" button in UMS after changing the shared folders for that to "register". Some times, for reasons we haven't fully figured out, that isn't enough and a full application restart is needed. 

UMS' default behaviour (a default I personally don't think is very good), is that all local disks are shared if no folders are shared explicitly.

To sum it up, use the latest 6.x.x version, configure your shared folders and then restart UMS and everything should be as expected. 

If the log file potentially contains "compromising" information after scanning places it shouldn't, you should delete the log file - not the application files. The determination of the log file location is a bit complicated, especially on Linux:
```java
if (Platform.isLinux()) {
	if (LOGGER.isTraceEnabled()) {
		LOGGER.trace("getDefaultLogFileFolder: System is Linux, trying \"/var/log/UMS/{}/\"", System.getProperty("user.name"));
	}
	final File logDirectory = new File("/var/log/UMS/" + System.getProperty("user.name") + "/");
	if (!logDirectory.exists()) {
		if (LOGGER.isTraceEnabled()) {
			LOGGER.trace("getDefaultLogFileFolder: Trying to create: \"{}\"", logDirectory.getAbsolutePath());
		}
		try {
			FileUtils.forceMkdir(logDirectory);
			if (LOGGER.isTraceEnabled()) {
				LOGGER.trace("getDefaultLogFileFolder: \"{}\" created", logDirectory.getAbsolutePath());
			}
		} catch (IOException e) {
			LOGGER.debug("Could not create \"{}\": {}", logDirectory.getAbsolutePath(), e.getMessage());
		}
	}
	defaultLogFileFolder = verifyLogFolder(logDirectory, "profile folder");
}

if (defaultLogFileFolder == null) {
	// Log to profile directory if it is writable.
	final File profileDirectory = new File(PROFILE_FOLDER);
	defaultLogFileFolder = verifyLogFolder(profileDirectory, "temporary folder");
}

if (defaultLogFileFolder == null) {
	// Try user-defined temporary folder or fall back to system temporary folder.
	try {
		defaultLogFileFolder = verifyLogFolder(getTempFolder(), "working folder");
	} catch (IOException e) {
		LOGGER.error("Could not determine default logfile folder, falling back to working directory: {}", e.getMessage());
		defaultLogFileFolder = "";
	}
}
```

You will usually find it in ```/var/log/UMS/username``` or your profile folder. The profile folder is by default on Linux ```$home/.config/UMS```.

The easiest way to find both the log and profile folder is to read the start of the log in the "Logs" tab in the GUI, it will state the folder paths very close to the start.

There's is no "ill intent" in this, it's just a known bug in the 7.0.0 branch. 

Regarding "sending information", UMS doesn't really send anything, but the queries made can contain the file name. As far as I know it honors the "external network" setting so that if that is turned off no information is fetched using the internet. UMS doesn't use the internet for much anyway, the things I can remember right now is: 

* Checking for updates
* Sending queries to OpenSubtitles.org to find some general information about video media and optionally download subtitles.
* Sending queries to musicbrainz.org and coverartarchive.org to get music thumbnails.
* Accessing "shared web folders" if configured. The default ```WEB.conf``` unfortunately contains some highly outdated "example" resources (I don't think anything should be configured by default). 

The only thing to worry about is if you have very compromising file names in your shared folders if someone were to intercept the queries.

**Comment by TacticalCode** [comment] 2017-10-31 15:22
The version I used was UMS-6.7.4.tgz from universalmediaserver.com
I'd say scanning all local disks by default on startup isn't what anybody would expect from a video streaming server software, which by default has an empty list of "Shared Folders".

> If the log file potentially contains "compromising" information after scanning places it shouldn't, you should delete the log file - not the application files.

Oh you! 🤣 I deleted the software that crawled through all files on my system without notifying me, because it didn't notify me about the fact it will crawl through all files on my system. Knowing UMS has the functionality to send lists of files on my system to a network, and the fact this software greeted my by crawling through my personal files, the decision to delete was an easy one. It's 2017, and that's unacceptable behavior. ⚠️ 

>a default I personally don't think is very good

I agree, it's not very good. In fact, that default isn't even good, quite the opposite. It's bad. Very bad. So bad, I opened an issue and spend time to write a ticket. That default is the worst!

>The only thing to worry about is if you have very compromising file names in your shared folders if someone were to intercept the queries.

Good thing that can't ever happen in real life! Oh wait, is BYOD a thing yet? 🤤  

I regard all information disclosure to external networks, without prior notice, as compromising my privacy. All of a user's local data is confidential (file names, file contents, system uptime, number of open TCP connections, username, amount of RAM, connected devices...) - and disclosing it compromises their privacy. If software decides to send some of that off to the internet, I'd rather be notified about that upfront, instead of it happening without my knowledge.

Again, I haven't actually tested if data was (or would have been sent, if I didn't manually disable metadata fetching). I instantly killed UMS as I saw it crawling through files it shouldn't even try to access. But if UMS did send any information about local files off to a network by default, I'd rather delete the program instead of streaming Rick and Morty to my TV. From my (a user's) perspective, only scanning for files after the user has specified the location in the GUI (or a .conf) is what UMS should do. Why would the software chose to go through all of my files, including the tens of thousands of... 😰   "system files" that I have on my drives? Save some power and my time.

I don't think anybody expects UMS to share all of the media files on their system by default. The GUI is very intuitive and there shouldn't be a problem in requiring users to add a directory they *actually* want to share to the list of shared folders.

**Comment by Nadahar** [comment] 2017-10-31 15:36
The software is open source and made buy volunteers only, so I really don't think "what you expect of a software in 2017" is that relevant. If you want to improve it, you're welcome to make a pull request.

UMS 6.x won't start scanning all your folders when you start up. It will only "scan" the folders a renderer requests. It might be that you have a renderer on your network that will start enumerating the whole "folder tree" as soon as it sees a server, but unless you do, it should not start scanning all your folders by itself.

UMS will also only "register" media files, so most of your system files will only be skipped. That said, I've said for a long time that sharing everything by default is a stupid thing to do. It's been the default for many years, and there are obviously those users that can't manage to configure it (some don't even know the concept of a file or a folder), and I guess it's with them in mind the default behaviour was chosen.

If you are paranoid about the data on your harddrives, there's a lot of software you should check very thoroughly before you run it. UMS won't make any online queries until browse that particular folder, or start a manual scan. If you disable "external network" it won't do it at all, but this is enabled by default because most people think it's nice to get album art, subtitles and some addition information about known videos. You should at the very least block software you haven't checked what does in your firewall if exposing a filename is critical. I would in fact encrypt sensitive files and folders so that they weren't readable unless you gave explicit permission by decrypting them.

**Comment by SubJunk** [comment] 2017-11-03 03:35
For a long time we have wanted a feature (or I have) that offers a user a shared folder wizard on startup if they haven't shared anything yet. If we had that we could stop sharing everything by default. For now the GUI (which is what 99% of our users use to make config changes) has that setting hidden behind a tab so noobs don't know what to do.

**Comment by SenorRoboto** [comment] 2017-12-22 09:40
I just installed 6.7.4, added some specific shared folders on my F:/ Drive, then told it to scan. It started scanning all of my drives. I canceled the scan, closed UMS, reopened UMS, told it to scan again, and then it just scanned my selected folders.

Nadahar, rather than getting defensive this walks, talks, and acts like a bug. We all use the software and obviously appreciate it being worked on, and we are filing bugs to help make the program better. This kind of behavior drives people away and makes your job harder.

**Comment by Sami32** [comment] 2017-12-22 12:42
@SenorRoboto What @Nadahar have to do with the fact that it has always been that way since PMS in 2008 ? As already explained, it has been done by design, read the owner of the project comment above your post...

It seem to me that @Nadahar is the only one wanting correctly fix it, so i don't understand your remark...perhaps your misunderstood his english explainations ?

If you build the latest master, you will have a new wizard for noobs that should help you, or you can wait until the next UMS version.

**Comment by Nadahar** [comment] 2017-12-22 15:27
@SenorRoboto I really don't understand where you think I'm being defensive. I'm simply trying to explain why things are as they are.

My view is and has always been: Sharing all folders when nothing is defined is a *bad* idea. The argument for doing it is that people that don't understand how to configure shared folder will think UMS doesn't work when they try it. I still think this annoys users more than it helps them, but it's not up to me to decide.

There's a bug involved here as well, that is well known and has been around for years. The bug is that any changes you do to shared folders isn't effectuated until you restart UMS (just pressing "Restart server" isn't enough). This has been attempted solved several times, but the problem is how UMS is designed internally. This information is cached so many places internally that the changes doesn't propagate to everywhere it needs to, and changing this without redesigning the core information structure would break a lot of other stuff and make UMS much slower because a lot of things would have to be done over and over again constantly instead of "remembering"/caching that state.

**Comment by trumpetboy101** [comment] 2018-04-11 09:36
Hi, this still seems to be an issue, now with 7.0.0 as the stable release. I am running on Linux headless, and looking through the conf files, I couldn't find anywhere to specify the media folders. Upon running for the first time, the output lines run by endlessly with warnings of "WARN  10:34:03.313 [Library Scanner] Can't read directory: /proc/5542/root/...". Is this a bug, or is there a config parameter I missed?

**Comment by SubJunk** [comment] 2018-09-26 23:34
@ghost this should be fixed now, feel free to reopen if it isn't

**Closed by SubJunk** 2018-09-26 23:34 UTC
