### ISSUE TITLE
Errors in log caused by switching to trace mode

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#3367] opened 2022-09-13 03:25 UTC
I was trying to help a user on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=15320) and found database initialization and unable to bind errors in the logs. I have noticed the same thing from other users the past few versions.

I also noticed that most of the recent logs are not in trace mode at the start. Then UMS is switched to trace mode and the logs continue showing UMS starting up but that is when these errors show up.

I think when UMS is put into trace mode, some of the old processes are still shutting down when the new ones are started so things like the database cannot be initialized.

The log file is not refreshed like it used to be and is just appended to the end of the old one instead of the old one renamed with prev and a new one started.

**Comment by SubJunk** [comment] 2022-09-15 08:37
@Mik-S-UMS weird that would start now, I thought we were getting better at shutting down reliably

**Comment by SubJunk** [comment] 2022-09-15 08:41
I just tried to reproduce it but switching between debug and trace modes works for me, both with closing UMS and not closing it

**Comment by Mik-S-UMS** [comment] 2022-09-15 14:16
I have not tried to replicate this myself but definitely seen it in a few peoples logs. I'll have a look later to find the posts on the forum that have this so you can see if there is anything common between them that could be causing it.

**Comment by Mik-S-UMS** [comment] 2022-09-16 20:58
Here are a few other logs that show this from the first page on the forum and I'm sure there are more going back further.
https://www.universalmediaserver.com/forum/viewtopic.php?p=45984#p45984
https://www.universalmediaserver.com/forum/viewtopic.php?p=46044#p46044
https://www.universalmediaserver.com/forum/viewtopic.php?p=45797#p45797

[this](https://www.universalmediaserver.com/forum/viewtopic.php?p=46159#p46159) one shows UMS starting 14 times

and the errors that are similar are
```
ERROR 2022-09-14 18:11:10.578 [AWT-EventQueue-0] Can´t find Java executable "C:\Program Files (x86)\Universal Media Server\jre17\bin\javaw", falling back to pathless execution using "javaw"
ERROR 2022-09-14 18:11:17.165 [main] com.zaxxer.hikari.pool.HikariPool HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/ProgramData/UMS/database/medias.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:168)
	at org.h2.mvstore.db.Store.<init>(Store.java:145)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at net.pms.database.Database.getConnection(Database.java:74)
	at net.pms.database.Database.open(Database.java:111)
	at net.pms.database.Database.init(Database.java:99)
	at net.pms.database.MediaDatabase.init(MediaDatabase.java:189)
	at net.pms.PMS.init(PMS.java:418)
	at net.pms.PMS.createInstance(PMS.java:955)
	at net.pms.PMS.main(PMS.java:1120)
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/ProgramData/UMS/database/medias.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	... 21 common frames omitted
ERROR 2022-09-14 18:11:28.203 [main] com.zaxxer.hikari.pool.HikariPool HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/ProgramData/UMS/database/medias.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:168)
	at org.h2.mvstore.db.Store.<init>(Store.java:145)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at net.pms.database.Database.getConnection(Database.java:74)
	at net.pms.database.Database.open(Database.java:124)
	at net.pms.database.Database.init(Database.java:99)
	at net.pms.database.MediaDatabase.init(MediaDatabase.java:189)
	at net.pms.PMS.init(PMS.java:418)
	at net.pms.PMS.createInstance(PMS.java:955)
	at net.pms.PMS.main(PMS.java:1120)
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/ProgramData/UMS/database/medias.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	... 21 common frames omitted
ERROR 2022-09-14 18:11:34.630 [main] net.pms.PMS FATAL ERROR: Unable to bind web interface on port: 9001, because: Address already in use: bind
```
I also tried it own my system and I do get those errors too and I noticed the javaw.exe process stays open for a bit after quitting UMS.

I am sure they do not alter the .xml files and are not running in headless mode.

I think it might be better for the old logs to be renamed first, a fresh log created then zip the old ones on startup. this could help older systems (like mine) to keep up.
I don't know how this could block binding of the port though.

I also need help on the original post as I think there may be a network protocol issue I know nothing about. I saw something about "Expected soap action in request" which may be relevant.

**Comment by SurfaceS** [comment] 2022-09-20 06:51
After a quick look at that, it is a "normal" things with the current code.

When someone restart from the app, the app launch a process before it exits, so the port is maybe not free / db not yet closed, etc. depending on the luck.

Also, the log file is never closed.

What can be done is
- shutdown all services before calling the new process.
- delay a bit the startup on the new process to let the other time to close.

**Comment by SurfaceS** [comment] 2022-09-20 15:04
Should be fixed

**Closed by SurfaceS** 2022-09-20 15:04 UTC
