### ISSUE TITLE
Default web content reappears after server restart

### ISSUE THREAD

**Issue by griffrawk** [UniversalMediaServer/UniversalMediaServer#2721] opened 2021-12-11 12:05 UTC
UMS 10.13.0 Linux x64 (Arch)

Whenever I delete the predefined web content that comes as default (Joe Rogan, Marvel, TED Talks etc) it reappears the next time the server is restarted. I've no interest in any of this, so please let it respect my choice.
This also happened with 10.12.0, the first version I used, but I don't know how far back this may have been an issue.

**Comment by Mik-S-UMS** [comment] 2021-12-11 21:24
I have noticed this myself and I remember on the forum the same thing happens if you delete all shared folders it will repopulate with the default options. 
If you leave at least 1 item it will stay.

**Comment by griffrawk** [comment] 2021-12-12 16:42
I've worked around this for the moment. Edit `~/.config/UMS/WEB.conf` and comment out (or delete I suppose) the web content entries I don't want. Restart the server and they're gone.

Now the GUI itself needs to do the same thing and write back the on-screen changes.

**Comment by griffrawk** [comment] 2021-12-12 16:52
Ah.... the plot thickens. If I add a new entry (could be anything) to the web content entries after commenting out all the others, the file is now overwritten with just the entry I just added (plus some header help text).

If I delete that one entry, it brings back all the defaults from `/opt/ums/WEB.conf`. This is also incorrect behaviour IMHO.

This sounds exactly like you experience with the shared folders list @Mik-S-UMS 

Seems like the delete button in the UI actually deletes from file, and as observed, unless you leave one entry it repopulates.

If instead you comment out manually, it eaves the file alone. Adding a new entry clears the file though...

**Comment by griffrawk** [comment] 2021-12-12 16:55
Ref here also: https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14724

**Comment by SubJunk** [comment] 2021-12-12 21:26
@griffrawk thanks for reporting this, there's some good detail here. I agree it's not ideal, and I will fix it.

This is a duplicate of https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2663 so please continue any discussion there.

**Closed by SubJunk** 2021-12-12 21:26 UTC
