### ISSUE TITLE
Support AudioToolBox encoding

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1179] opened 2017-02-07 10:20 UTC
I request support AudioToolBox encoding.
AudioToolBox is hardware audio tool and outputs high quality audio. It can be used through ffmpeg.
`ffmpeg -i input -c:a aac_at output`
But FfmpegAudio of UniversalMediaServer can't set it. `CustomFFmpegOptions=` doesn't override the setting of FfmpegAudio of UniversalMediaServer.

 /Applications/Universal\ Media\ Server_v8.app/Contents/Resources/osx/ffmpeg  -codecs | grep _at
ffmpeg version N-80408-g39c0b22-tessus Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --as=yasm --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-version3 --disable-ffplay --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 44.100 / 57. 44.100
  libavformat    57. 37.101 / 57. 37.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.100 /  6. 46.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
 DEA.L. aac                  AAC (Advanced Audio Coding) (decoders: aac aac_fixed aac_at ) (encoders: aac aac_at )
 DEA.L. ac3                  ATSC A/52A (AC-3) (decoders: ac3 ac3_fixed ac3_at ) (encoders: ac3 ac3_fixed )
 DEA.L. adpcm_ima_qt         ADPCM IMA QuickTime (decoders: adpcm_ima_qt adpcm_ima_qt_at )
 DEA..S alac                 ALAC (Apple Lossless Audio Codec) (decoders: alac alac_at ) (encoders: alac alac_at )
 DEA.L. amr_nb               AMR-NB (Adaptive Multi-Rate NarrowBand) (decoders: amrnb amr_nb_at libopencore_amrnb ) (encoders: libopencore_amrnb )
 DEA.L. eac3                 ATSC A/52B (AC-3, E-AC-3) (decoders: eac3 eac3_at )
 DEA.L. gsm_ms               GSM Microsoft variant (decoders: gsm_ms gsm_ms_at libgsm_ms ) (encoders: libgsm_ms )
 DEA.L. ilbc                 iLBC (Internet Low Bitrate Codec) (decoders: ilbc_at ) (encoders: ilbc_at )
 D.A.L. mp1                  MP1 (MPEG audio layer 1) (decoders: mp1 mp1float mp1_at )
 DEA.L. mp2                  MP2 (MPEG audio layer 2) (decoders: mp2 mp2float mp2_at ) (encoders: mp2 mp2fixed )
 DEA.L. mp3                  MP3 (MPEG audio layer 3) (decoders: mp3 mp3float mp3_at ) (encoders: libmp3lame )
 DEA.L. pcm_alaw             PCM A-law / G.711 A-law (decoders: pcm_alaw pcm_alaw_at ) (encoders: pcm_alaw pcm_alaw_at )
 DEA.L. pcm_mulaw            PCM mu-law / G.711 mu-law (decoders: pcm_mulaw pcm_mulaw_at ) (encoders: pcm_mulaw pcm_mulaw_at )
 D.A.L. qdm2                 QDesign Music Codec 2 (decoders: qdm2 qdm2_at )
 D.A.L. qdmc                 QDesign Music (decoders: qdmc_at )

**Comment by Nadahar** [comment] 2017-02-07 12:50
@onon765trb Do you have a sample files for testing?

**Comment by Sami32** [comment] 2017-02-07 15:55
Apple world ;)
https://ffmpeg.org/pipermail/ffmpeg-devel/2016-March/191817.html

**Comment by Nadahar** [comment] 2017-02-07 16:11
@onon765trb Do you mean to transcode to or from "AudioToolBox" AAC? If you mean transcode to, I doubt that is a very good solution - very few renderers are from Apple. I also doubt that this codec har a DLNA profile.

**Comment by onon765trb** [comment] 2017-02-08 09:43
We can use AudioToolBox encoding by only execute
`ffmpeg -i input -c:a aac_at  output`
not
`ffmpeg -i input -c:a aac  output`.
Only not `aac` but `aac_at`. very easy.

I use `aac_at` with `CustomFFmpegOptions= -c:a aac_at`. It override  `-c:a aac`.
But `CustomFFmpegOptions= -c:a aac_at` isn't binding for FFmpeg Audio settings.

As shown by [https://ffmpeg.org/pipermail/ffmpeg-devel/2016-March/190487.html](url), the developper of FFmpeg, Carl Eugen, give credit it.

**Comment by Sami32** [comment] 2017-02-08 14:46
@onon765trb Doesn't need a specific issue for that, as it concern only few user with this specific need.
It will not set in the interface, as many users find it already to crowded.

So i'll close this issue as i consider that's a duplicate of this issue:
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1181

If you disagree feel free to reopen it.

**Closed by Sami32** 2017-02-08 14:46 UTC
