### ISSUE TITLE
Configuration changes not saving

### ISSUE THREAD

**Issue by boblatimer** [UniversalMediaServer/UniversalMediaServer#3689] opened 2022-12-14 20:44 UTC
I have just updated to the latest version 12.1.

When I reboot my machine the GUI opens in a browser, which I don't want. I found the setting to turn it off but it won't allow me to save the setting.

Do I need to revert to the previous version?

**Comment by Mik-S-UMS** [comment] 2022-12-14 22:05
I had the same problem. I found the setting but it would not save it. I have had a few computer issues after some upgrades so I thought it was related to them.

I used the "Edit UMS configuration file manually" option in the java GUI to set `web_gui_on_start = false` to change it.

There was some error message in the notification but is disappears too fast to read.

**Comment by boblatimer** [comment] 2022-12-14 23:42
Thanks very much Mik. Glad it's not just me.


Could you please give me an idiot's guide on how to use the "Edit UMS configuration file manually" option in the java GUI to set web_gui_on_start = false to change it.

**Comment by Mik-S-UMS** [comment] 2022-12-15 00:59
Just open up the Java GUI, go to general settings then click the "Edit UMS configuration file manually" button to open up the config file.
For me the last line was `web_gui_on_start =` just change that to `web_gui_on_start = false`

**Comment by SubJunk** [comment] 2022-12-15 02:26
Oh yeah I can see certain settings aren't saving. I'll fix that

**Comment by boblatimer** [comment] 2022-12-15 02:39
Thanks.

**Comment by SubJunk** [comment] 2022-12-15 04:35
I have fixed this now. If you let me know your operating system I can upload the fixed version for you

**Comment by boblatimer** [comment] 2022-12-15 04:42
Thank you very much for that.  I'm running Windows 10.

**Comment by SubJunk** [comment] 2022-12-15 07:02
Cool, please let me know if this works https://www.universalmediaserver.com/uploads/UMS-boblatimer.exe

**Comment by boblatimer** [comment] 2022-12-15 23:52
Not sure whether it's something I'm doing but it doesn't work for me.

I uninstalled the previous version and installed this one.

The first thing I noticed was that menu that comes up when right-clicking on the icon in the task bar is:

Web player
Settings
Settings (old)
Quit

The first two do nothing and the third takes me to the main panel.

Version 12.01 gives a menu of:

Web player
Web Interface
Main panel
Quit

The setting for the web interface on start-up is reached by clicking on the "Web Interface" which means in the latest version it's difficult to get to it.  I finally managed to get there and changed the setting but it wouldn't save as before.

In the meantime I'll go back to 12.01 and change that setting using the "Edit UMS configuration file manually" in the advanced settings in the Main panel.

Robert.

**Comment by SubJunk** [comment] 2022-12-16 01:37
The "Settings" option is supposed to take you to the web interface like before, and it works for me.
The setting saves for me, can you try again? I attached which setting I mean
<img width="604" alt="image" src="https://user-images.githubusercontent.com/584228/208001952-097d8323-7d0f-4ae5-a37b-eb1bfd3ca06c.png">

If it still doesn't work it would be useful to get logs

**Comment by boblatimer** [comment] 2022-12-16 03:51
I uninstalled 12.0.1 again and installed the test version.

You're correct in that "Settings" takes me to the web interface. So I changed the "Launch GUI..." setting and tried to save but it still wouldn't save.

I've attached a copy of the log.

**Comment by SubJunk** [comment] 2022-12-16 05:35
@boblatimer thanks for the logs, we will need TRACE logs for more details. Please follow the instructions at https://github.com/UniversalMediaServer/UniversalMediaServer/blob/main/issue_template.md
I can't reproduce the problem myself so will need to rely on the logs :)

**Comment by Mik-S-UMS** [comment] 2022-12-16 05:35
I just tested this and it does gives the notification
```
Error
Your configuration changes were not saved. Please click here to report the bug to us.
```

I was monitoring the UMS.conf in notepad++ and I can see that it is changing the setting but I think I can see why it is still causing problems.
The setting is changed to `web_gui_on_start =true` or `web_gui_on_start =false`, notice no space after `=`.
I thought I had it working by adding the space back before changing the setting but I can't reproduce it now.

**Comment by SubJunk** [comment] 2022-12-16 19:33
The fix for some of this has been merged now, but the `Your configuration changes were not saved.` is a different thing so I'll keep this open for that

**Comment by boblatimer** [comment] 2022-12-17 03:20
Okay, I've done that using version 12.0.1 and the trace log is attached.

Now the strange thing is that when running the trace I switched to the web interface to change the "GUI in a browser" setting from no tick to ticked.  I hit Save twice and both times it told me it couldn't save the setting. But when I started UMS again it DID open the browser. (I previously had it set so that it didn't open the browser using the .conf file edit approach in the main panel.)

So I went back and unticked it and again it told me it couldn't save. When I restarted UMS it did open the web browser, so it HADN'T saved it that time.

Hope all that helps.

**Comment by SubJunk** [comment] 2022-12-21 21:31
@boblatimer I don't think the attachment worked, maybe it doesn't work via email.
Can you please let me know if this version works https://www.universalmediaserver.com/uploads/UMS-OldMan100.exe

**Comment by boblatimer** [comment] 2022-12-21 23:33
I assume when you wrote “I don't think the attachment worked, maybe it doesn't work via email.” you meant that the trace I sent you didn’t reflect the previous test version you sent to me.  As I pointed out in my email, I ran the trace on version 12.0.1, not on the test version.

So this time I completely uninstalled UMS. (Interesting that when I went to uninstall it I found two versions of UMS – it looked like there was a 32-bit version and a 64-bit version so I uninstalled them both.)

I then ran CCleaner, rebooted, ran CCleaner again and then installed UMS-OldMan100.exe. (Not sure about the implications of the OldMan tag. 😊 )

Once it had installed, it opened the Web Interface.  I was able to untick the “run GUI in a browser on startup” and it saved okay.

If I right-click on the UMS icon in the task bar I get:

Web player
Settings
Settings (old)
Quit

If I click on “Settings” I get a web interface but the only thing I have access to is “My Account”. I can no longer get to the other settings such as the “GUI in a browser” one.

Version 12.01 gives a menu of:

Web player
Web Interface
Main panel
Quit

I think the 12.0.1 version is a better description.

Hope that helps.

Regards,

Bob.

**Comment by SubJunk** [comment] 2022-12-22 04:36
It's good the changes are saving now, thanks for confirming it.

The "My Account" being the only section you can access seems strange. What do you see if you open the top-right menu? For me it shows:
![image](https://user-images.githubusercontent.com/584228/209057097-50874ba3-3325-4358-badb-c0e875cffe8f.png)

**Comment by boblatimer** [comment] 2022-12-22 04:58
Really strange.

When it opened right after installation it looked exactly like yours, so I could change the GUI setting in "Server Settings".

After doing that and restarting to make sure that it didn't open the web interface on startup, it looked like yours but without the "Shared Content", "Tools" and "Server Setting" lines.

I've just had another look now (the computer was probably rebooted a couple of times since the installation) and it looks exactly like yours.

Robert.

**Comment by Mik-S-UMS** [comment] 2022-12-22 05:13
It works for me too. I did find one thing but I'll make a separate issue for that.

**Comment by SubJunk** [comment] 2022-12-23 23:10
@boblatimer that menu state you described would occur if the user you are logged in as doesn't have permission to view those settings, or maybe if you're not logged in

**Comment by SubJunk** [comment] 2022-12-23 23:10
I'm going to close this issue now since it is sprawling but please make new issues if you notice other problems

**Closed by SubJunk** 2022-12-23 23:10 UTC
