### ISSUE TITLE
Java 9 problem in the future

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#1444] opened 2018-01-30 21:12 UTC
@UniversalMediaServer/developers after I install the JDK 9.0.4 the Eclipse is showing this warning: 
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jgoodies.looks.FontPolicies$DefaultWindowsPolicy (file:/C:/Users/Libor/.m2/repository/com/jgoodies/jgoodies-looks/2.7.0/jgoodies-looks-2.7.0.jar) to method sun.font.FontUtilities.fontSupportsDefaultEncoding(java.awt.Font)
WARNING: Please consider reporting this to the maintainers of com.jgoodies.looks.FontPolicies$DefaultWindowsPolicy
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

We use the last free version of `Jgoodies` for all GUI and when it will be denied in a future Java release we will have a serious problem. The solution is either to ask `Jgoodies` developer to give us permission to use the latest version without pay a fee (because the UMS is an Open Source project) or refactor the GUI with any alternative layout managers.

**Comment by Nadahar** [comment] 2018-01-31 09:59
This particular problem only applies to jgoodies-looks. It's caused by Oracle's stupid decisions and nothing technical, so for all I care people should just stay away from Java9. My guess is that this will affect a lot of projects though, and that somebody will find a solution. Forking jgoodies-looks and fixing just that may be the most obvious solution, and I find it likely that someone will do that at some stage. If not, we might have to do it ourselves.

Alternatively another way of achieving the same could be found. From what I can see jgoodies-looks is only used in ```LooksFrame```, and if you comment out the imports 
```Java
import com.jgoodies.looks.Options;
import com.jgoodies.looks.plastic.PlasticLookAndFeel;
import com.jgoodies.looks.windows.WindowsLookAndFeel;
```
...you can easily see what must be replaced. It seems like it only concerns ```LookAndFeel```, and ```WindowsLookAndFeel``` in particular. It might be possible to find a substitute.

```PlasticLookAndFeel``` is so terrible that I don't think that would be a loss, and it seems it's only used as a fallback:
![com-jgoodies-looks-plastic-plasticlookandfeel](https://user-images.githubusercontent.com/12900583/35616490-ab788960-0675-11e8-8038-f83c5016fdb1.jpg)

 Any other ugly L&F could probably might as well be used as a fallback.

**Comment by SubJunk** [comment] 2018-04-21 05:42
I had a brief email exchange with the developer of JGoodies in 2015 and it wasn't possible for him to offer us the use of newer versions. He seems like a really nice guy and I empathize with his position. I just sent him a quick email to check if anything has changed and I'll let you guys knows what he says.

**Comment by Nadahar** [comment] 2018-04-21 08:03
He can't let us use the newer version in an open source project, it would make it available to everybody. The only thing he could do, is to release an update to the latest free version where the Java 9/10/11 compatibility is fixed without all the other stuff.

**Comment by SubJunk** [comment] 2019-09-09 09:24
Now we are locked at Java 8 so it's not a problem

**Closed** 2019-09-09 09:23 UTC
