### ISSUE TITLE
WindowsNamedPipe creation problem with UMS 5.3.0 on Windows, Java 8 64bit

### ISSUE THREAD

**Issue by konrada** [UniversalMediaServer/UniversalMediaServer#714] opened 2015-10-30 18:59 UTC
When trying to transcode:
TRACE 2015-10-30 19:27:43.897 [New I/O worker #7] Looking for an audio track with lang: eng
TRACE 2015-10-30 19:27:43.897 [New I/O worker #7] Matched audio track: id: 0, lang: en, audio track title from metadata: Surround, audio codec: AC3, sample frequency:48000, number of channels: 6, bits per sample: 16
TRACE 2015-10-30 19:27:43.897 [New I/O worker #7] Searching for a match for: en with eng and off
TRACE 2015-10-30 19:27:43.897 [New I/O worker #7] Disabled the subtitles: id: 0, type: UNKNOWN, lang: off
DEBUG 2015-10-30 19:27:43.897 [New I/O worker #7] Reading engines: "ffmpegvideo,mencoder,ffmpegaudio,tsmuxeraudio,ffmpegwebvideo,vlcwebvideo,vlcvideo,mencoderwebvideo,vlcaudio,ffmpegdvrmsremux,rawthumbs" (default: "ffmpegvideo,mencoder,tsmuxer,ffmpegaudio,tsmuxeraudio,ffmpegwebvideo,vlcwebvideo,vlcvideo,mencoderwebvideo,vlcaudio,ffmpegdvrmsremux,rawthumbs")
DEBUG 2015-10-30 19:27:43.897 [New I/O worker #7] Reading maximum_bitrate: "0" (default: "90")
TRACE 2015-10-30 19:27:43.897 [New I/O worker #7] Using the video bitrate limit from the renderer config (25) which is lower than the one from the program settings (25)
TRACE 2015-10-30 19:27:43.897 [New I/O worker #7] Halving the video bitrate limit to 12500
DEBUG 2015-10-30 19:27:43.897 [New I/O worker #7] Reading DefaultVBVBufSize: true (default: false)
TRACE 2015-10-30 19:27:43.897 [New I/O worker #7] Adjusting the video bitrate limit to 11000 to make room for audio
DEBUG 2015-10-30 19:27:43.897 [New I/O worker #7] Creating pipe \\.\pipe\ffmpegvideo_58_1446229663897
DEBUG 2015-10-30 19:27:43.925 [New I/O worker #7] Caught exception
java.lang.IllegalArgumentException: Unrecognized calling convention: 3
	at com.sun.jna.Native.invokePointer(Native Method) ~[ums.jar:5.3.0]
	at com.sun.jna.Function.invokePointer(Function.java:477) ~[ums.jar:5.3.0]
	at com.sun.jna.Function.invoke(Function.java:411) ~[ums.jar:5.3.0]
	at com.sun.jna.Function.invoke(Function.java:323) ~[ums.jar:5.3.0]
	at com.sun.jna.Library$Handler.invoke(Library.java:236) ~[ums.jar:5.3.0]
	at com.sun.proxy.$Proxy2.CreateNamedPipeA(Unknown Source) ~[na:na]
	at net.pms.io.WindowsNamedPipe.<init>(WindowsNamedPipe.java:166) ~[ums.jar:5.3.0]
	at net.pms.io.PipeProcess.<init>(PipeProcess.java:60) [ums.jar:5.3.0]
	at net.pms.io.PipeProcess.<init>(PipeProcess.java:67) [ums.jar:5.3.0]
	at net.pms.encoders.FFMpegVideo.launchTranscode(FFMpegVideo.java:1032) [ums.jar:5.3.0]
	at net.pms.dlna.DLNAResource.getInputStream(DLNAResource.java:2922) [ums.jar:5.3.0]
	at net.pms.network.RequestV2.answer(RequestV2.java:374) [ums.jar:5.3.0]
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:300) [ums.jar:5.3.0]
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:256) [ums.jar:5.3.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.3.0]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [ums.jar:5.3.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.3.0]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [ums.jar:5.3.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [ums.jar:5.3.0]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [ums.jar:5.3.0]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [ums.jar:5.3.0]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [ums.jar:5.3.0]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [ums.jar:5.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_20]

**Comment by elmokono** [comment] 2015-11-17 02:39
Same problem here, Win 7 Home Premium x86 / Java 8.45 / UMS 5.3.0

23:07:35 DEBUG Starting transcode/remux of The Amazing Spider-Man 2 (2014).mp4 with media info: container: mp4, bitrate: 2080362, size: 2209039217, video tracks: 1, audio tracks: 1, subtitle tracks: 1, video codec: h264, duration: 02:21:34.00, width: 1920, height: 800, frame rate: 23.976, thumb size: 2273, mime type: video/mp4, matrix coefficients: BT.709, attached fonts: false
	Audio track id: 0, lang: en, audio codec: AAC, sample frequency:48000, number of channels: 2, bits per sample: 16
	Subtitle track id: 100, type: SUBRIP, lang: es, externalFile: D:\Plex\Movies\The Amazing Spider-Man 2 (2014)\The Amazing Spider-Man 2 (2014).srt, external file character set: ISO-8859-1
23:07:35 DEBUG Creating pipe \\.\pipe\ffmpegvideo_79_1447726055187
23:07:35 DEBUG Caught exception
java.lang.IllegalArgumentException: Unrecognized calling convention: 3
	at com.sun.jna.Native.invokePointer(Native Method) ~[ums.jar:5.3.0]
	at com.sun.jna.Function.invokePointer(Function.java:477) ~[ums.jar:5.3.0]
	at com.sun.jna.Function.invoke(Function.java:411) ~[ums.jar:5.3.0]
	at com.sun.jna.Function.invoke(Function.java:323) ~[ums.jar:5.3.0]
	at com.sun.jna.Library$Handler.invoke(Library.java:236) ~[ums.jar:5.3.0]
	at com.sun.proxy.$Proxy2.CreateNamedPipeA(Unknown Source) ~[na:na]
	at net.pms.io.WindowsNamedPipe.<init>(WindowsNamedPipe.java:166) ~[ums.jar:5.3.0]
	at net.pms.io.PipeProcess.<init>(PipeProcess.java:60) [ums.jar:5.3.0]
	at net.pms.io.PipeProcess.<init>(PipeProcess.java:67) [ums.jar:5.3.0]
	at net.pms.encoders.FFMpegVideo.launchTranscode(FFMpegVideo.java:1032) [ums.jar:5.3.0]
	at net.pms.dlna.DLNAResource.getInputStream(DLNAResource.java:2922) [ums.jar:5.3.0]
	at net.pms.network.RequestV2.answer(RequestV2.java:374) [ums.jar:5.3.0]
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:300) [ums.jar:5.3.0]
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:256) [ums.jar:5.3.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.3.0]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [ums.jar:5.3.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.3.0]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [ums.jar:5.3.0]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [ums.jar:5.3.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.3.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [ums.jar:5.3.0]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [ums.jar:5.3.0]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [ums.jar:5.3.0]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [ums.jar:5.3.0]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [ums.jar:5.3.0]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [ums.jar:5.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_45]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]
23:07:35 DEBUG Starting C:\Program Files\Universal Media Server\win32\ffmpeg.exe -y -loglevel info -i D:\Plex\Movies\The Amazing Spider-Man 2 (2014)\The Amazing Spider-Man 2 (2014).mp4 -filter_complex subtitles=D\\:/Plex/Movies/The Amazing Spider-Man 2 (2014)/The Amazing Spider-Man 2 (2014).srt:1920x800:ISO-8859-1 -bufsize 10000000 -maxrate 9000000 -crf 23 -ab 448k -c:v libx264 -tune zerolatency -preset ultrafast -level 31 -pix_fmt yuv420p -async 1 -fflags +genpts -c:a libmp3lame -ac 2 -b:v 35000k -bufsize 35000k -f matroska \\.\pipe\ffmpegvideo_79_1447726055187
23:07:35 DEBUG Reading pipe: \\.\pipe\ffmpegvideo_79_1447726055187

**Comment by Nadahar** [comment] 2015-11-17 06:24
@konrada @elmokono 
Do you have any firewalls active on the UMS computer? If so, try disabling it. Firewalls sometimes block pipe creation.

If that's not it, do you have JRE 1.8.0.65 installed? We have had reports of trouble with this version, downgrading to 1.8.0.60 is the workaround for now. We have to figure out if this is a bug in 1.8.0.65 or if we have to rewrite our pipe creation process for 1.8.0.65, but this far we haven't been able to find any information that sheds any light on that situation.

**Comment by garrett-mccutcheon** [comment] 2015-11-25 22:36
I've attached the debug log where I had this same issue. Was running 1.8.0_66. Disabled Windows 10 firewall (for both public and private networks) with no success. Uninstalled JRE 1.8.0.66 (and x64 of same) and deleted /ProgramData/Oracle. Installed JRE 1.8.0_60. Launched UMS, Windows Firewall prompted for permission for JRE - granted for both Public and Private Networks. Now UMS works as expected.

Sorry I can't provide any additional insight wrt the _problem_ but hopefully the confirmation of rollback and firewall can help in diagnosis.

[debug.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/44453/debug.log.txt)

**Comment by Nadahar** [comment] 2015-11-25 22:45
@UniversalMediaServer/developers @SubJunk This seems to be a problem we need to tackle rather fast, as I expect many to update their Java versions automatically.

**Comment by valib** [comment] 2015-11-26 00:26
This is strange. I installed the Java JRE 1.8.0.66 (this was not offered for me automatically) and when I run UMS for the first time I had the same error. But when I run the UMS several times after that it works normally.

**Comment by Nadahar** [comment] 2015-11-26 01:09
@valib That what needs a clean installation? The JRE? I doubt it, I mean to remember reading about others that had tried to uninstall and reinstall JRE without any change. What I'm wondering is if you're building UMS yourself before running it, or running a downloaded version? Maybe there's something there, that if it's compliled with JDK 1.8.0.66 it runs, but not if compiled on an earlier version?

It's the JNA stuff that goes wrong, it's hard to see what we could do wrong in that situation. I recently updated JNA to 4.2.1 in the 6.0.0 branch, maybe we should do that in master as well. There could be some compatibility issues resolved there, although I don't see anything obvious when looking at [their change log] (https://github.com/java-native-access/jna/blob/master/CHANGES.md).

**Comment by elmokono** [comment] 2015-11-26 02:11
I installed UMS 5.1.4 and works fine, Java 7 and 8 (no firewall, no UAC, local admin privileges, no antivirus). 
I'll upgrade UMS until I find which version stopped worked.

**Comment by Nadahar** [comment] 2015-12-10 22:46
@elmokono Have you had any progress with this?

**Comment by richard-kong** [comment] 2016-01-01 02:26
I had the same problem, I had the pipe creation error. I am running Windows 7 x64, Java 1.8.0_60 UMS 5.4

I was able to fix by downgrading to UMS 5.2.1

```DEBUG 2015-10-30 19:27:43.897 [New I/O worker #7] Creating pipe \.\pipe\ffmpegvideo_58_1446229663897
DEBUG 2015-10-30 19:27:43.925 [New I/O worker #7] Caught exception
java.lang.IllegalArgumentException: Unrecognized calling convention: 3```

**Comment by Nadahar** [comment] 2016-01-01 06:16
@richard-kong Strange and interesting. I thought 1.8.0_60 was "safe" regarding this problem. 

Several people have had it resovled by downgrading their Java version to 1.8.0_60. When that turns out not to be the solution, it might indicate that the problem is with the Java installation itself. Maybe a complete uninstallation of Java and a reinstallation is what's needed?

**Comment by richard-kong** [comment] 2016-01-01 06:29
I was previously running UMS 4.2 on 1.8.0_40 with no issues, I upgraded to UMS 5.4 and got this problem. I uninstalled and reinstalled UMS but the problem persisted. After reading this issue i upgraded my Java to 1.8.0_60 (x64) which did not fix.

I also tried one of the 5.3.x builds which had the same problem.

**Comment by Nadahar** [comment] 2016-01-01 06:51
I wonder what the cause is, the problem isn't there on most installations. The error comes from something completely out of our control, it's an external library called JNA communicating with the Windows API that throws this error, and the error itself makes no sense to me.

I've compared the code and we've made no changes in the code making these calls between ```5.2.1``` and ```5.3.0```. We did hovewer upgrade JNA from ```4.1.0``` to ```4.2.0``` from ```5.2.2``` to ```5.2.3```.

If that is the cause (which seems likely right now), ```5.2.2``` should work while ```5.2.3``` should fail on your setup.

**Comment by skeptical** [comment] 2016-01-01 17:53
@Nadahar @richard-kong just a shot in the dark, but according to [this](http://stackoverflow.com/questions/33268544/error-when-getting-window-handle-using-jna#comment54367330_33268544) ```Unrecognized calling convention``` may have to do with mismatch between bitness of compiling sdk vs runtime jre.  Maybe try snapshot of jna after [this fix](https://github.com/java-native-access/jna/pull/533).

**Comment by richard-kong** [comment] 2016-01-01 22:59
@Nadahar you were right `5.2.2` works but `5.2.3` throws the `Unrecognized calling convention` exception

**Comment by Nadahar** [comment] 2016-01-02 21:46
@skeptical It looks promising, but I can't find a [compiled snapshot] (https://maven.java.net/content/repositories/snapshots/net/java/dev/jna/jna/) with this fix. Compiling takes a C compiler with config, something I know nothing about setting up. The fix should be in the next version of JNA.

We should somehow remember to check this when the next version of JNA is released. If this [stackoverflow case] (http://stackoverflow.com/questions/33268544/error-when-getting-window-handle-using-jna#comment54367330_33268544) is correct, the problem is using a 64 bit JRE. 

It would be nice if you could confirm @richard-kong, by uninstalling Java and then installing a 32 bit (latest version) of Java.

**Comment by richard-kong** [comment] 2016-01-03 01:42
@Nadahar you are right. I installed the current version of 32bit java and it all works now. I testing both 5.2.3 and 5.4.0

**Comment by Nadahar** [comment] 2016-01-03 01:48
@richard-kong Thank you, then I think we have this one resolved for now. The next version of UMS has been downgraded to JNA ```4.1.0```, and the bug will most likely be fixed by java-native-access/jna#533 for future versions even though we have to test this when the next version is released.

**Comment by SubJunk** [comment] 2016-03-25 04:16
JNA 4.2.2 has been released now. Is anyone available to test it? I'm happy to upload a version of UMS with it to test

**Comment by richard-kong** [comment] 2016-03-25 04:35
yea i can tell it, just send me a link to download the build.

**Comment by SubJunk** [comment] 2016-03-25 04:52
Great. http://www.spirton.com/uploads/UMS/UMS-jna422.exe

**Comment by richard-kong** [comment] 2016-03-25 06:20
the original error went away. Mencoder works, But now i get this when using ffmpeg:

```
15:58:38 INFO  Java: Java HotSpot(TM) 64-Bit Server VM 1.8.0_66 64-bit by Oracle Corporation
15:58:38 INFO  OS: Windows 7 64-bit 6.1

DEBUG 2016-03-25 16:05:46.071 [New I/O worker #1] Starting transcode/remux of myFile.mkv with media info: container: mkv, bitrate: 3779134, size: 672024942, video tracks: 1, audio tracks: 1, subtitle tracks: 1, video codec: h264, duration: 00:23:42.00, width: 1280, height: 720, frame rate: , muxing mode: Header stripping, mime type: video/x-matroska, attached fonts: false
	Audio track id: 0, lang: ja, audio codec: AAC, sample frequency:48000, number of channels: 2, bits per sample: 16
	Subtitle track id: 0, type: ASS, lang: en
DEBUG 2016-03-25 16:05:46.072 [New I/O worker #1] Creating pipe \\.\pipe\ffmpegvideo_57_1458885946072
DEBUG 2016-03-25 16:05:46.072 [Thread-56] Waiting for pipe connection \\.\pipe\ffmpegvideo_57_1458885946072
DEBUG 2016-03-25 16:05:46.373 [ffmpeg64.exe-8] Starting "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe" -y -loglevel fatal -i "E:\Anime\myFolder\myFile.mkv" -filter_complex "subtitles=E\\:/Anime/myFolder/myFile.mkv:si=0:charenc=ASS" -bufsize 1835000 -maxrate 44000000 -g 5 -q:v 1 -qmin 2 -qmax 3 -ab 448k -c:a ac3 -c:v mpeg2video -f vob \\.\pipe\ffmpegvideo_57_1458885946072
DEBUG 2016-03-25 16:05:46.379 [ffmpeg64.exe-8] Reading pipe: \\.\pipe\ffmpegvideo_57_1458885946072
DEBUG 2016-03-25 16:05:46.394 [ffmpeg64.exe-8] Attaching thread: ffmpeg64.exe-8
DEBUG 2016-03-25 16:05:46.486 [ffmpeg64.exe-8-2] Error initializing complex filters.
DEBUG 2016-03-25 16:05:46.487 [ffmpeg64.exe-8-2] Invalid argument
INFO  2016-03-25 16:05:47.491 [ffmpeg64.exe-8] Process "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe" has a return code of 1! Maybe an error occurred... check the log file
```

**Comment by SubJunk** [comment] 2016-03-25 10:47
@richard-kong thanks for testing that. Does that FFmpeg bug happen with UMS 6.2.0?

**Comment by SubJunk** [comment] 2016-03-25 21:05
@richard-kong I've found the bug you mentioned and will fix it before the next release, thanks for reporting it

**Closed by SubJunk** 2016-03-25 21:05 UTC
