### ISSUE TITLE
Video files bigger than 2GB "could not be parsed. And will be hidden"

### ISSUE THREAD

**Issue by zero0cool0** [UniversalMediaServer/UniversalMediaServer#1006] opened 2016-09-19 17:05 UTC
Some handbrake encoded files cannot be parsed and show as "The file {} could not be parsed. It will be hidden" where {} is the filename in question. Others work well and as expected.

mediainfo is perfectly capable of parsing the file, at least calling "mediainfo {}" from the command line outputs a sizeable amount of information (attached for one of the bad files in question).
[mediainfo1.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/480641/mediainfo1.txt)

I had a quick look at the source code and the code in question `src/main/java/net/pms/dlna/RealFile.java` at line 75 enters the if-condition because getMedia().getContainer() equals null for these files, but unfortunately I have no idea what this means.

UMS 6.5.1-SNAPSHOT
mediainfo v0.7.88
Linux 4.4.0-36-generic #55-Ubuntu

**Comment by Sami32** [comment] 2016-09-19 19:48
Please, post your log following these steps:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

Or post a link of a sample of your problematic video file (less of 30 MB will be fine) to help us reproduce this issue.

**Comment by Nadahar** [comment] 2016-09-19 20:01
@zero0cool0 There is currently a bug with MediaInfo that prevents it from parsing file names with characters outside the ASCII range on Linux and OS X. The Unicode implementation of the API is broken. These files parse just fine when using MediaInfo itself, it's only when using the API that it fails.

If this is the case for the files in question, this is a duplicate of #355. You can read more about it there. As you can see from the [MediaInfo ticket](https://sourceforge.net/p/mediainfo/bugs/925/) the author won't fix it unless he gets paid. That means it probably won't be fixed any time soon. Anybody capable of figuring out the code could probably submit a patch, otherwise it looks like paying is the only way to get it fixed. The problem itself is probably easily fixed, it seems to be some conversion issue between UTF16 and the file system character set that is the underlying problem.

**Comment by zero0cool0** [comment] 2016-09-20 05:44
@Nadahar I don't think it is the same bug, as the file names in question do not contain characters outside the ASCII range. For example, one file is called `Amadeus (1984).m4v` which IMHO is pure ASCII. The error is persistent even if I rename this to `Amadeus.m4v`.

@Sami32 I'm attaching the log zip as requested. Will also try to truncate some of the problematic video files to 30 MB, see if they still reproduce the error and share them.

Note that I made one small change to the 6.5.1-snapshot code. I've expanded the ominous Logger.info() statement in `src/main/java/net/pms/dlna/RealFile.java` ("file could not be parsed. It will be hidden") to output the value of getMedia() and getMedia().getContainer(). This is also shown in the debug.log.

[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/481689/ums_dbg.zip)

**Comment by Sami32** [comment] 2016-09-20 17:01
@zero0cool0 The code part that you are refering is just the result of an anterior parsing issue.

When i check your log, i suspect that you M4V file is malformed. As you i guess, we can play M4V files, but for you, only some of the video files that you maked are problematics.
A sample of your problematic  video file will be welcome, and as you point out, need to be verified as again problematic

In the purpose to narrow this issue:
- If you play it directly from you TV (NOT from the Web interface), did you get the same issue ?
- if you replace original MediaInfo by MediaInfo.dll 0.7.81 did you get same result ?

**Comment by Nadahar** [comment] 2016-09-20 17:30
@zero0cool0 It's not the same issue, although it behaves very similarly. Are you sure there are no permission issues, that the user running UMS has read permission for the file and its folder?

The absence of any exceptions from the parsing process itself points to something simple like not being able to find/open the file. I've tried to find some debug options for the MediaInfo API but haven't found anything this far. If anyone knows how to turn it on, it could be useful.

All the ```getMedia()``` fields will be default/null as long as the parsing isn't done, so debugging those won't tell very much. ```Container``` in this context is what we normally think of as file format, e.g MP4, MKV, WAV etc. A file without a container would have to be a raw file of some kind unless ofcourse parsing fails.

As @Sami32 says a sample file is probably needed, but even then it won't necessarily be that easy to find as not all OS'es are equal when it comes to MediaInfo. It seems to me that Windows generally have the best support, so it might be that the same files are parsable under Windows.

**Comment by zero0cool0** [comment] 2016-09-20 18:58
Thank you both.

A truncated file with 30MB does not lead to an error. I've tried multiple files.

This led me to investigate if the problematic files have something in common and lo, they are all bigger than 2GB (or bigger than 2,147,483,648 bytes exactly). Does this help narrow down the issue at all?

It's definitely not a filesystem issue as these files reside on a ext4 partition on a modern linux.

**Comment by Sami32** [comment] 2016-09-21 00:35
@zero0cool0 To have a better chance to succeed you need to cut your video file with the following command: `dd if=sample-file of=small-sample-file bs=1024 count=30000`

To make sure it's not an MediaInfo issue just set `MediaInfo = false` in your renderer configuration file and post your new log.

Testing with a standalone or CLI version, as you did, could give totally different results, depending on MediaInfo version and OS version, with the way programs get infos from.

**Comment by Nadahar** [comment] 2016-09-21 01:37
@Sami32 I'm not sure there is a traditional "renderer configuration file" for the web client.

**Comment by atamariya** [comment] 2016-09-21 10:33
@zero0cool0 You're running 32-bit JRE - that's where your problem lies. If you're on 64bit CPU, use a 64-bit JRE.

**Comment by Nadahar** [comment] 2016-09-21 15:16
> You're running 32-bit JRE

If that's correct it's an impressive limitation. There is no such file-size limit on 32 bit Windows. That basicly means that UMS with 32-bit JRE is useless for video files. This should in that case be mentioned in the Linux documentation.

**Comment by Sami32** [comment] 2016-09-21 23:04
http://users.suse.com/~aj/linux_lfs.html
https://en.wikipedia.org/wiki/Large_file_support
https://www-uxsup.csx.cam.ac.uk/pub/doc/suse/sles9/adminguide-sles9/ch18s04.html
http://serverfault.com/questions/24803/why-cant-i-create-files-larger-than-2-gb-on-linux

**Comment by Nadahar** [comment] 2016-09-21 23:21
@Sami32 I don't get why you post a bunch of links like above. What are you trying to say? I know that 32 bit Linux has this limitation, this is about running a 32 bit JRE on 64 bit Linux. It might end up giving the same result, but it's not obvious to me that it is the same thing.

**Comment by Sami32** [comment] 2016-09-22 00:15
> INFO  2016-09-20 07:35:15.935 [main] Java: OpenJDK Server VM 1.8.0_91 32-bit by Oracle Corporation
> INFO  2016-09-20 07:35:15.936 [main] OS: Linux 32-bit 4.4.0-36-generic

**Comment by Nadahar** [comment] 2016-09-22 01:28
@Sami32 Ok, I didn't check the log since I interpreted @atamariya's comment as if it was a 64 bit OS. I am a bit confused by this, are we sure that the OS string reported by Java is correct and not affected by a 32 bit JVM "not seeing" the 64 bit OS?

If it is in fact a 32 bit Linux, how is Handbrake even able to encode the files? From what I understand LFS support isn't very good. @zero0cool0 What is the true nature of your environment?

**Comment by zero0cool0** [comment] 2016-09-22 05:49
So the true nature of the environment is indeed 32 bit. It's an older system. The obvious workaround is to split the large files into chunks. Not ideal. 
@Nadahar I encode the files on another system with a 64 bit OS.

I'll close this issue as it's obviously not a UMS issue but a OS/JRE limitation.

`Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:00:59 UTC 2016 i686 i686 i686 GNU/Linux`

`$ file /usr/lib/jvm/java-8-openjdk-i386/jre/bin/java
/usr/lib/jvm/java-8-openjdk-i386/jre/bin/java: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=848ca1f93d919f43d05792f677839b9356e2f33a, stripped`

**Comment by zero0cool0** [comment] 2016-11-11 10:25
So, I'm reopening this issue because now, I do have a 64-bit system with a 64-bit operating system.

```
$ uname -a
Linux server.local 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
```
$ /usr/bin/java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

```

```
INFO  10:55:49.866 [main] Starting Universal Media Server 6.5.1
INFO  10:55:49.867 [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  10:55:49.867 [main] http://www.universalmediaserver.com
INFO  10:55:49.867 [main]
INFO  10:55:49.867 [main] Build: 7e985ea99 (2016-10-02)
INFO  10:55:49.867 [main] Java: OpenJDK 64-Bit Server VM 1.8.0_111 64-bit by Oracle Corporation
INFO  10:55:49.867 [main] OS: Linux 64-bit 4.4.0-47-generic
INFO  10:55:49.867 [main] Encoding: UTF-8
INFO  10:55:49.867 [main] Memory: 683 MB
INFO  10:55:49.869 [main] Language: English (United States)

```

And yet, UMS refuses to parse files that are bigger than 2GB
`INFO  10:56:13.382 [New I/O worker #7] The file /Video/Amadeus (1984).m4v could not be parsed. It will be hidden`

There is in fact a whole list of files that are listed similarly to the one above, and all of them are bigger than 2GB.

Any help appreciated.

**Closed** 2016-11-11 12:55 UTC

**Comment by Nadahar** [comment] 2016-11-11 13:00
@zero0cool0 I'm not sure understand your description. When you say the files "are on another system" does that mean that you have mounted them via NFS? CIFS? The 2GB limitation might be in the way it's mounted.

> The file is not hidden, but in VLC, its size is reported as 9.22 EB (Exa bytes?)

Which file is this, and the fact that the reported file size is completely off in VLC further indicates that there's something funny with this.

If I understand you correctly you also say that files larger than 2 GB placed on the local filesystem parses without error? To me, that's another indication that the problem isn't with UMS.

The thing is, there's nothing in UMS, that I'm aware of, that has a 32 bit limitation. These things are all external to UMS like JVM, OS, file systems etc.

**Comment by zero0cool0** [comment] 2016-11-11 13:04
Thanks @Nadahar. I've closed the issue again - turns out that after deleting the database (folders `data` and `database`) the problem went away. Must have been a leftover.

**Comment by Nadahar** [comment] 2016-11-11 13:05
Great to hear :+1:

**Comment by Antoniossss** [comment] 2018-01-04 21:10
I would suggest to reopen the issue. I have following INFO on the console

`The file /media/pi/EX2/MyMovie.mp4 could not be parsed. It will be hidden`

This is actual filename. 

What is strange, that file is hidden on my tablet and 2 Samsung Smart TVs but when I access it via windows explorer (not directly but via UMS) it is listed just fine and it plays in windows media player. How can it be renderer specific ??
