### ISSUE TITLE
Eclipse problems

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2111] opened 2020-06-16 19:58 UTC
I managed to setup Eclipse to start looking at UMS's code, but run into a problem with the antrun plugin. more info here https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14210&start=20
checking out an earlier version solved the issue but would like to work on the latest version of the code to keep up to date.

**Comment by Nadahar** [comment] 2020-06-16 21:43
6e57307ff1397cf2b5f8a64ad83f1cb705fdec1a broke it, and I honestly have no idea why this commit was made. It's simply not true that "it's no longer supported", I'm using the latest version of Eclipse and it still relies on this configuration to be able to handle the `antrun` plugin.

**Comment by SubJunk** [comment] 2020-06-17 00:01
@Mik-S-UMS yay welcome to GitHub, glad you made it here :)

@valib can you let us know the reasoning behind https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2016 ?

**Comment by Mik-S-UMS** [comment] 2020-06-18 20:39
@SubJunk  Thanks, still trying to get used to things.
I've gone though my notes based on what has been said on the forum and some of my ideas and put them in some sort of order. not sure if it's the best way on here but will post several related things in each issue so I'm not spamming too much :)

having a quick look though current issues on here there might be some that have been brought up before but maybe could be worth a second look.

**Comment by valib** [comment] 2020-06-18 20:52
I tried to return back and reproduce the issue which motivated me to made the PR 6e57307ff1397cf2b5f8a64ad83f1cb705fdec1a with no succes. So @SubJunk feel free to revert that commit.

**Comment by SubJunk** [comment] 2020-06-18 21:08
@Mik-S-UMS yes as you can see our list of issues is in need of organizing. I have been focusing on that lately and it is much better than it was, believe it or not, but there is a long way to go :)
In particular it would be very useful to get a sense of the priority of problems, and since you spend a lot of time on the forum you might have a good idea of that. Are there any older issues that are mentioned frequently on the forum that we could prioritize?

@valib ok no problem, thanks

**Comment by SubJunk** [comment] 2020-06-18 21:39
That's reverted now so I'll close this

**Closed by SubJunk** 2020-06-18 21:39 UTC
