### ISSUE TITLE
UMS does not handle absolute-form GET requests

### ISSUE THREAD

**Issue by mfulgo** [UniversalMediaServer/UniversalMediaServer#430] opened 2014-12-12 22:00 UTC
compiled version: c4988f0cd140c3b5b357ee9022b870a0a0c6f9e9

After seeing the following in my logs, I started to dig into the code:

```
TRACE 2014-12-12 16:29:21.961 [New I/O worker #13] Opened request handler on socket /10.0.0.2:47351
TRACE 2014-12-12 16:29:21.961 [New I/O worker #13] Request: HTTP/1.1 : GET : ttp://10.0.0.3:5001/images/icon-120.png
TRACE 2014-12-12 16:29:21.961 [New I/O worker #13] Matched media renderer "Samsung Galaxy Tab3" based on address /10.0.0.2
TRACE 2014-12-12 16:29:21.961 [New I/O worker #13] Received on socket: Host: 10.0.0.3:5001
TRACE 2014-12-12 16:29:21.961 [New I/O worker #13] Received on socket: Connection: Keep-Alive
TRACE 2014-12-12 16:29:21.961 [New I/O worker #13] Received on socket: User-Agent: asf-dms-icon
DEBUG 2014-12-12 16:29:21.961 [New I/O worker #13] HTTP User-Agent: asf-dms-icon
TRACE 2014-12-12 16:29:21.961 [New I/O worker #13] Recognized media renderer: Samsung Galaxy Tab3
TRACE 2014-12-12 16:29:21.962 [New I/O worker #13] HTTP: ttp://10.0.0.3:5001/images/icon-120.png / 0-0
TRACE 2014-12-12 16:29:21.962 [New I/O worker #13] Sent to socket: Content-Type: image/png
TRACE 2014-12-12 16:29:21.962 [New I/O worker #13] Sent to socket: Accept-Ranges: bytes
TRACE 2014-12-12 16:29:21.962 [New I/O worker #13] Sent to socket: Connection: keep-alive
TRACE 2014-12-12 16:29:21.962 [New I/O worker #13] Sent to socket: Expires: Tue, 07 Apr 2015 15:16:01 GMT
TRACE 2014-12-12 16:29:21.962 [New I/O worker #13] Sent to socket: Server: Linux-amd64-3.13.0-39-generic, UPnP/1.0, UMS/4.3.1
TRACE 2014-12-12 16:29:21.962 [New I/O worker #13] Sent to socket: Content-Length: 0
```

Note the address `ttp://10.0.3:5001/...` is missing an `h`.

I'm still digging into where it gets stripped off; I've confirmed via Wireshark that the request being sent to UMS has the `h`.

**Comment by Sami32** [comment] 2016-07-23 18:18
@mfulgo @SubJunk Did the latest UMS version solved this issue ?
I am not able to reproduce that with the actual version under WinXP 32.

**Comment by Nadahar** [comment] 2016-07-23 22:01
@Sami32 The bug is still in the [latest code](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/84cdfe9e207a9cd38684043b202b4929f748c05e/src/main/java/net/pms/network/RequestHandlerV2.java#L106), but the line number has changed from [99](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/c4988f0cd140c3b5b357ee9022b870a0a0c6f9e9/src/main/java/net/pms/network/RequestHandlerV2.java#L99) to [106](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/84cdfe9e207a9cd38684043b202b4929f748c05e/src/main/java/net/pms/network/RequestHandlerV2.java#L106) and thus @mfulgo's link no longer points to the correct line.

To figure out how to solve this bug one needs to figure out why the first character is stripped in "normal cases". It looks like the first character is normally a ```/```, but it would need to be looked into properly to be sure. The "special fix" for some Samsung TV's should also be seen in connection with this, it would be unnecessary if the URL was properly formatted from the start.

In any case the stripping of the first character should be removed from [RequestHandlerV2](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/network/RequestHandlerV2.java) and a proper logic be fitted to the [RequestV2 constructor](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/84cdfe9e207a9cd38684043b202b4929f748c05e/src/main/java/net/pms/network/RequestV2.java#L190) to handle multiple forms of request URL's.

The bug most definitly is still there, and it certainly is a bug since the HTTP standard allows this form even though it might not be used much. The HTTP standard also hints that the currently broken ```absolute-form``` might become the required form in a future version of the standard. It should probably also be looked into how V1 handles this.

@mfulgo I have a Galaxy Tab 3, but I don't know what renderer software/app and renderer profile you used. I can't seem to find anything matching the renderer config name or the very strange user-agent. I'm also guessing this is from a relatively old Android version now. It's also a bit strange to me that the renderer is recognized as a specific tablet instead of just a general Android, I wouldn't think any Android renderer software would differ it's behaviour based on the hardware used. I might simply be missing something obvious in that regard though.

**Comment by Sami32** [comment] 2016-07-26 18:12
@mfulgo Did you have same issue with UMS 3.3.0 version ?
I'm asking that because i suspect that https://github.com/UniversalMediaServer/UniversalMediaServer/commit/81800cca7d235a108d43a0d1ddc5c5b39c9aeeee could perhaps be the culprit.
I cannot compare myself since my only renderer send GET requests in the `origin-form`.

**Comment by mfulgo** [comment] 2016-07-27 04:46
Sorry Sami, I haven't worked with this probably since I opened the issue. If I have a chance, I'll fire it up and test it out. 

Alternatively, you can probably test it manually by issuing a `curl` request with the appropriate header.

**Comment by Sami32** [comment] 2016-07-27 10:45
@mfulgo Thanks for answering :-) Don't worry we are not one day near :-D

Thank you for you advice, i will try that, after learned how to do that of course ;-)

**Comment by SubJunk** [comment] 2020-02-17 07:54
This bug should have been fixed now https://github.com/UniversalMediaServer/UniversalMediaServer/blob/61730629611fa8bfcb24adf7346427829a237613/src/main/java/net/pms/network/RequestHandlerV2.java#L276
Feel free to reopen if not

**Closed by SubJunk** 2020-02-17 07:54 UTC
