### ISSUE TITLE
[idear] Select profile screen

### ISSUE THREAD

**Issue by Goten87** [UniversalMediaServer/UniversalMediaServer#237] opened 2014-02-08 17:53 UTC
well right now we have 2 shot cuts
how about u make only 1 and let us choose a profile from a nice interface screen
when we get it for the first time a default profile will be made
when we make more profiles we can choose what we want
with a timer of 1 min or something when we don't choose a profile after that minute it will always select the default

**Comment by Sami32** [comment] 2016-07-25 16:42
@Goten87 Do you mean, for selecting at the starting time, a profile depending on the renderer that will be used ?
Sorry if i didn't understood you correctly, it could come from my poor english ;-)
If it will for that purpose, i guess the developpers want first implement a database per renderer.

**Comment by Nadahar** [comment] 2016-07-25 16:54
@Sami32 Even though I don't know how many that actually use this, UMS supports multiple configuration profiles. That means different profile folders (```%programdata%\UMS``` on Windows by default```) containing differnt configuration files, database etc. 

It's posstible to specify the profile via the command line (which can be used to create a shortcut for each profile), or one can you the "Profile selection dialog" which can be started via a shortcut installed by the Windows installer as ```Universal Media Server (Select Profile)```. This profile selection dialog isn't very good, it will only give you a default ```open file dialog``` where you can choose either the folder or the configuration file.

I think @Goten87 mean that the profile selection should be integrated into the UMS interface itself instead, but that's not so easy as it might sound. The reason is the the configuration is loaded which means that you basicly have to restart UMS to change profile. Because of this integrating the profile selection in the main GUI isn't really viable without a major rewrite of a lot of things.

I'd vote for ```Won't implement``` on this one for the reason above.

**Comment by Sami32** [comment] 2016-07-25 19:19
@Nadahar Thank you for clarify things :+1: I didn't even know about that, shame on me 8-/

If i remember well, in Firefox (and maybe Thunderbird) they give the profile selection choice as in UMS.
If cannot really estimate the work that need to be done, as you told, i'm not sure many users are aware of it or need it.
In the case where many different people use UMS on the same computer, i can understand the "easiness" importance, but here again not sure that it is really necessary since UMS improved in audio/subtitles configuration or interface translation (that also need a restart, that point could be voided maybe...)

**Comment by Goten87** [comment] 2016-07-25 19:43
what i mean for this befor ums starts up a UI to select a profile

**Comment by Nadahar** [comment] 2016-07-25 20:00
My point is that the far easiest way to use profiles is by creating shortcuts directly to each profile. This can be done by modifying the command line argument in the shortcut. 

This was implemented in #690 based on #688. The problem is probably that not many people know about it, but I did add a [help page with command line argument descriptions](http://htmlpreview.github.io/?https://raw.githubusercontent.com/UniversalMediaServer/UniversalMediaServer/master/src/main/external-resources/documentation/commandline.html).

**Comment by Sami32** [comment] 2016-07-25 21:46
@Nadahar Ok, i get the "huge" ;-) So i share your opinion on that, since so much fixes and cleaning need to be done...no need to catches the Devil by the tail. Scary guy :-D
Your alternative look fair enough to me, in proportion to the users's request.

**Comment by valib** [comment] 2016-07-25 22:45
@Sami32 the info from the link is included in the UMS embedded Help. And for Wiki I did it.

**Comment by Sami32** [comment] 2016-07-26 10:41
@valib Thanks for that ;-)
I checked only after that he give me the link from Github.
I didn't have checked the Help section only wikis and the forum but i'm far to have read everything, shame on me 8-/

**Comment by polygirl** [comment] 2020-02-09 08:05
Thanks for your suggestion which you made some time ago.  For the reasons Nadahar mentioned, it doesn't look as though this will be worked on so I'll close the issue.

**Closed by polygirl** 2020-02-09 08:05 UTC
