### ISSUE TITLE
A to Z limit support broken

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4937] opened 2024-08-29 19:11 UTC
This is a comment from Patreon:
Guys, the server is not detecting my shared drived. This problem began with 14.4.0, and I just simply went back to 14.3.0 and everything worked fine again. Now the same issue is with 14.5.0, and it will not see my shared drives, so the available items is 0. This was one of the issues I reported which resulted in corrections before.
The server somes up, however when it attempts to scan the shared drives, it sees nothing, cleans up the database and then just sits there. I am running Win10 22H2 and 3 of the 4 drives are shared at root level. One drive has a folder that is shared. I hope we can get this thing back to normal. I have again gone back to 14.3.0 and everything is fine. Thanks!
Any ideas what could have broken this @SurfaceS @ik666 ?

**Comment by ik666** [comment] 2024-08-30 06:24
@SubJunk Sorry, I cannot remember do have done anything that effects file scanning and I haven't seen this behaviour yet on my machines running on Mac and Linux ...

**Comment by SurfaceS** [comment] 2024-09-01 09:33
@SubJunk 
Log is needed here.

**Comment by SurfaceS** [comment] 2024-09-02 10:41
Should be fixed in #4947.
Was not a _shared drive support broken_.

**Comment by SubJunk** [comment] 2024-09-04 02:24
The user has reported this fix did not work. I have asked them for logs

**Comment by radioresearch** [comment] 2024-09-04 10:31
[ums_dbg_2024-09-04-06-13.zip](https://github.com/user-attachments/files/16868812/ums_dbg_2024-09-04-06-13.zip)
Please find the requested tracelog attached.
Al Muick / radioresearch

**Comment by radioresearch** [comment] 2024-09-04 15:29
The shared drives are as follows:
D:\
E:\
F:\To Be Watched\
G:\

I cannot reproduce a browse because it insists there is nothing to browse, though the shared drives are listed in the program.

By ATZ settings, I presume you mean the "A to Z" section.  It was set at 100, but I changed it to 0 for the test, without any difference. :-(

**Comment by SurfaceS** [comment] 2024-09-04 16:22
@radioresearch

On logs I do not see anything that ask for a browse.

> I cannot reproduce a browse because it insists there is nothing to browse, though the shared drives are listed in the program.

- Open UMS, wait until it started (when you can reach web settings).

- Open your web browser, and browse this : http://localhost:9001/player
Wait the page is loaded (it can take some delay the first browse if you have a lot of files).

- If it **not show** you drives on the web browser, dump and post logs as you done before (I will have what UMS is doing after the web request).

- If it **show** you drives on the web browser, that mean the problem is with the device, so :
try a browse by your device (the one that will insists there is nothing to browse), then dump and post logs.

**Comment by radioresearch** [comment] 2024-09-05 11:58
[ums_dbg_2024-09-05-07-52.zip](https://github.com/user-attachments/files/16892956/ums_dbg_2024-09-05-07-52.zip)
OK, when I put "A to Z" to the 10000 default, it now sees all the files!  This is a little troublesome for me as I really wanted them to be grouped in alphabetical folders.  I would say that this is no longer a top priority, as I can now use the latest version of UMS.
Thank you for all the help and for your time.!

**Comment by SubJunk** [comment] 2024-09-05 23:18
Thank you for letting us know!

**Comment by SubJunk** [comment] 2024-09-24 08:11
@radioresearch we have a fix to A to Z limit now, would you like me to upload a build for you?

**Closed** 2024-09-24 08:11 UTC

**Comment by radioresearch** [comment] 2024-09-24 08:17
Yes, please!!

Thanks!

**Comment by SubJunk** [comment] 2024-09-24 08:35
@radioresearch uploaded to Patreon
