### ISSUE TITLE
Log Level cannot be changed to Error or Warning

### ISSUE THREAD

**Issue by amalic** [UniversalMediaServer/UniversalMediaServer#317] opened 2014-05-15 12:10 UTC
whenever i change the loglevel to something else than "Error" or "Warning" the change is displayed in the Log -> "Changed debug level to ..." (should be more like "Changing log level to ..."). 

This seems not to be working with Log Level "Error" or "Warning".

**Comment by Sami32** [comment] 2016-07-27 18:17
@amalic @SubJunk I cannot reproduce this issue on Windows.
Can you close this issue ?

**Closed** 2016-08-03 15:29 UTC

**Comment by Nadahar** [comment] 2016-08-03 17:19
The logging has since been pretty much rewritten and this works AFAIK.
