### ISSUE TITLE
Container gets stripped when played from rar-archive. 3.4.0 and up

### ISSUE THREAD

**Issue by SilentFez** [UniversalMediaServer/UniversalMediaServer#273] opened 2014-04-11 19:26 UTC
I'm having some trouble playing mkvs when they are in a rar-archive.
It looks like the container gets stripped for information. The time-code doesn't show up and I can't use the goto function on the PS3.

This is how it shows up in the log:
Starting transcode/remux of test.mkv with media info: container: null, bitrate: 0, size: 9223372034707292159, video codec: null, duration: null, width: 0, height: 0, frame rate: null, thumb size : 10163, muxing mode: null, mime type: video/mpeg

If i extract the mkv it shows up as it should.
Starting transcode/remux of test.mkv with media info: container: mkv, bitrate: 3898993, size: 621779774, video codec: h264, duration: 00:21:15.00, width: 1278, height: 720, frame rate: 23.976, thumb size : 11203, muxing mode: null, mime type: video/x-matroska

The problem seems to occur in all builds after 3.3.0.

In both sets off logs I first tried to play the mkv from the rar and using the goto function.
Then I played the same mkv when it is unrared.

Debug for 3.4.0 where it is not working: http://hille.tv/files/ums/ums3.4.0_dbg.zip
Debug for 3.3.0 where it is working: http://hille.tv/files/ums/ums3.3.0_dbg.zip

**Comment by Sami32** [comment] 2016-07-26 13:51
@hille Sadly your logs are not accessible anymore, so if you have again this problem with the latest UMS version, could you post your new log, please ?
@valib @SubJunk I did reproduce this issue, on Windows with ZIP and 7Z archives containing MKV or MP4 video file.
[ums_dbg_ZIP.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/383878/ums_dbg_ZIP.zip.txt)
ould this issue came from the JNA upgrade to 4.0.0 in UMS 3.4.0 ? or i missed something...
The videos are not played and time is showed as 09:59:59 for a 12s video; i make the zip files with 7Zip.
I didn't tried UMS 3.3.0 version though...

**Comment by valib** [comment] 2016-07-26 21:03
For compressed video files there is missing external subs support for FFmpeg and also for MEncoder. I will check if it is possible to do that.

**Comment by Sami32** [comment] 2016-07-26 23:13
@valib That's fast !  ;-)

**Comment by Sami32** [comment] 2016-07-27 01:47
@valib Too fast ;-) Didn't solved this issue.
[debug.log_ZIP.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/385128/debug.log_ZIP.txt)

**Comment by valib** [comment] 2016-07-27 07:15
@Sami32 the problem you reported is made by FFmpeg see `DEBUG 2016-07-27 02:38:23.593 [ffmpeg.exe-50-2] [mov,mp4,m4a,3gp,3g2,mj2 @ 033d9420] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1920x1080, 4163 kb/s): unspecified pixel format. ` For video I tested it works OK because for my TV is transcoding set to MPEG-PS and pixel format is not used. I will look on it.

**Comment by Sami32** [comment] 2016-07-27 11:56
@valib Perhaps i forgotten to told that this video file is working when not include in an archive file.
[MKV.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/385885/MKV.txt)
I will have done if i could, but as when i go in the #--TRANSCODE--# folder, the archive files folder are not displayed any choice of video engines, and their do not appear in the main #--TRANSCODE--# folder.
![capture_07272016_133430](https://cloud.githubusercontent.com/assets/18471069/17174046/6be425c6-53f6-11e6-8f2f-c916b0e4b9bb.jpg)
![capture_07272016_125019](https://cloud.githubusercontent.com/assets/18471069/17174321/98651fc2-53f8-11e6-8452-54dfd43fb535.jpg)

When i see "**Not muxing the video stream with tsMuxeR via FFmpeg because the video stream is not muxable to this renderer**" in the log i suspect that the file is not correctly recognized before be send to FFmpeg ?
Seeing DLNA.ORG_OP=10, i guess that the video loose it searchable status.

**P.S.** I just discover that i was not able to browse the original video file folder from #--TRANSCODE--# folder.
Cling give me this error report "SEVERE - 12:43:51:078 - AWT-EventQueue-0 : ContentDirectoryService Browser : Error: Current state of service prevents invoking that action. Can't parse DIDL XML response: org.teleal.common.xml.ParserException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3380; Le préfixe "pv" de l'attribut "pv:subtitleFileType" associé à un type d'élément "res" n'est pas lié.."

**Comment by valib** [comment] 2016-07-27 13:37
@Sami32 the error `Le préfixe "pv" de l'attribut "pv:subtitleFileType" associé à un type d'élément "res" n'est pas lié.."` is the Cling problem. Standard renderers whose don't use this feature simply ignore or not report it. For that case is in the DefaultRenderer.conf the option `OfferSubtitlesByProtocolInfo = true`. When this is set to false the error will disapear but also this kind of subtitles support is stopped.

**Comment by Sami32** [comment] 2016-07-27 19:09
@valib Thank you very much for sharing :-D You are right it did the trick.
I didn't tried any of these option because i was afraid loosing subtibles support but i will try on my renderer.
AFAIK, this error was affecting only files having both internal and external subtitles in the #--TRANSCODE--# folder.

**Comment by polygirl** [comment] 2020-02-10 08:06
@SilentFez It looks as though this is now resolved for you so we are closing this issue. Please feel free to reopen if needed.

**Closed by polygirl** 2020-02-10 08:06 UTC
