### ISSUE TITLE
Bug Report:  External Subtitles File Causing Video Videos Not to Play

### ISSUE THREAD

**Issue by autumnriver** [UniversalMediaServer/UniversalMediaServer#810] opened 2016-01-27 01:31 UTC
This post has been edited to update the nature of the problem.

Windows 10 64bit
UMS 5.5.0
Renderer:  LG BD670 Blu-Ray Player

When a subtitle .srt file is included in same folder with a video file (any format) the video file does not play thru UMS when the renderer is an LG BD670. 

When the .srt file is deleted from the folder, the video displays and can be played, but without subtitles.

When the same files in the same folder are streamed using Windows Network File sharing instead of UMS, the LG correctly displays both files and plays the video (with subtitles).  Therefore UMS is at fault, not the LG Blu-Ray player.

A new clean install does not solve the problem
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/106694/ums_dbg.zip)

**Comment by Nadahar** [comment] 2016-01-27 04:00
For us to have any chance to see what goes wrong, please follow [these instructions] (http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556).

**Comment by autumnriver** [comment] 2016-01-27 14:33
The log has been uploaded.

The log does not appear to show anything beyond UMS locating the folder
(directory) - H:Movies.  The problem files are in a subfolder in that
directory.
As explained before, the presence of an srt file in the folder causes UMS
to not display the associated video file. (This seems to happen with any
format video file, though I've only tested it with mp4 and mkv files).  It
does display the srt file, which of course it cannot play alone.

**Comment by Nadahar** [comment] 2016-01-27 14:34
@autumnriver Where is the log uploaded?

**Comment by autumnriver** [comment] 2016-01-27 14:41
I uploaded it as an edit to my original comment.

I don't know your code, but here is my best guess as to the cause:  UMS is
screening out the video file because both files (the srt and the mp4) have
exactly the same name; only the extension is different.  This is the way it
has to be for the subtitles to work.

Note that this problem does not occur with Windows network file sharing.

Thanks for your attention.

**Comment by Nadahar** [comment] 2016-01-27 14:53
@autumnriver That's not the problem, that's the normal way to do it. I see in the log that the .srt file is recognized and analyzed to be UTF-8. Further it is set up to be transcoded with FFmpeg. 

I can't quite see why this file would be hidden, I can see no indications of that in the log. I think @valib need to look at this, as he knows much more than me about subtitle issues.

**Comment by autumnriver** [comment] 2016-01-27 14:54
Further info:

If I rename the video file alone, it now displays OK in the listing.  But
the srt file (with the old name) does not show.  Again, both files have to
have the same name for subtitling to work.  The problem seems to be that
both files cannot display if they have the same name but different
extensions.

Hope this helps.

**Comment by Nadahar** [comment] 2016-01-27 15:05
@autumnriver As said, no, that is not the problem. Subtitle files generally to not show, UMS only shows image, audio or video files. But when the files have the same name but different extension (which is the "standard" way of doing it) UMS recoginize that this subtitle file belongs to that video file. That is not the problem, the problem is somewhere after that, in how UMS choose to present the result to the LG.

I see that UMS wants to transcode this. The fact that it works when you use WMP sharing, indicates that your renderer can handle this subtitle streaming. That indicates that your renderer profile is wrong, and that might be where the whole problem lies. We'll just have to wait and see what @valib has to say.

**Comment by autumnriver** [comment] 2016-01-27 15:19
When both files have the same name, the .srt file alone shows.  I can
select it to play, and then get the message (presumably from the LG) "This
file cannot be played", which of course is correct as it is only an .srt
file.

**Comment by Nadahar** [comment] 2016-01-27 15:20
@autumnriver Even weirder - the .srt file should never show. Have you looked in the TRANSCODE folder if any of the versions there is playable?

**Comment by autumnriver** [comment] 2016-01-27 15:46
It gets a lot more weird:

If it go into the TRANSCODE folder, only the .srt file shows.  (Note this
is when the video file is .mp4)

However, if I change the video file to .avi, the TRANSCODE folder shows
several options in addition to the .srt file.  None of them play, except
one named "no transcribing."  This one will play the movie, but without the
subtitles.  Strange indeed.

All of this seems to point toward the SMS code have a glitch with names.
As you wrote that UMS should show the video file but not display the
associated .srt file, it seems that the code is somehow suppressing the
video file instead of the .srt file when both are present and have the same
name.  I infer this because when I change the name of the video file but
not the .srt file, it then displays as you say it should:  the video file
only.  Of course it can't render the subtitles when this is the case.

Thanks for all your help so far.

**Comment by autumnriver** [comment] 2016-01-27 16:14
One further detail I forgot to mention:

When the .srt file is displaying only, it shows up as follows:  movie name
{External Subtitles}

**Comment by autumnriver** [comment] 2016-01-27 17:57
Nadar,

Further research shows I may have this problem somewhat wrong.

Here is what I've found:

If I go to Navigation/Share Settings and uncheck "hide file extensions",
then when I look at the file in the LG it shows as follows:  movie name.mp4
{External Subtitles}

When I click on this file, the LG says "This file cannot be played."

So it seems I reported this to you backwards.  It is the movie file that is
showing, not the .srt file.  However the LG will not play it with a
subtitle file present. It will play the same file without the .srt file
present, of course without subtitles.

However, since the movie plays fine with subtitles using Windows Network
Sharing, UMS is somehow preventing the file from playing with subtitles on
my LG player.

Not sure this helps.

I am attaching another log file when I tried it again.

James

**Comment by valib** [comment] 2016-01-27 18:19
@autumnriver It seems to me that your player is mixing the UPnP support with DLNA. Do you have still set the Windows network file sharing enabled for the folder? As @Nadahar stated the .srt files should newer show. I also think that you need the new .conf file for your player. The LG-LA6200 is not the proper one. Try to use the LG-BD.conf rename it and set the ```UserAgentSearch = TV.*LG.*\d{2}LB\d{4}
UpnpDetailsSearch = TV.*LG.*\d{2}LB\d{4}``` to ```UserAgentSearch = LGE_DLNA_SDK
UpnpDetailsSearch = LG BDP``` you will see if it works. And do not forget to disable all other LG renders.

**Comment by Nadahar** [comment] 2016-01-27 18:58
@autumnriver This is beginning to make more sense. The problem is, as I said earlier, probably with the renderer configuration file used, and how that specifies that subtitles should be delivered to your renderer. 

I still think @valib will figure this out in no time.

**Comment by autumnriver** [comment] 2016-01-27 20:18
Turning off  file sharing for the folder in Windows makes no difference.

UMS shows my LG BD670 Blu-Ray Player as follows:  LG BDP DMR -- 6844

It identifies it as a UPnP renderer. (see screenshot)

I don't understand what configuration files you are referring to.

Note that UMS works fine for all other video files.  The problem only
appears with an external subtitle.

James

**Comment by autumnriver** [comment] 2016-01-27 20:33
One more thing:  The description of the LG BD670 says that it is "DLNA
Compatible" and will work with "DLNA servers."  No mention is made of UPnP.

**Comment by Nadahar** [comment] 2016-01-27 20:40
UPnP and DLNA is a mess, DLNA is based on the UPnP AV specification, but has it's own rules limiting it. So you could say that any DLNA device is a UPnP device, even if they doesn't support the full UPnP spec. I'm not sure what @valib meant when he said that about mixing the two above though.

**Comment by valib** [comment] 2016-01-27 21:49
@Nadahar during I was writing my previous response the @autumnriver wrote an explanation that it is not a UPnP and DLNA mess but his own setting which hide the file extension so the video file was always there but he was thinking that it is only the subs file. If he is not able to play those transcoded videos means that he needs other renderer setting than was automatically chosen.

**Comment by Nadahar** [comment] 2016-01-27 21:53
@valib Yes, but have you looked at his debug files - do you see what other option he should use. From trying with Windows own DLNA sharing, it seems that the renderer supports streaming of those subtitles. You know better than me how to configure that.

**Comment by vargasjj** [comment] 2016-03-02 03:13
Hi. I am hitting this same bug on Ubuntu 14.04 running UMS 6.1.0 with Java 8 and running Android smartphones. I see the same issue in my LG TV.

If I removed my external subtitles, I get the movie playing without any problems.
If I copy the .srt file with the exact name of the movie, then, I cannot play it.

I sanitized a little bit my debugs.

- Non-Working movie:

`21:49:19 DEBUG Matched media renderer "LG-HTS" based on address /192.168.1.107
21:49:19 DEBUG Starting transcode/remux of MyMovie.mp4 with media info: container: mp4, bitrate: 2221056, size: 2101269109, video tracks: 1, audio tracks: 1, subtitle tracks: 1, video codec: h264 (High) (avc1 / 0x31637661), duration: 02:09:08.20, width: 1920, height: 1024, frame rate: 23.98, mime type: video/mp4, attached fonts: false
	Audio track id: 0, lang: und, audio codec: aac (LC) (mp4a / 0x6134706D), sample frequency:48000, number of channels: 2, bits per sample: 16
	Subtitle track id: 100, type: SUBRIP, lang: es, externalFile: /home/jaime/Vídeos/MyMovie.srt, external file character set: ISO-8859-1
21:49:19 DEBUG Starting mkfifo --mode=777 /tmp/UMS-jaime/ffmpegvideo_815_1456886959345
21:49:19 DEBUG Unix process ID (mkfifo): 9830
21:49:19 DEBUG Starting /opt/UMS/linux/ffmpeg64 -y -loglevel fatal -i /home/jaime/Vídeos/MyMovie.mp4 -filter_complex subtitles=/home/jaime/Vídeos/MyMovie.srt:charenc=ISO-8859-1 -bufsize 5000000 -maxrate 14000000 -g 25 -qmax 7 -qmin 2 -ab 448k -c:a ac3 -c:v mpeg2video -f vob /tmp/UMS-jaime/ffmpegvideo_815_1456886959345
21:49:19 DEBUG Reading pipe: /tmp/UMS-jaime/ffmpegvideo_815_1456886959345
21:49:22 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:22 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:23 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:23 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:24 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:24 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:25 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:25 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:26 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:26 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:49:27 ERROR There is no inputstream to return for MyMovie.mp4 [FFmpeg] {External Subtitles}`

- Here is another movie I tried and it worked OK. I just stopped it manually on my video player.
Working movie:

`21:16:46 DEBUG Matched media renderer "Chromecast" based on address /192.168.1.105
21:16:46 DEBUG Starting transcode/remux of MyOtherMovie.mp4 with media info: container: mp4, bitrate: 2246656, size: 2003315016, video tracks: 1, audio tracks: 1, subtitle tracks: 1, video codec: h264 (High) (avc1 / 0x31637661), duration: 02:01:43.37, width: 1920, height: 1072, frame rate: 23.98, thumb size: 1918, mime type: video/mp4, attached fonts: false
	Audio track id: 0, lang: und, audio codec: aac (LC) (mp4a / 0x6134706D), sample frequency:48000, number of channels: 2, bits per sample: 16
	Subtitle track id: 100, type: SUBRIP, lang: null, externalFile: /home/jaime/Vídeos/MyOtherMovie.srt, external file character set: UTF-8
21:16:46 DEBUG Starting mkfifo --mode=777 /tmp/UMS-jaime/ffmpegvideo_89_1456885006848
21:16:46 DEBUG Unix process ID (mkfifo): 8218
21:16:47 DEBUG Starting /opt/UMS/linux/ffmpeg64 -y -loglevel fatal -i /home/jaime/Vídeos/MyOtherMovie.mp4 -filter_complex subtitles=/home/jaime/Vídeos/In.The.Heart.Of.The.Sea.2015.1080p.BluRay.x264-\[YTS.AG\].srt -bufsize 10000000 -maxrate 9000000 -crf 23 -ab 448k -c:v libx264 -tune zerolatency -preset ultrafast -level 31 -pix_fmt yuv420p -async 1 -fflags +genpts -c:a libmp3lame -ac 2 -b:v 35000k -bufsize 35000k -f matroska /tmp/UMS-jaime/ffmpegvideo_89_1456885006848
21:16:47 DEBUG Reading pipe: /tmp/UMS-jaime/ffmpegvideo_89_1456885006848
21:16:47 DEBUG Attaching thread: ffmpeg64-38
21:16:47 DEBUG Unix process ID (/opt/UMS/linux/ffmpeg64): 8222
21:16:49 DEBUG Matched media renderer "Chromecast" based on address /192.168.1.105
21:16:49 INFO  Started playing MyOtherMovie.mp4 on your Chromecast
21:16:49 DEBUG The full filename of which is: /home/jaime/Vídeos/MyOtherMovie.mp4 and the address of the renderer is: 192.168.1.105
21:17:13 DEBUG Connection error: java.io.IOException: Conexión reinicializada por la máquina remota
21:17:13 DEBUG Premature end, stopping...
21:17:16 DEBUG Stopping Unix process 8222: ffmpeg64-38
21:17:16 DEBUG Stopping Unix process 8218: mkfifo-39`


- Here is another Non-Working movie:

`21:17:46 DEBUG Sending ALIVE...
21:17:51 DEBUG Matched media renderer "Chromecast" based on address /192.168.1.105
21:17:55 DEBUG Matched media renderer "Chromecast" based on address /192.168.1.105
21:17:55 DEBUG Starting transcode/remux of MyNextMovie.mp4 with media info: container: mp4, bitrate: 2223104, size: 1948605225, video tracks: 1, audio tracks: 1, subtitle tracks: 1, video codec: h264 (High) (avc1 / 0x31637661), duration: 01:59:38.05, width: 1920, height: 1024, frame rate: 23.98, thumb size: 19126, mime type: video/mp4, attached fonts: false
	Audio track id: 0, lang: und, audio codec: aac (LC) (mp4a / 0x6134706D), sample frequency:48000, number of channels: 2, bits per sample: 16
	Subtitle track id: 100, type: SUBRIP, lang: es, externalFile: /home/jaime/Vídeos/MyNextMovie.srt, external file character set: ISO-8859-1
21:17:55 DEBUG Starting mkfifo --mode=777 /tmp/UMS-jaime/ffmpegvideo_84_1456885075879
21:17:55 DEBUG Unix process ID (mkfifo): 8281
21:17:56 DEBUG Starting /opt/UMS/linux/ffmpeg64 -y -loglevel fatal -i /home/jaime/Vídeos/MyNextMovie.mp4 -filter_complex subtitles=/home/jaime/Vídeos/MyNextMovie.srt:charenc=ISO-8859-1 -bufsize 10000000 -maxrate 9000000 -crf 23 -ab 448k -c:v libx264 -tune zerolatency -preset ultrafast -level 31 -pix_fmt yuv420p -async 1 -fflags +genpts -c:a libmp3lame -ac 2 -b:v 35000k -bufsize 35000k -f matroska /tmp/UMS-jaime/ffmpegvideo_84_1456885075879
21:17:56 DEBUG Reading pipe: /tmp/UMS-jaime/ffmpegvideo_84_1456885075879
21:17:58 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:17:59 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:17:59 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:00 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:00 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:01 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:01 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:02 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:02 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:03 DEBUG External input stream instance is null... sounds not good, waiting 500ms
21:18:03 ERROR There is no inputstream to return for MyNextMovie {External Subtitles}
21:18:03 ERROR External input stream instance is null... stopping process
21:18:03 DEBUG Stopping Unix process 8285: ffmpeg64-40
21:18:03 DEBUG Stopping Unix process 8281: mkfifo-41`


The is a difference on this movies when talking about subtitles.
The Working movie has some sort of <i></i> and some other <b></b> tagging (like some sort of HTML) code.
This is NOT present none of my other .srt files, only the working movie. I have like 5 movies with their own .srt files and 4 of the 5 has no weird tagging like the working one.

This therefore produces that a `:charenc=ISO-8859-1` strange string is added on the debugs.
It also produces that the server tries to find a file named `MyNextMovie {External Subtitles}` which contains an **SPACE** between the name of the movie and the string `{External Subtitles}`.
It also happen with different other names such as `[FFmpeg] {External Subtitles}` , which are not being added in the Working movie at all. Only on the rest of the movies.

Does anyone can identify a similar outcomes here?

I'd appreciate any guidelines because I don't want to go a Windows environment. I'd rather stay in Ubuntu.
This is NOT happening in my Windows though (yes, I got a UMS on a Windows).

Regards,

- JJ

**Comment by vargasjj** [comment] 2016-03-04 14:59
Hello,
Is there any updates on this concern?
Any ideas?

Thank you.
- JJ

**Comment by autumnriver** [comment] 2016-03-04 16:09
The problem is not the .srt file as such.

The problem is that UMS displays only the .srt file, and not the associated
video file (any format), on my rendering device,an LG Blue Ray Player.

I'm using Windows 10 64-bit.

Using Windows file sharing, both files display correctly on my LG  device.
Hence it is not a Windows problem and surely not a problem with my device,
since it is entirely up to third party software companies to conform to
Windows standards, not the other way round.

Suggestion:  look at your code and see why a renderer might fail to see a
video file associated with an .srt. file.

**Comment by vargasjj** [comment] 2016-03-04 16:43
Hi, @autumnriver
Thanks for the reply.
Would you please rephrase that?
Why a renderer might fail to see a video file associated with an .srt
file... in Ubuntu?

- JJ

2016-03-04 11:10 GMT-05:00 autumnriver <notifications@github.com>:

> The problem is not the .srt file as such.
>
> The problem is that UMS displays only the .srt file, and not the associated
> video file (any format), on my rendering device,an LG Blue Ray Player.
>
> I'm using Windows 10 64-bit.
>
> Using Windows file sharing, both files display correctly on my LG device.
> Hence it is not a Windows problem and surely not a problem with my device,
> since it is entirely up to third party software companies to conform to
> Windows standards, not the other way round.
>
> Suggestion: look at your code and see why a renderer might fail to see a
> video file associated with an .srt. file.
>
>

**Comment by autumnriver** [comment] 2016-03-04 17:09
No, in Windows 10.

The renderer sees one file, which it says it cannot play.  I believe it is
the .srt file, since it usually plays video files.  If the .srt file is
removed, the video plays OK (without subtitles).

It is possible it is seeing the video file, not the .srt file as the exact
file type cannot be discerned on the renderer.  But it amounts to the same
thing:  UMS will not play the video with the renderer when there is an .srt
file present.

Again, this is not a problem in Windows file sharing.

**Comment by Sami32** [comment] 2016-07-27 17:50
@autumnriver Do a clean install of UMS version, go in the Renderer's UniversalMediaServer folder in your Windows and delete all the renderers configuration files.

Put that one inside, **delete the .txt entension** before use it, and start UMS. 
[LG-BD670.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/386739/LG-BD670.conf.txt)

Return feedback, if it's fine just close this issue, if not leave a new full TRACE log.

**Comment by Sami32** [comment] 2016-10-15 14:22
@vargasjj Did you get the same issue with ASS or TXT subtitles ?
Converting your problematic SRT subtitles to UTF-8 do solve your issue ?

**Comment by SubJunk** [comment] 2021-04-08 08:47
Closing this due to inactivity

**Closed by SubJunk** 2021-04-08 08:47 UTC
