### ISSUE TITLE
Add PS4 support

### ISSUE THREAD

**Issue by tangestani** [UniversalMediaServer/UniversalMediaServer#574] opened 2015-06-16 04:16 UTC
Sony has just released a Media Player for the PS4. It's available for download now.

Here are the supported formats:
* Video
  * MKV
    * Visual: H.264/MPEG-4 AVC High Profile Level4.2
    * Audio: MP3, AAC LC, AC-3(Dolby Digital)
  * AVI
    * Visual: MPEG4 ASP, H.264/MPEG-4 AVC High Profile Level4.2
    * Audio: MP3, AAC LC, AC-3(Dolby Digital)
  * MP4
    * Visual: H.264/MPEG-4 AVC High Profile Level4.2
    * Audio: AAC LC, AC-3(Dolby Digital)
  * MPEG-2 TS
    * Visual: H.264/MPEG-4 AVC High Profile Level4.2, MPEG2 Visual
    * Audio: MP2(MPEG2 Audio Layer 2), AAC LC, AC-3(Dolby Digital)
  * AVCHD: (.m2ts, .mts)
* Photo
  * JPEG (based on DCF 2.0/Exif 2.21)
  * BMP
  * PNG
* Music
  * MP3
  * AAC (M4A)

More info: http://manuals.playstation.net/document/en/ps4/videos/mp_format_v.html

**Comment by SubJunk** [comment] 2015-06-16 08:34
@tangestani this is great news! We need a trace log to get the identifying info and then I will make a renderer profile

**Comment by tangestani** [comment] 2015-06-16 10:06
I saved my trace log here: https://gist.github.com/tangestani/2ba8f758efe09861ac87#file-ps4-ums-trace-log

**Comment by SubJunk** [comment] 2015-06-16 20:33
@tangestani thanks, please try this and let me know how it goes, particularly for transcoding: https://raw.githubusercontent.com/UniversalMediaServer/UniversalMediaServer/master/src/main/external-resources/renderers/Sony-PlayStation4.conf

**Comment by tangestani** [comment] 2015-06-17 07:13
@SubJunk I tried your renderer conf and ran into two issues:

First, minor issue, the server doesn't attempt to transcode H.264 videos that exceed level 4.1. (MediaInfo issue maybe?)

Second, more important issue, the player refuses to play any videos that require transcoding.
I tried manually transcoding a video to match how it's being done by server and it plays fine. It seems like the player just doesn't like the way the video is being served.

Here's a log of an attempt to serve a transcoded video: https://gist.githubusercontent.com/tangestani/2ba8f758efe09861ac87/raw/5a84378347fa5c362831b617bae121ee36b15e23/ps4-ums-trace.log

**Comment by SubJunk** [comment] 2015-06-17 20:04
@tangestani can you try disabling the "remux with tsmuxer" setting on the FFmpeg options page and see if that helps transcoding?

**Comment by OP-Klaus** [comment] 2015-06-18 00:29
This is a report from a friend of mine:

Fast forwarded through all files and stopped at various points to make sure. BTW Fast forwarding on the PS4 is lightning fast and a massive upgrade over a PS3.  

Transcoding via FFmpeg/Mencoder/TSMuxer does not work at all across a variety of files both video and audio  eg x264/h264/AAc/AC3 etc

As a result the rest of the testing results were done with no encoding:

DTS audio does not work, in most cases the file will not play but in others the file will play with no audio. The PS4 displays an onscreen prompt that says audio cannot be played while the video is running. 

WEb-DL plays natively as long as it is not DTS audio. Tested AC3 and AAc at 1080p and 720P

X264/h264 video with AC3 audio plays natively. tested 720p and 1080p. 

Most videos with AAC audio played natively, out of 7 tested 2 of them did not play. 

Videos with AAc-HE audio streams played natively.

External Subs did not work, video played fine.

Hardcoded subs worked on the one video I played with them. 

One video I tried with LPCM audio didn't work.

Itunes Library testing:

Partially works, files and playlists show up but files purchased off Itunes do not. You can see them under the transcode folder but selecting them gives you the media can not be played message.

**Comment by SubJunk** [comment] 2015-06-18 00:30
This is a report from a friend of mine:

Fast forwarded through all files and stopped at various points to make sure. BTW Fast forwarding on the PS4 is lightning fast and a massive upgrade over a PS3.

Transcoding via FFmpeg/Mencoder/TSMuxer does not work at all across a variety of files both video and audio eg x264/h264/AAc/AC3 etc

As a result the rest of the testing results were done with no encoding:

DTS audio does not work, in most cases the file will not play but in others the file will play with no audio. The PS4 displays an onscreen prompt that says audio cannot be played while the video is running.

WEb-DL plays natively as long as it is not DTS audio. Tested AC3 and AAc at 1080p and 720P

X264/h264 video with AC3 audio plays natively. tested 720p and 1080p.

Most videos with AAC audio played natively, out of 7 tested 2 of them did not play.

Videos with AAc-HE audio streams played natively.

External Subs did not work, video played fine.

Hardcoded subs worked on the one video I played with them.

One video I tried with LPCM audio didn't work.

Itunes Library testing:

Partially works, files and playlists show up but files purchased off Itunes do not. You can see them under the transcode folder but selecting them gives you the media can not be played message.

**Comment by SubJunk** [comment] 2015-06-18 20:05
Here's the latest version of our PS4 profile, please test it:

https://raw.githubusercontent.com/UniversalMediaServer/UniversalMediaServer/41b7cf17052aaac3a3a0e8f7ec14d2cda422e92b/src/main/external-resources/renderers/Sony-PlayStation4.conf

**Comment by Chazz121** [comment] 2015-06-20 15:35
I tested the new profile. Ps4 says; "cannot play media" on files with DTS audio. DTS does not get trans-coded even when keep DTS is unchecked in trans code settings.

**Comment by SubJunk** [comment] 2015-06-24 10:40
Do either of these builds fix that?

http://www.spirton.com/uploads/UMS/UMS-544112b.exe
http://www.spirton.com/uploads/UMS/UMS-ce9daae.exe

**Comment by Chazz121** [comment] 2015-06-24 16:47
I had no luck with either build.

**Comment by skeptical** [comment] 2015-06-25 13:11
> Transcoding via FFmpeg/Mencoder/TSMuxer does not work at all across a variety of files both video and audio eg x264/h264/AAc/AC3 etc

@SubJunk just a shot in the dark (I don't know what your fixes include already), but have you tried generating fragmented mp4? See links here in [Webrender.ffmp4Cmd()](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/configuration/WebRender.java#L366).

**Comment by SubJunk** [comment] 2015-06-25 20:31
@Chazz121 thanks for testing. Logs are useful too so I can try to come up with more ideas :)

@skeptical I'm interested in creating a transcoding profile for that if we can, since it's possible that other renderers like PlayStation Vita will use it - our current Vita profile can't transcode. It might also help with the PS4 too.

I've looked into it before but never got it working, I think earlier this year I tried to add TranscodeVideo=MP4-H264-AAC but gave up. Is ffmp4Cmd working?

**Comment by SubJunk** [comment] 2015-06-25 20:36
@skeptical we could start building it by restoring ee31373 and adding the fragment parameters

**Comment by skeptical** [comment] 2015-06-25 22:00
@SubJunk I oremember it from trying to get mp4 to work in html5 (turned out fragmented mp4 worked well only for firefox in linux back when we were testing).  I mention it since the PS4 initially had browser support (if I remember right) and the new dlna support may be derived from that, but it's all sheer speculation and probably totally off the wall :-).

**Comment by SubJunk** [comment] 2015-06-26 07:50
@skeptical well right now I think we need all the speculation/ideas we can get, since it is essential to add PS4 support, I say we try it :)

**Comment by SubJunk** [comment] 2015-06-28 05:54
It would still be cool to add the MP4 profile, but I have discovered that Serviio is able to at least transcode DTS to AC-3 while muxing the video, and transcode the video to MPEG-2 in a way that the PS4 accepts.

Working commands, using the video testing suite from http://sourceforge.net/projects/unimediaserver/files/Official%20Releases/Windows/VideoTestingSuite-1.0.7z/download:

ffmpeg -fflags +genpts -threads auto -i MKV-H264-DTS-6ch.mkv -y -threads auto -c:v copy -bsf:v h264_mp4toannexb -c:a ac3 -b:a 384k -ac 2 -map 0:0 -map 0:1 -sn -f mpegts transcoding-temp-11-4-ORIGINAL.stf

ffmpeg -threads auto -i MKV-H265-AACHE-6ch.mkv -y -threads auto -c:v mpeg2video -pix_fmt yuv420p -qscale:v 1 -r 24000/1001 -g 15 -c:a ac3 -b:a 384k -ac 2 -map 0:0 -map 0:1 -sn -f mpegts transcoding-temp-21-4-ORIGINAL.stf

I'm having a friend test some custom builds from the FFmpegRemux branch to try to replicate those results. No luck so far.

**Comment by ExSport** [comment] 2015-06-28 20:29
Somewhere on net I saw -threads auto so I tried it month ago? Result was unknown parameter on Windows. I tried 0 which worked as auto and also later found similar posts that newer versions interpret 0 as "auto" but using auto didn't worked for me:-)

**Comment by SubJunk** [comment] 2015-06-29 00:57
@ExSport it defaults to auto anyway so we can ignore that part

**Comment by ExSport** [comment] 2015-06-29 06:45
Agree:-) Only wanted to say that auto is illegal parameter:-)

**Comment by vampiricwulf** [comment] 2015-06-29 07:33
MKV?! Does this mean it won't have to be transcoded when streamed?

**Comment by SubJunk** [comment] 2015-06-29 07:57
@ExSport cool :) maybe Serviio use an older or customized version of FFmpeg

@vampiricwulf yeah it supports MKV natively so no transcoding, unless there are subtitles :)

**Comment by ExSport** [comment] 2015-06-29 07:59
..unless there are subtitles and PS4 doesn't support them natively (internal or external ones)

**Comment by SubJunk** [comment] 2015-06-29 08:51
@ExSport It doesn't seem that PS4 supports any embedded subtitles, or external ones over DLNA, but it does support external ones via USB

**Comment by ExSport** [comment] 2015-06-29 09:17
Then it is pitty, quite simple DLNA implementation right now...

**Comment by SubJunk** [comment] 2015-06-29 09:46
@ExSport yeah well they only had years to work on it so what can we expect ;)

**Comment by SubJunk** [comment] 2015-07-06 10:23
Update: I have been working on getting a file to transcode the audio but not video, and it is working for a FLV file, but when it is remuxed into MKV and then transcoded in the same way, it doesn't work on PS4.
It seems that we are sending the exact same information both times, so I don't know why.
This thread is where the logs are if anyone wants to give me a hand and see if they have any ideas: http://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=3521&p=17052#p17042

I'm using the FFmpegRemux branch for the test builds in that thread

**Comment by mine260309** [comment] 2015-07-08 06:07
@SubJunk I think PS4 does not recognize the file format by DLNA resource's mimetype or DLNA.ORG_PN, but just by the file extension.
See my finding at https://github.com/mine260309/ps3mediaserver/issues/1#issuecomment-119221045
I guess we have to tweak the URL, append correct extension name for transcoding item to make PS4 work.

**Comment by SubJunk** [comment] 2015-07-08 06:33
@mine260309 thanks for posting this here, we also found the same thing yesterday but using the .flv extension. It's great to see progress and I will commit a change to do this automatically soon.

**Comment by ExSport** [comment] 2015-07-08 06:47
You know on both sides because I sent this idea to both places:-) I spotted this URL behavior months ago as I was troubleshooting transcoded avi not playing and found URL is with avi extension and also that incorrect resolution was sent.

**Comment by mine260309** [comment] 2015-07-08 12:05
Now I can confirm that as long as PMS/UMS is transcoding to TS stream (MPEG2+AC3), and `.ts` is appended in the URL, PS4 is able to play the stream. Check the comment https://github.com/mine260309/ps3mediaserver/issues/1#issuecomment-119550831 and the commit in it.
Maybe I can clone UMS as well... :)

**Comment by Nadahar** [comment] 2015-07-08 14:09
I understand the need for a quick fix to support the PS4, but once the heat is off, wouldn't it be better to always provide a simulated extension when transcoding? With the sad state of the DLNA standard, you can't really blame renderers for not relying solely on the DLNA info. My Onkyo renderer also filters on file extension and refuses to even try to play extensions unsupported by it. Would there ever be a case where always sending a faked extension for transcoded files would pose a problem?

**Comment by mine260309** [comment] 2015-07-08 14:52
Yes, for long term, I think it can be configured as an option in renderer's config file, so if a renderer needs file extension, PMS/UMS append it.

**Comment by Nadahar** [comment] 2015-07-08 14:54
I'm still not sure I understand why it would need to be an option, how could it create problems? We send file extension in the URL too, it's just that it's the extension for the original, not the transcoded format right?

**Comment by ExSport** [comment] 2015-07-08 15:07
I already mentioned it in past that it is best to send correct extension so after transcoding from avi to mpeg that mpeg extension should be sent. Until now it was taken as cosmetic fix so other things had priority but now we can see it can be problem so there is no reason why not to do it globally and patch is quite easy. Few days/months ago some similar fixed were already applied as changing resolution info after transcoding with scale or expand and also"MPEG2_TS_EU SD/HD/JPN/ISO things for transcoded video.
I am sure SubJunk has it already implemented but progress is slow because no UMS developer has PS4 for testing:-)

**Comment by ExSport** [comment] 2015-07-08 15:11
@nadahar
Yes. Nobody lost the time with changing extension in URL as it had no benefit until now with today renderers so same extension as original file was sent.
There is no problem to send correct extension depending on transcoding used or not so I am sure this behavior will be fixed globally and not on renderer level to confuse with another option which should be enabled by default for any renderer.

**Comment by SubJunk** [comment] 2015-07-08 19:10
@Nadahar yes, I think it's a good idea to provide dummy extensions too. It is unlikely to do any harm and may even fix some behavior we have been unable to solve in other renderers.

@mine260309 your commit is pretty similar to my one (https://github.com/UniversalMediaServer/UniversalMediaServer/commit/f7eb82789cdee79ddf63f68e10a98e38464d6a2b) but a problem with both of them is that they are relying on a MIME type that is used for other file extensions; video/mpeg can have .ts but also .ps, .mpeg, .mpg, .vob and some others. It's very relevant because we transcode to the latter formats (MPEG-PS) for most renderers, so the file extension will be wrong for them if we apply this fix to them all (which affects @Nadahar 's comment).

The best fix would be to use different logic that says "if the video is being transcoded, and the transcode format is MPEG-TS, then fake a .ts file extension".

**Comment by SubJunk** [comment] 2015-07-09 10:32
Closing this now since we have PS4 support as of 5.2.0. Feel free to create new issues for enhancements since we still probably can tweak it to be better

**Closed by SubJunk** 2015-07-09 10:32 UTC
