### ISSUE TITLE
The error given by jdbc was: org.h2.jdbc.JdbcSQLException

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1232] opened 2017-03-23 15:19 UTC
> TRACE 2017-03-23 16:11:53.140 [Library Scanner] Parsing results for file "EIA-608&708_caption.mpg": container: mpegts, bitrate: 13816106, size: 167279204, video tracks: 1, audio tracks: 2, subtitle tracks: 3, video codec: mpeg2, duration: 00:01:36.00, width: 1920, height: 1080, frame rate: 29.970, mime type: video/mpeg, matrix coefficients: BT.709
> 	Audio track id: 52, lang: en, audio codec: AC3, sample frequency:48000, number of channels: 6, bits per sample: 16
> 	Audio track id: 53, lang: es, audio codec: AC3, sample frequency:48000, number of channels: 1, bits per sample: 16
> 	Subtitle track id: 49, type: UNKNOWN, lang: und
> 	Subtitle track id: 49, type: UNKNOWN, lang: en
> 	Subtitle track id: 49, type: UNKNOWN, lang: und
> DEBUG 2017-03-23 16:11:53.156 [Library Scanner] A duplicate key error occurred while trying to store the following file's subtitle information in the database: F:\!MEDIA_TEST_FILES\UMS Video Testing Suite (20150121)\TESTS\INTERNAL SUBTITLES\EIA-608&708_caption.mpg
> DEBUG 2017-03-23 16:11:53.156 [Library Scanner] The error given by jdbc was: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_C ON PUBLIC.SUBTRACKS(FILEID, ID) VALUES (249, 49, 27)"; SQL statement:
> INSERT INTO SUBTRACKS VALUES (?, ?, ?, ?, ?) [23505-193]
> DEBUG 2017-03-23 16:11:53.156 [Library Scanner] A duplicate key error occurred while trying to store the following file's subtitle information in the database: F:\!MEDIA_TEST_FILES\UMS Video Testing Suite (20150121)\TESTS\INTERNAL SUBTITLES\EIA-608&708_caption.mpg
> DEBUG 2017-03-23 16:11:53.156 [Library Scanner] The error given by jdbc was: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_C ON PUBLIC.SUBTRACKS(FILEID, ID) VALUES (249, 49, 27)"; SQL statement:
> INSERT INTO SUBTRACKS VALUES (?, ?, ?, ?, ?) [23505-193]

As the file have 170MB i didn't joined it, but if you need i can post a link.
[MediaInfo log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/865199/EIA608.txt)

**Comment by Sami32** [comment] 2017-03-23 18:02
@valib I guess that an issue for you :wink: 
[getSubtitleTracksList()](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/d259bfc070165a2d49e51e4e0e47ee8338519885/src/main/java/net/pms/dlna/DLNAMediaDatabase.java#L606)

**Comment by valib** [comment] 2017-03-24 12:55
@Sami32 The issue is somewhere else. There is a problem with media parsing when all subs tracks have the same `id: 49`. Is this seen also in the MediaInfo?

**Comment by Sami32** [comment] 2017-03-24 13:13
@valib I saw later that it was related to incorrect Id parsing, `getId()` give the same results.
I mean we get this error, because of these not correctly handled cases: (Yes, you'll see it in the MediaInfo log posted above )
> ID                                       : 49-CC1
> ID                                       : 49 (0x31)-CC1

> ID                                       : 49-CC3
> ID                                       : 49 (0x31)-CC3

> ID                                       : 49-1
> ID                                       : 49 (0x31)-1

> ID                                       : 49-3
> ID                                       : 49 (0x31)-3

**Comment by Nadahar** [comment] 2017-06-15 15:25
Did looking into this stop? This seems like something that should be fixed.

**Comment by Sami32** [comment] 2017-06-15 15:52
@nadar Not from my side.
I've already forgotten about that, and it was not a hight priority from my point of view.

**Comment by Nadahar** [comment] 2017-06-15 17:05
It will give subtitle problems for users, and I think database errors are bad in itself.

**Comment by Sami32** [comment] 2017-06-18 16:29
@Nadahar I agree, but i was expecting that @valib or @subjunk will handle it, so i've never planned to do more than report it.

**Comment by Sami32** [comment] 2017-06-18 16:33
@Nadahar I agree, but i was expecting that @valib or @subjunk will handle it, so i've never planned to do more than report it.

**EDIT**: That's said if no one care, i could have a look at it later.

**Comment by SubJunk** [comment] 2020-02-15 06:47
I think this has been fixed with the database and subtitles improvements that came after this. Feel free to reopen if it happens again.

**Closed by SubJunk** 2020-02-15 06:47 UTC
