### ISSUE TITLE
external subtitles won't show if .mkv file has multiple subtitles embedded

### ISSUE THREAD

**Issue by wesyr** [UniversalMediaServer/UniversalMediaServer#225] opened 2014-01-06 16:40 UTC
Hi,

Yesterday I've encounter a problem with mkv which contains multiple subtitle tracks and also an srt file.

The problem is that, Showtime can't load that requested srt file, when i type the link into a browser I get

Failure: 500 Internal Server Error

It has been also reported on showtime tracker:

https://showtimemediacenter.com/issues/1835

I've reproduced it on a second computer with UMS.

Link to forum topic: 
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=1516&p=9055#p9055

On forum I've attached logs from showtime and ums.

**Comment by Sami32** [comment] 2016-07-23 22:30
@subjunk @valib When the link on the forum cannot be access anymore that could mean that this issue can be closed ;-)

**Comment by Nadahar** [comment] 2016-07-23 23:13
@Sami32 I can't access anything at the forum atm, so I'm not sure that's a valid proof that the issue is gone..

**Comment by Sami32** [comment] 2016-07-24 19:34
@Nadahar Thanks for your attention :-) Yes for me too, but yesterday all the issues links was not accessible so i wrongly though they was deleted...my bad 8-/

I did reproduce this issue with the latest UMS version. 
[debug.log_EXTERNALSUBTITLES.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/380449/debug.log_EXTERNALSUBTITLES.txt)
[debug.log_EXTERNAL_SUBTITLES_scan.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/380459/debug.log_EXTERNAL_SUBTITLES_scan.txt)

It's working fine with MKV file and any external subtitle when one subtitle is embedded, but not when 3 subtitles are embedded.
So it's a UMS issue, as far as i saw in my log external subtitles was not recognized at the parsing results time, so maybe it come from _DLNAMediaSutitle.java_

**Comment by Sami32** [comment] 2016-07-25 00:41
@wesyr @SubJunk "(on Showtime)" could be deleted from the title of this issue, since it's not specific to a renderer, as well as ".srt" as it also affect the others kind of external subtitles. Thanks.

**Comment by wesyr** [comment] 2016-07-25 15:31
Changed title to correct one :)

**Comment by Sami32** [comment] 2016-07-25 18:46
@wesyr Thanks :+1:

**Comment by valib** [comment] 2016-07-25 21:05
@wesyr is this issue still valid with the latest UMS version? Since 2014 I made a lot of changes. For me it works well.

**Comment by Sami32** [comment] 2016-07-29 17:28
@wesyr Don't be surprise, it's the "subtitles" guy, so better to answer him if you need this issue solved ;-)

**Comment by wesyr** [comment] 2016-07-31 21:16
@valib, @Sami32 sorry about this delay, i wasn't home for a week and didn't had chance to check this topic :) right now it's night-night time here where i am ;) , so i can check it tommor in the evening and of course will answer you is is still valid :)

**Comment by Sami32** [comment] 2016-08-05 12:07
@wesyr Hoping that you didn't lost yourself in the night ;-)

**Comment by Sami32** [comment] 2016-09-07 18:42
@wesyr Can you give us some feedback, please ?

**Comment by atamariya** [comment] 2019-09-16 08:50
@SubJunk This should be closed as @valib confirmed that this works.

**Closed** 2020-01-01 21:26 UTC
