### ISSUE TITLE
not showing media thumbnail correctly.

### ISSUE THREAD

**Issue by ayush0477** [UniversalMediaServer/UniversalMediaServer#4854] opened 2024-07-27 10:00 UTC
it is basically not showing correct thumbnails, but from another media.

**Comment by SubJunk** [comment] 2024-07-28 01:51
I have seen other reports of this recently too. Do you remember which version it first happened with? Can you test older versions to check?

**Comment by SubJunk** [comment] 2024-07-28 03:52
Duplicate of #4820

**Closed by SubJunk** 2024-07-28 03:52 UTC
