### ISSUE TITLE
Audio files are not stored in the Media Library

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#1780] opened 2019-03-29 23:32 UTC
@SubJunk I don't know when this bug started but for me the Audio subfolders in the Media Library are empty even if I browse folders where audio files exist.

**Comment by SubJunk** [comment] 2019-03-30 01:28
I can reproduce it, working on it now

**Comment by SubJunk** [comment] 2019-03-30 04:37
The code that inserts that metadata into the database is running but failing, that's where I got to but ran out of time. Will do more soon

**Comment by SubJunk** [comment] 2019-03-30 07:15
@valib it's caused by h2database `1.4.197` (and continues in `1.4.198`), so we can fix it by rolling back to `1.4.196`. Not sure if it's because we are using it wrong or it's a bug with h2

**Comment by SubJunk** [comment] 2019-03-30 07:19
Fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/8e9e63ce08316083517ea3f2a15aa7aac4a2b430

**Closed by SubJunk** 2019-03-30 07:19 UTC
