### ISSUE TITLE
[BUG] Files renamed and thumbnails replaced by subtitle flags outside TRANSCODE folder

### ISSUE THREAD

**Issue by 444nonymous** [UniversalMediaServer/UniversalMediaServer#1364] opened 2017-08-16 16:43 UTC
@valib

![29485131-013c64a0-84cd-11e7-9101-537ea69b09fa](https://user-images.githubusercontent.com/20845683/29533114-ab54f2a6-86b0-11e7-8647-d93a2eebd033.jpg)

Problem 1: Default Icons are replaced and erased with subtitle icons. If a language it's specified in the subtitle, the flag icon is shown. If not, a blank icon appears.

I looks very ugly because you have 3 types of thumbnails competing: embedded, subtitle flags and default icons (all 3 shown in picture). Also note that auto generated thumbnails using ffmpeg do not work, only using mplayer. I think it's related.

Problem 2: There is an option for "Do not add engine names to filenames". There should be another for subtitles or a default setting for not changing filenames by adding variables.  if you change something in the subtitle config, it does change the filename. So the client (renderer) identifies it as a different file and does not resume or remember any setting associated with that file.

I'm watching "Movie.mkv". But it don't like the embedded subtitles. I download "Movie.srt" subtitles. But when I play the movie again, it does not resume. The reason is because now the filename is "Movie {External Subtitles].mkv". Sometimes they include the format and language of the subtitle. IE: "Movie{Sub:Subrip/English}.mkv

Also note I'm not doing any transcoding, just streaming from a normal folder. The client / renderer supports external subtitles streaming too. Other option could be showing the info in the thumbnail. https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1368

Thanks.

**Comment by 444nonymous** [comment] 2017-08-17 08:02
The names are not just generic "Movie {External Subtitles}.mkv". Sometimes they include the format and language of the subtitle. So if you change something in the config, it does change the filename.

IE: "Movie{Sub:Subrip/English}.mkv 

I thinks this is pretty similar to the labels created by "adding engine names to filenames" and there should be an option to disable it.

Thanks.

**Comment by 444nonymous** [comment] 2017-08-21 18:58
I'd like to rename the first post to:

[BUG] Files renamed and thumbnails replaced by subtitle flag icons outside TRANSCODE folder.

**Comment by Nadahar** [comment] 2017-08-21 21:30
I can't see where the bug is. The file names aren't renamed, the files are left untouced. There are no "rules" in either UPnP or DLNA that dictates that the name of a media entry has to be the same as the file name. In UMS file names are only showed when a better description can't be found, data from tags, online lookups or custom algorithms are used to try to make media names more meaningful. What you call a bug, is by design.

Regarding the flag icons, I'm not sure as I've already said, and I'm waiting for @valib to confirm if that's by design or not. I'm not so sure its a bug though.

**Comment by 444nonymous** [comment] 2017-08-22 05:33
Files are renamed as presented to the client / redenderer. There is no doubt about that. That's why the client / renderer treats the same file as different constantly. And that constant renaming of the same file depending what subtitles are used creates a lot of problems as explained.

So what you argue is that files are not renamed in the source HDD. OK. It does not really matter, the problem is the same. Also there is a mess of icons fighting to override each other, kaning the inetrface look ugly and confusing. None of that can be a feature, it has to be a bug. This is UMS not Apple.

**Comment by valib** [comment] 2017-08-22 11:52
@444nonymous it seems to me that we do not understand each other. When I checked again the picture you provided it realy seems like a bug. Flags should be used only in the TRANSCODE folder to specify the subtitles language and should not be shown in the normal folder. Can you provide the log to see what happened? We need to know the setting which causes that.

**Comment by Nadahar** [comment] 2017-08-22 12:09
@444nonymous I'm sorry to say, but the files are never renamed. What you're describing is the media title. Here's an example of what UMS sends the renderer (this is audio files):
```xml
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
  <container childCount="11" id="93" parentID="73" restricted="1">
    <dc:title>#--TRANSKODE--#</dc:title>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/93/thumbnail0000%23--TRANSKODE--%23</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/93/thumbnail0000%23--TRANSKODE--%23</upnp:albumArtURI>
    <upnp:class>object.container.storageFolder</upnp:class>
  </container>
  <item id="96" parentID="73" restricted="1">
    <dc:title>Vision of Her</dc:title>
    <upnp:album>The Window - DSD Download</upnp:album>
    <upnp:artist>David Elias</upnp:artist>
    <dc:creator>David Elias</dc:creator>
    <upnp:genre>Independent Acoustic</upnp:genre>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="2986980" duration="00:05:07.00" nrAudioChannels="2" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="88200" size="114664543">http://10.72.64.11:5023/get/96/03+-+David+Elias+-+The+Window+-+Vision+of+Her+%2824-88.2%29.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/96/thumbnail000003+-+David+Elias+-+The+Window+-+Vision+of+Her+%2824-88.2%29.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/96/thumbnail000003+-+David+Elias+-+The+Window+-+Vision+of+Her+%2824-88.2%29.flac</upnp:albumArtURI>
    <dc:date>2015-07-28T01:35:23</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="99" parentID="73" restricted="1">
    <dc:title>In Fields of Green I Met Her</dc:title>
    <upnp:album>Because Words Can't Take You There</upnp:album>
    <upnp:artist>Stuart White</upnp:artist>
    <dc:creator>Stuart White</dc:creator>
    <upnp:genre>Ambient</upnp:genre>
    <upnp:originalTrackNumber>4</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="4338710" duration="00:04:55.00" nrAudioChannels="6" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="96000" size="160270294">http://10.72.64.11:5023/get/99/04_diatonis_bwctyt_in-fields-of-green-i-met-her_6-chan_9624.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/99/thumbnail000004_diatonis_bwctyt_in-fields-of-green-i-met-her_6-chan_9624.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/99/thumbnail000004_diatonis_bwctyt_in-fields-of-green-i-met-her_6-chan_9624.flac</upnp:albumArtURI>
    <dc:date>2011-08-05T08:46:48</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="102" parentID="73" restricted="1">
    <dc:title>Astrognosia: Aquarius – Vannmannen (CD-resolution)</dc:title>
    <upnp:album>Astrognosia &amp; Aesop (CD-resolution)</upnp:album>
    <upnp:artist>Kringkastingsorkesteret;KORK</upnp:artist>
    <dc:creator>Kringkastingsorkesteret;KORK</dc:creator>
    <upnp:genre>Art Music &gt; Classical &gt; Classical</upnp:genre>
    <upnp:originalTrackNumber>15</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="871700" duration="00:01:25.00" nrAudioChannels="2" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="44100" size="9359119">http://10.72.64.11:5023/get/102/2L-111_15_stereo-44k-16b.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/102/thumbnail00002L-111_15_stereo-44k-16b.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/102/thumbnail00002L-111_15_stereo-44k-16b.flac</upnp:albumArtURI>
    <dc:date>2016-08-09T19:49:28</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="105" parentID="73" restricted="1">
    <dc:title>Sonata, Op.27 'Moonlingt' Adagio sostenuto</dc:title>
    <upnp:album>Ludwing Van Beethoven 1770-1827</upnp:album>
    <upnp:artist>Artur Rubinstein</upnp:artist>
    <dc:creator>Artur Rubinstein</dc:creator>
    <upnp:genre>Piano</upnp:genre>
    <upnp:originalTrackNumber>1</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="256000" duration="00:15:36.00" nrAudioChannels="2" protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01" sampleFrequency="44100" size="29988351">http://10.72.64.11:5023/get/105/Beethoven+-+%27Moonlight%27+Sonata+-+Arthur+Rubinstein+%28Piano%29.mp3</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/105/thumbnail0000Beethoven+-+%27Moonlight%27+Sonata+-+Arthur+Rubinstein+%28Piano%29.mp3</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/105/thumbnail0000Beethoven+-+%27Moonlight%27+Sonata+-+Arthur+Rubinstein+%28Piano%29.mp3</upnp:albumArtURI>
    <dc:date>2016-08-12T20:22:59</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="108" parentID="73" restricted="1">
    <dc:title>ChillingMusic.wav</dc:title>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="1437167" duration="00:00:27.00" nrAudioChannels="2" protocolInfo="http-get:*:audio/wav:DLNA.ORG_OP=01" sampleFrequency="44100" size="4923734">http://10.72.64.11:5023/get/108/ChillingMusic.wav</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/108/thumbnail0000ChillingMusic.wav</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/108/thumbnail0000ChillingMusic.wav</upnp:albumArtURI>
    <dc:date>2016-08-09T20:05:37</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="111" parentID="73" restricted="1">
    <dc:title>Rock</dc:title>
    <upnp:album>Dark Edges</upnp:album>
    <upnp:artist>Stuart White</upnp:artist>
    <dc:creator>Stuart White</dc:creator>
    <upnp:genre>Ambient Dark</upnp:genre>
    <upnp:originalTrackNumber>2</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="5934465" duration="00:08:08.00" nrAudioChannels="6" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="96000" size="362061708">http://10.72.64.11:5023/get/111/diatonis_dark-edges_02_rock_9624_6-chan.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/111/thumbnail0000diatonis_dark-edges_02_rock_9624_6-chan.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/111/thumbnail0000diatonis_dark-edges_02_rock_9624_6-chan.flac</upnp:albumArtURI>
    <dc:date>2011-09-02T17:04:40</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="114" parentID="73" restricted="1">
    <dc:title>A Night Full of Stars</dc:title>
    <upnp:album>Invisible Order</upnp:album>
    <upnp:artist>Stuart White</upnp:artist>
    <dc:creator>Stuart White</dc:creator>
    <upnp:genre>Ambient</upnp:genre>
    <upnp:originalTrackNumber>4</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="6012268" duration="00:08:42.00" nrAudioChannels="6" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="96000" size="392300448">http://10.72.64.11:5023/get/114/diatonis_invisible-order_04_a-night-full-of-stars_9624_6-chan.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/114/thumbnail0000diatonis_invisible-order_04_a-night-full-of-stars_9624_6-chan.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/114/thumbnail0000diatonis_invisible-order_04_a-night-full-of-stars_9624_6-chan.flac</upnp:albumArtURI>
    <dc:date>2011-08-11T20:16:20</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="117" parentID="73" restricted="1">
    <dc:title>One to Be</dc:title>
    <upnp:album>Trajectories</upnp:album>
    <upnp:artist>Stuart White</upnp:artist>
    <dc:creator>Stuart White</dc:creator>
    <upnp:genre>Ambient</upnp:genre>
    <upnp:originalTrackNumber>7</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="3348312" duration="00:09:32.00" nrAudioChannels="6" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="44100" size="239542004">http://10.72.64.11:5023/get/117/diatonis_trajectories_07_one-to-be_4424_6-chan.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/117/thumbnail0000diatonis_trajectories_07_one-to-be_4424_6-chan.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/117/thumbnail0000diatonis_trajectories_07_one-to-be_4424_6-chan.flac</upnp:albumArtURI>
    <dc:date>2011-09-17T11:42:08</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="120" parentID="73" restricted="1">
    <dc:title>The Secret Universe</dc:title>
    <upnp:album>Trajectories</upnp:album>
    <upnp:artist>Stuart White</upnp:artist>
    <dc:creator>Stuart White</dc:creator>
    <upnp:genre>Ambient</upnp:genre>
    <upnp:originalTrackNumber>8</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="3003031" duration="00:06:47.00" nrAudioChannels="6" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="44100" size="152984531">http://10.72.64.11:5023/get/120/diatonis_trajectories_08_the-secret-universe_4424_6-chan.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/120/thumbnail0000diatonis_trajectories_08_the-secret-universe_4424_6-chan.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/120/thumbnail0000diatonis_trajectories_08_the-secret-universe_4424_6-chan.flac</upnp:albumArtURI>
    <dc:date>2011-09-17T11:42:24</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="123" parentID="73" restricted="1">
    <dc:title>Hallelujah (Chorus)</dc:title>
    <upnp:album>Messiah</upnp:album>
    <upnp:artist>The Sixteen - Harry Christophers</upnp:artist>
    <dc:creator>The Sixteen - Harry Christophers</dc:creator>
    <upnp:genre>Choral</upnp:genre>
    <upnp:originalTrackNumber>21</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="787842" duration="00:03:55.00" nrAudioChannels="2" protocolInfo="http-get:*:audio/flac:DLNA.ORG_OP=01" sampleFrequency="44100" size="23224191">http://10.72.64.11:5023/get/123/Hallelujah.flac</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/123/thumbnail0000Hallelujah.flac</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/123/thumbnail0000Hallelujah.flac</upnp:albumArtURI>
    <dc:date>2015-06-29T12:58:40</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
  <item id="126" parentID="73" restricted="1">
    <dc:title>Hallelujah (Chorus)</dc:title>
    <upnp:album>Messiah</upnp:album>
    <upnp:artist>The Sixteen - Harry Christophers</upnp:artist>
    <dc:creator>The Sixteen - Harry Christophers</dc:creator>
    <upnp:genre>Choral</upnp:genre>
    <upnp:originalTrackNumber>21</upnp:originalTrackNumber>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" bitrate="320000" duration="00:03:55.00" nrAudioChannels="2" protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01" sampleFrequency="44100" size="9509798">http://10.72.64.11:5023/get/126/Hallelujah.mp3</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://10.72.64.11:5023/get/126/thumbnail0000Hallelujah.mp3</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://10.72.64.11:5023/get/126/thumbnail0000Hallelujah.mp3</upnp:albumArtURI>
    <dc:date>2015-06-29T12:58:02</dc:date>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  </item>
</DIDL-Lite>
```
The filename itself isn't transferred. The field that is supposed to uniquely identify each media entry. It doesn't change as the title is changed, but it *does* change when UMS is restarted. That's a problem that can't be solved without rewriting very code logic in UMS, so even though I think it should be a long term goal to solve, nothing can be done about it short-term.

**Comment by 444nonymous** [comment] 2017-08-22 15:44
@valib 

Log pack file. Rename to zip (extension not allowed here)

[ums_dbg.pdf](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1242554/ums_dbg.pdf)

**Comment by valib** [comment] 2017-08-22 17:56
@444nonymous I tried to reproduce the bug using your `UMS.conf` setting but for me it works well. The only thing I can recommend is to delete the database or try clean install of the UMS and maybe also Java. Seems that there is something wrong because when renderer is asking for thumbnail of the video then it is not generated using FFmpeg.

**Comment by 444nonymous** [comment] 2017-08-22 20:00
I deleted the database. It does not matter. Even if i don't select generate thumbnails the subtitle flags problem persists. Without ffmpqeg thumbnails, normal icons should be shown, not the flags.

Java is latest version and works fine with other apps.

**Comment by Nadahar** [comment] 2017-08-22 20:11
@valib He has disabled thumbnail generation, which is why FFmpeg isn't used. He only wants generic icons, but get the flag instead for videos with subtitles.

**Comment by 444nonymous** [comment] 2017-08-22 22:07
@valib Yes and I've tried many configurations. generate_thumbnails = true or false. Using ffmpeg or mplayer.

The thing is, if you are not generating thumbnails (so you are not using ffmpeg), default icons should be shown. And they are not, they are replaced by flags.

Jdownloader uses a compatible ffmpeg.exe version. I replaced it in UMS and it works. Guess what, the moment I don't select generate thumbnails, flags icons appear again.

To disable flags icons I have to disable subtitles. That's the only way for normal thumbnails (icons with extensions) appear. Also the renaming problem always persists.

**Comment by valib** [comment] 2017-08-22 22:22
@444nonymous I think that the main problem is that you use Java 1.8.0_131 version which is not supported for WIN XP. The Java support for WIN XP was stopped in April 2014 so you must anticipate that everything will not work.

**Comment by 444nonymous** [comment] 2017-08-22 22:39
@valib Not supported means: XP is not supported by MS anymore so install Java 8 at your own risk.

But it works fine. It's 100% compatible. Not supported does not mean incompatible in this case.

If you can't find the subtitles bug it's OK, but it's not a Java or ffmpeg bug.

**Comment by valib** [comment] 2017-08-22 22:49
@444nonymous this is the problem "Install Java 8 at your own risk". You are asking us to make changes we are not able to test when current version tested on supported environment works.

**Comment by 444nonymous** [comment] 2017-08-22 23:28
That's true, but It's pretty obvious it's not a java problem. If I used java 7 you could also say it's an old version (and that really causes problems).

Same with ffmpeg. It does not work for anybody on the whole internet using XP / Vista running any program, but it works for the UMS devs using XP.

What do you want me to say.

**Comment by Nadahar** [comment] 2017-08-23 00:14
@444nonymous @valib Both I and @Sami32 can confirm that UMS works both under Java 7 and Java 8 on Windows XP, but there are compatibility issues with JNA > 4.2.2, which means UMS > 6.6.0. The bundles version of FFmpeg is also incompatible. 

The reason for all this is, in my view, that Microsoft is sabotaging Windows XP to force people to upgrade. A lot of software use MSVC to build for Windows, and MS has made sure that anything compiled with MSVC 2015 or later (from what I can see) causes everything from unstability to incompatibility when run on Windows XP. The reason JNA has stopped working on Windows XP is because they have updated their build tools to MSVC 2015, and I'm pretty sure FFmpeg stopped working when they did that as well.

I've compiled my own version of ```jnidispatch.dll``` (the file that creates problems with JNA) that is compiled using mingw-w64. By using that file instead of the one that comes with JNA, the latest version of JNA works fine on Windows XP. I've made a solution for it here: https://github.com/DigitalMediaServer/DigitalMediaServer/commit/4a3b3beb0c838e557f64b8e917e0ca26f8a0f96c

When it comes to the FFmpeg version, we've discussed it to great length here: https://github.com/DigitalMediaServer/DigitalMediaServer/pull/2#issuecomment-321266339. The idea is that it will be linked to from the UMS forum I remember correctly.

That said, I think you misunderstand the issue @valib. It doesn't matter if you disable FFmpeg or delete it or disable thumbnail generation - the point is that it seems like if you don't generate thumbnails, and there's (external?) subtitles available for a video media, the flag will be shown instead of a generic icon. To reproduce it, simply turn off thumbnail generation.

**Comment by SubJunk** [comment] 2017-08-23 06:47
I've seen this bug before randomly on PS3 years ago, but never since switching to using my TV. Do you have another device you can try just to check @444nonymous ?

**Comment by 444nonymous** [comment] 2017-08-23 08:22
@SubJunk. I only have 2 LG TVs (netcast, pre webOS), and the problem looks the same. 

They are both updated and supported but they use old DLNA 1.5 (not sure if related).

**Comment by SubJunk** [comment] 2017-08-24 06:50
What about an Android or iOS phone? Could you install an app like VLC on your phone to check if you see the same bug on there?

**Comment by 444nonymous** [comment] 2017-08-24 08:55
With VLC Android it shows the default icons (no flags) and names with subtitles are renamed with the tag {External Subtitles}, but no individual info about the subtitle format.

**Comment by valib** [comment] 2017-08-24 12:58
@UniversalMediaServer/developers I can confirm the bug. When I disabled `Thumnail generation` than flags appeared in case the external subs language was recognized. The tag {External Subtitles} is shown when the subs language is not recognized othervise it could show e,g, {Sub:Subrip/Und}. This is by design so the question is which tag would be better to show. We discussed it also [here](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1098)

**Comment by 444nonymous** [comment] 2018-01-20 17:52
I'm gald you are fixing the subtitle system, even if I never used it. But moths later I still see my file listing like in the first picture. I'm NOT using the "TRANSCODE" or "SUBTITLE" folder and yet I can't get a normal clean listing of the files.

Problems:
1. Subtitle icons randomly overriding others
2. Subtitle tags "virtually" renaming files (it makes the TV recognize the files as different every time I change a subtitle and it creates problems like not resuming)
3. The embedded icons randomly overriding others (not related to subtitles but there is a icon fight here, they should be disabled). They even override generated thumbs.

Could you please fix the NORMAL listing of files? It's a very basic thing and I don't think it requires too much coding to disable the subtitle system outside the "SUBTITLE" folder, disable the subtitle tags and icons, and also the embedded ones.

**Comment by Nadahar** [comment] 2018-01-20 22:21
@444nonymous None of these changes are complete yet, so they haven't been merged.

You can configure if you want the extra information about audio and subtitle tracks shown behind the video name, so you should just turn that of.

The last point about the thumbnails isn't random, embedded art is preferred over generated thumbnails. People simply have different ideas about which thumbnails they'd like to see, so somebody is going to complain no matter what.

**Comment by 444nonymous** [comment] 2018-01-21 13:42
@Nadahar ("You can configure if you want the extra information about audio and subtitle tracks shown behind the video name, so you should just turn that of.")

There is no option or setting to do that. There never was. The closer thing is "Do not add engine name to file names" and it only applies to video engines.

I just want a normal clean listing of files working. The most basic thing in a DLNA server.

**Comment by Nadahar** [comment] 2018-01-22 14:33
@444nonymous There is such a setting, but it's not in the GUI (and might not be very well documented). I hadn't checked how easy it was to find, I just remembered to having seen it in the code.

You can disable it by adding this line in ```UMS.conf```:
```powershell
hide_subs_info = true
```

**Comment by 444nonymous** [comment] 2018-06-17 06:02
@Nadahar @valib

What is the UMS.conf parameter to disable flag icons?

I'm using 7.1 and the flags problem is the same as when I opened this issue thread. 
The fix was merged https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1372 but I still have the same problem.

**Comment by SubJunk** [comment] 2018-06-17 07:06
@444nonymous that pull request still hasn't been merged. It continues in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1483
It got held up but will hopefully be finished and merged soon

**Comment by SubJunk** [comment] 2021-06-26 08:16
That branch eventually got merged

**Closed by SubJunk** 2021-06-26 08:16 UTC
