### ISSUE TITLE
Option to disabled embedded video art thumbnails

### ISSUE THREAD

**Issue by 444nonymous** [UniversalMediaServer/UniversalMediaServer#1360] opened 2017-08-14 22:05 UTC
IE: Some mkv video files have an embedded image. It usually is a spam logo from the ripper.

1. If you disable "generate tumbnails", the embedded image it's always shown.
2. If you enable "generate tumbnails" and disable "use mplayer", the embedded image it's always shown.
3. Only if you enable "generate tumbnails" and also enable "use mplayer", the embedded image it's NOT shown.

Fix:
1. Embedded images should never be shown if "generate tumbnails" is false.
2. A generated tumbnail should always have priority over embedded images.
3. There could be an option to complete disable or show embedded images.

**Comment by 444nonymous** [comment] 2017-08-14 22:08
It's thumbnail. I can't edit it

**Comment by Nadahar** [comment] 2017-08-14 22:29
@444nonymous I'm not sure I agree with you, even though it seems like a bug if "use mplayer" (where exactly is this option?) has an impact. Yet another option to control behaviour might be viable though.

> Embedded images should never be shown if "generate tumbnails" is false.

"Generate thumbnails" means literally *generate* thumbnails, that is take a screenshot from some point in the video and use that as a thumbnail. This isn't related to if thumbnails are shown.
> A generated tumbnail should always have priority over embedded images.

I disagree. The generated thumbnails are quite "random" as they are created from some arbitrary point of time in the video. Sometimes they come out all black or all white for example. The idea is that if any other source of thumbnail is available (embedded, external etc.) it will probably be more relevant.

> There could be an option to complete disable or show embedded images.

This could be a solution, given that it is deemed necessary. I don't have much opinion neither for nor against this, so I'd agree with whatever "the majority" think.

**Comment by 444nonymous** [comment] 2017-08-15 04:16
The option is "use mplayer for video thumbnails", right to "generate thumbnails". When MediaInfo detects an embedded image, UMS shows it giving it priority. Deleting mediainfo fixes it, but you loose main features, like giving the player device media time info. So movies play showing from 0:00 to 99:99, instead of 00:00 - 2:00 (if the movie is 2 hours long).

Here is the thing. Even if you own an have a great movie / music colletion, most people don't rip themselves their own media. And it's a common practice for rippers to include their logo as embedded image. In fact I still have to find a movie with a real and related embedded image. The opposite happens in music files, if it has an image it is usually a real cover.

So even if it's true that auto generated thumbnails are not perfect, they are much better than a spam logo so common in video files. And even the generic movie icon showing the file extension is much better than having the save 4-5 spam logos for most movies (witch cannot be disabled right now)

An option to avoid showing embedded images in video files is a clear improvement.

**Comment by 444nonymous** [comment] 2017-08-17 07:56
@Nadahar you edited my post (last paragraph yours).

Update: Even if you set "MediaInfo = false" in renderer.conf, if you have enabled subtitles in UMS it shows no icons or ugly low res flags for the subtitle language.

I think the default icons (showing extension labels in the icon) should always be shown first, only to be replaced by auto generated or manually placed images.
 
So, priority showing icons:
1. Default icons with extensions labels. (if 2 or 3 are not selected)
2. Thumbnails Generated by UMS after reading file (if 3 is not selected)
3. Manually download cover art (if used, it could have an option to be selected)

Option to disable or always disable by default: movie files embedded images and subtitle icons.

**Comment by 444nonymous** [comment] 2017-08-18 10:52
Just tell me how is this possible. Look at this mess. It has (at the same time):
1. Just few normal icons showing extensions (when all icons should look like this when generated thumbnails are disabled).
2. Subtitle icons. Both flag icons and empty spots are created because external subtitles are enabled. These icons have preference over the normal icons (1.)
3. Spam embedded icons because mediainfo is enabled. These icons have preference over the normal and subtitle icons (1. and 2.)

Spam embedded icons (3.) have also preference over generated icons. So to clean this mess I have to disable mediainfo and subtitles, and enable mplayer generated icons. That's the only possible way to have some coherence an all icons looking the same.

**Comment by 444nonymous** [comment] 2017-08-18 12:50
[url=https://ibb.co/c1yaRk][img]https://preview.ibb.co/dJ7DCQ/20170818_123659.jpg[/img][/url]
[url=https://imgbb.com/]svg image hosting[/url]

**Comment by 444nonymous** [comment] 2017-08-18 12:51
https://preview.ibb.co/dJ7DCQ/20170818_123659.jpg

**Comment by 444nonymous** [comment] 2017-08-18 12:53
https://image.ibb.co/mme4K5/20170818_123659.jpg

(Please delete the 2 previous post. I can't edit them)

**Comment by 444nonymous** [comment] 2017-08-18 12:56
https://image.ibb.co/mme4K5/20170818_123659.jpg

**Comment by Nadahar** [comment] 2017-08-18 12:59
@444nonymous As far as I know, everybody can edit their own posts. I've never had a problem editing my own posts when I've posted in "foreign" repositories. Alså, you can add images by simply dragging them into your comment, there's no need to upload them to a image hosting site first. I added the image to your previous post.

**Comment by 444nonymous** [comment] 2017-08-18 13:00
Just tell me how is this possible. Look at this mess. It has (at the same time):

1. Just few normal icons showing extensions (when all icons should look like this when generated thumbnails are disabled).
 2. Subtitle icons. Both flag icons and empty spots are created because external subtitles are enabled. These icons have preference over the normal icons (1.)
3. Spam embedded icons because mediainfo is enabled. These icons have preference over the normal and subtitle icons (1. and 2.)
https://image.ibb.co/mme4K5/20170818_123659.jpg

Spam embedded icons (3.) have also preference over generated icons. So to clean this mess I have to disable mediainfo and subtitles, and enable mplayer generated icons. That's the only possible way to have some coherence an all icons looking the same.

PS: I can't edit the post, just delete them. It's because I'm using firefox ESR and it's no longer supported.

**Comment by 444nonymous** [comment] 2017-08-18 13:02
https://image.ibb.co/mme4K5/20170818_123659.jpg

Just tell me how is this possible. Look at this mess. It has (at the same time):

1. Just few normal icons showing extensions (when all icons should look like this when generated thumbnails are disabled).
2. Subtitle icons. Both flag icons and empty spots are created because external subtitles are enabled. These icons have preference over the normal icons (1.)
3. Spam embedded icons because mediainfo is enabled. These icons have preference over the normal and subtitle icons (1. and 2.)

Spam embedded icons (3.) have also preference over generated icons. So to clean this mess I have to disable mediainfo and subtitles, and enable mplayer generated icons. That's the only possible way to have some coherence an all icons looking the same.

PS: Github does not support Firefox ESR anymore. It's telling me to update since a few days ago and I can't edit posts or upload files, just delete them.

**Comment by Nadahar** [comment] 2017-08-18 13:05
When it comes to the issue itself, I've already explained why it works as it does, except the language flags which I though only showed in the ```TRANSCODE``` folder. I don't know why they are shown outside it, but @valib might know.

Except for that, it's working as designed. I don't know why you've turned off "generate thumbnails", it has nothing to do with now showing embedded thumbnails as I've already stated.

**Comment by 444nonymous** [comment] 2017-08-18 13:14
The subtitle option does not help outside "custom UMS" folders. You can also see the problem it creates because it renames files -> https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1364

I repeat, even if I have "generate thumbnails" ON, these are not shown because embedded thumbnails loaded by mediainfo have preference.
 
There is no normal way of having a decent and coherent set of icons, the same icons for all files. You have to disable mediainfo in renderer.conf for every profile + subtitles in UMS.conf, and then enable "generate thumbnails".

**Comment by 444nonymous** [comment] 2017-08-18 13:26
And by the way. I'm not even doing any transcoding (I have the option set to false in UMS.conf).Just streaming, because the client supports everything except x265.

And I have to enable subtitles in transcoding options for them to be streamed. So i get all the renaming and flag icons problems If I want subtitles. I disable Mediainfo, and I also loose some functionality to avoid the spam thumbnails problem shown instead auto generated ones.

**Comment by Nadahar** [comment] 2017-08-18 13:28
@444nonymous You have a very strange goal as I see it. I've never seen it as a goal to have coherent thumbnails, normally you want the thumbnails to identify the media they represents the best they can, not make your browsing screen "look nice".

Disabling MediaInfo will most likely lead to a lot of other issues, it's not MediaInfo that loads the embedded art, it simply parses the files so that UMS knows that the embedded art is there. UMS then has embedded art as the preference, which makes sense in many cases. This is no bug in itself though, so if you want to discuss changing how UMS works I'd suggest you focus on that instead of trying to make it look like a bug.

As I see it, you have revealed two potential bugs though. One is that using MPlayer to generate thumbnails actually give you no thumbnail, the other is that the "flags" are shown outside the "TRANSCODE" folder. I'm not sure how this is supposed to work though, so I'm not sure if it is a bug or intended behaviour.

**Comment by Nadahar** [comment] 2017-08-18 13:35
@444nonymous You're trying to use the system in a way it's not designed to. You're not supposed to disable transcoding, it's mostly there for use in trouble shooting. Also, by disabling MediaInfo you're basically disabling most of the logic UMS use to make the correct decisions automatically.

If you have a correct renderer configuration, MediaInfo enabled and don't disable transcoding, UMS will only transcode what your renderer doesn't support (x265). It won't transcode when not needed. You can also configure when subtitles should be used based on available audio and subtitle languages. If your renderer doesn't support subtitles without transcoding, media that need subtitles according to your configuration, will be transcoded automatically, and this will be consistent so that the "names" won't keep changing.

**Comment by 444nonymous** [comment] 2017-08-18 13:42
@Nadahar Let's be honest, a DLNA server is about have coherent thumbnails in a good looking interface. I wish DLNA had never been created, just SMB with extended discovery capabilities would do.

Embedded art makes sense when it's good art and not spam (IE: mp3 and music files). Mkv files never have any good embedded art, they either have no pics or spam (99% of the time). Anyway, embedded should always have an option to be overridden by custom art. Because if it's custom it means you took the time to find something better o select an option you consider better. Why give options for art that will never work?

Using MPlayer to generate thumbnails gives me thumbnails as log as there is no embedded pic in the file detected by mediainfo. Because there is no option in UMS that can avoid embedded art showing over any other art option you select. Only disabling Mediainfo so UMS does not get to "see" the embedded art.

**Comment by 444nonymous** [comment] 2017-08-18 13:52
@Nadahar I have read all the documentation and created a custom renderer.conf file for my client. If I have transcoding enabled, it works exactly like you say (only for x265 videos). But I disable transcoding because the server is a notebook, so just in case something would trigger transcoding instead of streaming and start burning my CPU for hours.

I agree that "Mediainfo = false" is a bad idea, but that's the only way I can get rid of the embedded spam icons. You say that's the way UMS works because embedded spam icons are the geatest thing ever and should not be overridden by any other option o matter what. I just disagree, in fact I prefer any other icon (mplayer generated, custom downloaded art,  plain extension icons). I just don't have any other option but disable mediainfo to get rid of them.

**Comment by Nadahar** [comment] 2017-08-18 13:57
@444nonymous 
> Let's be honest, a DLNA server is about have coherent thumbnails in a good looking interface.

No. I've never heard an argument for that before, and the idea has never struck me. There's a lot of bad looking DLNA interfaces, and I've never even considered that important. The point with DLNA is to enable different devices to share media through a standardized set of rules. DLNA is far from perfect in many ways, but I like the idea of having a platform and hardware independent way to exhange media and media information.

It's not true that embedded art will never work. If whoever encoded the file took the time to put an embedded image there, you'd think it would be relevant. I don't know where you get your video files, but your reference to "rippers" and "spam" seems to indicate that they aren't made by you, and that you're probable getting them somewhare shady. It would be very strange to me if we should make UMS work in a specific way that only makes sense for certain illegal content.

As I've said eariler in this issue, I think having the option to disable embedded art might make sense, but I wish that the other @UniversalMediaServer/developers presents their view so that we can come to an agreement before making any changes. I'm quite neutral to this, I can see that it has its use, while I also think making too many options makes it harder for people to get things working.

Your tone doesn't really help your case either, the fact that you scream "BUG, BUG" when in fact its just not working the way you'd like it to work, and saying things like "You say that's the way UMS works because embedded spam icons are the geatest thing ever" makes me just want to ignore you. We have a lot of things to use our free time on, and we have to prioritize. I've never said what you claim, and I don't understand what you think you achieve by claiming that I said something both you and I know I haven't.

UMS is open source and anyone can contribute. If you aren't able or willing to convince others to do the work for you (to get it to work like you want it to), you could always post a pull request yourself.

**Comment by 444nonymous** [comment] 2017-08-18 14:03
@Nadahar About this [quote]If your renderer doesn't support subtitles without transcoding, media that need subtitles according to your configuration, will be transcoded automatically, and this will be consistent so that the "names" won't keep changing.[/quote]

I can asure you, that you need to enable sutitles in transcoding for sutitle streaming to work, option called "automatically load srt / sub sutitles with the same name file".

If you disable that option, you fix the naming / flag thing, but subtitles will never be streamed. I've tried every configuration possible.

**Comment by 444nonymous** [comment] 2017-08-18 14:08
@Nadahar About this "If your renderer doesn't support subtitles without transcoding, media that need subtitles according to your configuration, will be transcoded automatically, and this will be consistent so that the "names" won't keep changing"

I can asure you, that you need to enable subtitles in transcoding for subtitle streaming to work, option called "automatically load srt / sub subtitles with the same name file".

If you disable that option, you fix the naming / flag thing, but subtitles will never be streamed. I've tried every configuration possible. Even "ShowSubMetadata = false" in renderer.conf does not do anything. Subtitle tags in file-names are still shown.

**Comment by Nadahar** [comment] 2017-08-18 14:12
@444nonymous For subtitles to work properly, you have to have MediaInfo enabled. Many renderers doesn't support streaming subtitles as a separate stream (so that you don't have to transcode to burn them in), but AFAIK most Samsung and Panasonic TVs do support that and the renderer configuration must be correctly configured. For other renderers, the only option is to transcode to burn the subtitles in.

It seems to me that you need to read through [this](https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Audio-and-Subtitles) to understand how to properly configure subtitles the way you want it. There's no need to keep turning the option to "load srt/sub" on and off if you've configured it properly.

**Comment by 444nonymous** [comment] 2017-08-18 14:23
@Nadahar 

First of all thank you for your work, UMS works. Then I'm not asking for a pretty interface, just the posibility of having a list of files even with the ugliest icons ever, but all the same and keeping also the original file names.

About getting movies. Rippers are good at what they do. You can have a Blu-Ray collection of movies and it's always faster and better to get the rips from others. There is always been "groups" for that. But they like to spam with embedded images. Easy to fix. You also give support to opensubtiltles and they spam inside the sub files too (that's harder to fix).

What you said after showing my client picture is that UMS is working exactly like it's supposed to. Well, I don't get why it shows so many different and not useful type of icons at the same time and you have to fight with options to get rid of them loosing basic UMS functionality. It would be much better to have a list of files with no icons and I would never have complained that it looks bad. It's better to have simple but working interface than this mess of icons and changing file names that really affects UMS as a server.

**Comment by 444nonymous** [comment] 2017-08-18 14:30
@Nadahar Mediainfo enabled or not, transcoding enabled or not, any options combitation... you always need to have "automatically load srt / sub subtitles with the same name file" enabled if you want subtitles to be streamed.

And my client supports it, so it works fine. But By enabling that option I also get all my files renamed showing subtitle tags and the flag icons. I tried everything I could to fix the renaming / flags thing. It's not possible, you either disable external subtitles to get rid of the problem or enable them and suffer it.

**Comment by 444nonymous** [comment] 2017-08-18 15:55
I've made more testing about subtitles. Here is the bug. 

The reason why I need "automatically load srt / sub subtitles with the same name file" for streaming (media info enabled and transcoding enabled) is because embedded subtitles have priority over external.

So subtitle streaming works fine  with "automatically load srt / sub subtitles with the same name file" disabled, unless the file has embedded subtitles. In that case you have to enable that option. You don't even have to enable "force_external_subtitles" for it to work. It seems UMS does not stream external subtitles if there are others embedded. 

And again, this is always streaming, never transcoding anything.

**Comment by Nadahar** [comment] 2017-08-18 16:01
I'm not the right person when it comes to the subtitles selection logic, but again it's not a *bug*. Lots of such small decisions has to be made because you can't make everything configurable as nobody would be able to configure it correctly. I do think I remember that the preference for internal subtitles has been discussed before, and I guess it would be reasonable to assume that if there are both internal and external subtitles available for the preferred language, the external subtitles should be preferred. But, if you haven't configured your language perferences correctly, you can't expect UMS to select the correct subtitle. When you say there's both internal and external subtitles, are those in the same language?

**Comment by 444nonymous** [comment] 2017-08-18 16:15
Chinese movie with embedded Chinese subtitles. So I load external srt in english. 

Streaming external subtitles always works, even with the option "disable subtitles" checked. Except if there are embedded subtitles. In that case you have to enable that transcoding option for streaming to work.

About configuring languages. It does no matter, i can use *,* that should load everthing. I also have tried und.

**Comment by 444nonymous** [comment] 2017-08-18 16:16
Chinese movie with embedded Chinese subtitles. So I load external srt in english.

Streaming external subtitles always works, even with the option "disable subtitles" checked. Except if there are embedded subtitles. In that case you have to enable that transcoding option for streaming to work.

About configuring languages. It does no matter, i can use (asterisk),(asterisk) that should load everthing. I also have tried und.

**Comment by Nadahar** [comment] 2017-08-18 16:29
The point is that you don't *want* it to load everything. If you want it to prefer English subtitles over Chinese, you should configure it to do so. As far as I know, the problem with choosing the correct subtitle if both external and internal subtitles exist only applies if they are both the same language. If you've told UMS that you prefer English subtitles over Chinese, it shouldn't have any problem picking the external subtitles in English, AFAIK. But, as I said, @valib really needs to step in here, as he's the one that knows that logic fully.

**Comment by 444nonymous** [comment] 2017-08-18 16:36
Look, for some reason if the file is embedded (image, subs, etc), UMS gives it absolute priority over other sources. To the point it's really hard to override it, you have to do a lot if trial and error to trick UMS.

It should always be the opposite. If you bothered to get an external source for art, subtitles, etc, it is because the embedded is not good for you and you prefer that. You should not fight with UMS to get it to work.

And it makes sense. You don't like you external sub? Delete it or get another one. Don't you like your embedded subtitle media? Good luck with that, you can't get rid of it and UMS will always load it over anything else you choose.

**Comment by Nadahar** [comment] 2017-08-18 16:56
@444nonymous 
> What you said after showing my client picture is that UMS is working exactly like it's supposed to.

I never said that, I've even pointed out a couple of things that looks like bugs to me but that I don't know enough about to assert wheter is a bug or "by design". I didn't pay much attention to your screenshot, as we've already estabilished that you have changed the configuration to try to "work around" the fact that the logic isn't like you want it to. It'd be much more interesting to see it with MediaInfo and generate thumbnails turned on, and a properly configured renderer configuration file.

There's one thing you seem to forget about how this is all working as well. Everything that is embedded in the file, is streamed as part of the file itself, and is as such available to your renderer regardless of what UMS does. Renderers often let you choose embedded subtitles in their own interface, which is completely out of UMS' control. I'm not saying that's what's happening here. It doesn't look like it since overriding configuration options lets you get the subtitle you want without transcoding, but you have to take that into consideration as well. Everything that's embedded in the file is available to the renderer as soon as UMS makes the file itself available.

Don't forget that a lot of renderers doesn't support external renderers. It's not a part of the DLNA spec, and the only reason it's working with Samsung and Panasonic is because they've implemented their own "hacks" that UMS use. If we were to prefer external subtitles, that would in many cases lead to no subtitles at all. You seem to only see your case, while we have to try to compromise so that it works as well as possible for everybody.

That said, I've long thought that the subtitle configuration should be rewritten so that the user had a list of "all possible sources" where they could move the sources up and down or even disable some. It could handle both internal, external, "live" (opensubtitles) subtitles and preferences for different subtitle formats if several were available. But, I'm not the one making the subtitle configuration, so all I can do is to suggest.

I've also brought up a long time ago that we should have a priority based system for thumbnails, much in the same way. The way it is now the selection of thumbnails is an intricate hardcoded logic that will work fine for some but not for others. It's simply impossible to come up with one set of rules that makes everyone happy, which is why I think that letting the user configure a priority (and disable sources they don't want) would be the best option. However, I never got any response on that point either, and there's lots of other bugs and problems that really need attention, which means that such ideas quickly just end up as a "future todo" somewhere far back in my head.

**Comment by SubJunk** [comment] 2017-08-19 05:59
I haven't read much of the conversation but I get annoyed at those cover thumbnails showing up too so I would like an option to disable them. Maybe I'll work on that when 7.0.0 final is released :)

**Comment by 444nonymous** [comment] 2017-08-19 06:22
@SubJunk It's not just the cover thumbnails, the subtitle thumbnails too.

https://image.ibb.co/mme4K5/20170818_123659.jpg

**Comment by SubJunk** [comment] 2020-06-19 00:04
Closing this in favour of the implementation issue at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1073

**Closed by SubJunk** 2020-06-19 00:04 UTC
Labels: enhancement
