### ISSUE TITLE
WEB.conf file not found on Mac OS X 64-bit

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1033] opened 2016-10-08 13:53 UTC
Why the Mac users get this warning ? I saw that in their log from somes users.

> DEBUG 2016-09-11 19:00:19.989 [main] Reading web_conf: "/Users/user/Library/Application Support/UMS/WEB.conf" (previous: null, default: "/Users/user/Library/Application Support/UMS/WEB.conf")
> INFO  2016-09-11 19:00:19.989 [main] Web configuration file: /Users/user/Library/Application Support/UMS/WEB.conf
> **WARN  2016-09-11 19:00:19.989 [main] Web configuration file not found: File "/Users/user/Library/Application Support/UMS/WEB.conf" not found**

Because i though that it's was already included in the install package:
https://github.com/Sami32/UniversalMediaServer/blob/ac0f180a3c3cf9ae441d7f203ba7f0c5b46b534e/src/main/assembly/assembly-osx.xml#L84
https://github.com/Sami32/UniversalMediaServer/blob/ac0f180a3c3cf9ae441d7f203ba7f0c5b46b534e/src/main/assembly/assembly-osx_java7_8.xml#L74

**Comment by Nadahar** [comment] 2016-10-08 20:44
I have no knowledge of the Mac install process, I think @SubJunk is the one with the best knowledge about this here..?

**Comment by Sami32** [comment] 2016-10-24 15:41
@Optimusprimeums  Did you get this issue as well ?

**Comment by SubJunk** [comment] 2019-10-18 07:46
Closing this as it seems to no longer be happening (at least I couldn't reproduce it on my Mac)

**Closed by SubJunk** 2019-10-18 07:46 UTC
Labels: question
