### ISSUE TITLE
Request: don't force the usage of discret GPU on Mac with dual GPUs

### ISSUE THREAD

**Issue by onon765trb** [UniversalMediaServer/UniversalMediaServer#1183] opened 2017-02-10 04:34 UTC
UMS forces the usage of discret GPU on Mac with dual GPUs without [gfxCardStatus](https://github.com/steveschow/gfxCardStatus/releases) , which is is a fork of [gfxCardStatus by cody krieger](https://gfx.io)
Can see such a switching, using [gfxCardStatus](https://github.com/steveschow/gfxCardStatus/releases) or console logs.

I request UMS keeps integrated GPU to save power.

To avoid such a switching, [i. graphics switching modes. of switching](https://gfx.io/switching.html) and [Apple's document: Allowing OpenGL applications to utilize the integrated GPU](https://developer.apple.com/library/content/qa/qa1734/_index.html) are usefull.

console logs
default	10:45:23.184140 +0900	kernel	[JavaAppLauncher pid:822 mux-aware] starting, non-mux-aware app count 0, EG 3D: idle HDA: idle
default	10:45:23.184182 +0900	kernel	[JavaAppLauncher pid 822 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:00.000
default	10:45:23.282936 +0900	kernel	[JavaAppLauncher pid:822 non-mux-aware] starting, non-mux-aware app count 1, EG 3D: idle HDA: idle
**default	10:45:23.282964 +0900	kernel	 PEG (usr IGD extdisp 0 capture 0 non-mux-aware app 1 ac 0)
default	10:45:23.282979 +0900	kernel	-------> Switching from IGD to PEG
default	10:45:23.282999 +0900	kernel	:::::::> PEG start powerup [0m 27.342s downtime]
default	10:45:23.355450 +0900	kernel	\*\*\*\*\*\*\*> PEG powerup took: 0.73s**
default	10:45:23.359011 +0900	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	10:45:23.427456 +0900	kernel	kPEEnableScreen 1
default	10:45:23.495627 +0900	loginwindow	    token = 1000217
default	10:45:23.495763 +0900	loginwindow	    token = 1000218
default	10:45:23.497705 +0900	sharingd	Display added (id 69677954)
default	10:45:23.504938 +0900	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
**default	10:45:23.510133 +0900	kernel	=======> Switch completed, PEG active**
default	10:45:23.522834 +0900	sharingd	Clamshell change detected (arg: 0)
default	10:45:24.245358 +0900	socketfilterfw	MacOS error: -67030
default	10:45:24.249211 +0900	JavaAppLauncher	subsystem: com.apple.network, category: , enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0

**Comment by Nadahar** [comment] 2017-02-10 04:57
@onon765trb UMS doesn't control that, the transcoder (FFmpeg, MEncoder) does if you're talking about GPU acceleration. If you're talking about the GUI, it's the JVM that controls it - and it depends on which JVM you've installed and how you've configured it.

In general, Java doesn't allow much low-level control like this, and UMS isn't an OS X only application. If you want something that can utilize your hardware to the maximum, you should stick to native software that has that type of control.

**Comment by Sami32** [comment] 2017-02-10 15:01
@onon765trb Please, do not misundertand me, but we don't have Mac hardware, we are not Mac followers, and we have few resources so that's make me feel that you're seing "Universal" with too much Apple ;-)

Honestly, we try to keep it working for all plateform as best as we can, but asking us to optimize it for Mac, it's a little, how to say..."Hard to swallow".

To be brief, i'll say: No plan, no skill, no will. That's said it's only my personal opinion/feeling, so perhaps a developper will go your way.

I guess that your intention was only to report the best you can with the hardware you get ?

**Comment by onon765trb** [comment] 2017-02-19 05:24
Thank you for your reading and comments.

It is very easy to solve this!!! The setting of App on Mac is saved in foo.plist.
Only adding` <key>NSSupportsAutomaticGraphicsSwitching</key><true/> ` to /`Applications/Universal Media Server.app/Contents/Info.plist`.
This way is publicly opened by Apple, as the above link.

My UMS well works with this.

**Comment by Sami32** [comment] 2017-02-19 14:03
@onon765trb Thank you for take time to report and work on that :+1: 

You're welcome to send PRs anytime :wink:

**Comment by onon765trb** [comment] 2017-06-14 07:50
Regrettably, `<key>NSSupportsAutomaticGraphicsSwitching</key><true/>` isn't written in `/Applications/Universal Media Server.app/Contents/Info.plist` in 6.7.0 and 6.7.1.
In other words, they force the usage of dGPU.

**Comment by Sami32** [comment] 2017-06-14 11:22
Afaik, it is:
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/osx/Info.plist-template.xml#L39

Perhaps the @Nadahar Mac mofifications that will appear in the next version will solve that.
When it's related to MAC OS, i think he is the only one that will handle it.

**Comment by Nadahar** [comment] 2017-06-14 12:17
@onon765trb @Sami32 If it's simply about adding a key to ```Info.plist``` it's very easy to solve. I need some more information though, so that I know what I change. 

Can you give me a proper description of what this setting does and why it is needed?

**Comment by Nadahar** [comment] 2017-06-14 14:56
@Sami32 That template file isn't what's being used, these things are set in POM.xml.

**Comment by onon765trb** [comment] 2017-06-16 09:37
I have attached my Info.plist. This well works.
You also can see [ Apple's document: Allowing OpenGL applications to utilize the integrated GPU](https://developer.apple.com/library/content/qa/qa1734/_index.html).

Without this key, UMS forces the usage of discret GPU on Mac with dual GPUs.

The usage of discret GPU on Mac with dual GPUs often result in braking Mac.
Recall or repair session is often  on Mac with dual GPUs.
It is difficult to find the advantages of the usage of discret GPU, other than using adobe products, Final Cut Pro, etc.
Even mpv, vlc, and ffmpeg don't use discret GPU.

[Info.plist.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1080308/Info.plist.zip)

**Comment by Sami32** [comment] 2017-06-16 13:10
@Nadahar Setting it `false` should have been better :flushed: 

Note: https://bugs.openjdk.java.net/browse/JDK-8041900

**Comment by Nadahar** [comment] 2017-06-16 13:23
@onon765trb I agree that it looks reasonable, I'm just not sure if there are any downsides.

@Sami32 I don't quite understand - why would it be better to set it to false?

**Comment by Sami32** [comment] 2017-06-16 13:40
@Nadahar Doesn't set it to `True`, force it ? It's how i understand it, but i cannot test it.
You are the one that will care about Mac now ;)

**Comment by Nadahar** [comment] 2017-06-16 13:43
@Sami32 No. Setting it to true lets the OS "choose", setting it to false (the default) will force use of the "discreet" - the more powerful, power-consuming, bad quality GPU.

**Comment by Nadahar** [comment] 2017-06-16 14:24
It turns out that #1305 will fix this as well, as the "upgraded" appbundler has ```NSSupportsAutomaticGraphicsSwitching``` set to ```true``` [by default](https://github.com/Nadahar/appbundler/blob/646f5c6427c20c5d40eae36b48fd2d351547dc21/appbundler/src/com/oracle/appbundler/AppBundlerTask.java#L88).

**Comment by Nadahar** [comment] 2017-06-16 14:39
@onon765trb It would be nice if you could test if this version works as intended: http://superbum.org/downloads/UMS-FixReboot.dmg

#1305 is actually made for something else, but it happens to fix this as well. While you're at it, it would be nice if you could confirm that "Create Trace logs" (On the "Logs" tab) works properly in that it restarts UMS in "trace" logging mode. In addition, if you see any problems with this version that isn't there in the current version of UMS, I'd like to know.

As my upload is slow, the file isn't ready for download in another 15 minutes.

**Comment by onon765trb** [comment] 2017-06-17 10:57
I tested. Fine!!! GJ.

**Comment by Nadahar** [comment] 2017-06-19 13:05
Fixed in #1305

**Closed by Nadahar** 2017-06-19 13:05 UTC
