### ISSUE TITLE
100% CPU usage while doing nothing. LG TV cpu usage bug resurface?

### ISSUE THREAD

**Issue by orangpelupa** [UniversalMediaServer/UniversalMediaServer#1111] opened 2016-12-17 15:35 UTC
my issue sounds really similar with this old issue https://github.com/UniversalMediaServer/UniversalMediaServer/issues/316

basically after around 4 hours idle, or sometimes after around 1 hour of playing video without transcoding, UMS will eat 100% CPU. Even after i turned off my LG TV, it stays at 100%.

the last half of the log is attached

[ums.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/658901/ums.txt)

thankyoiu

Specs;
windows 10 64 bit
UMS 6.5.2 
LG UH610T

**Comment by Nadahar** [comment] 2016-12-17 18:38
@orangpelupa There's a lot of different errors in your partial log, unfortunately it's not enough to figure out what's going on. You need to post full debug files [as described here](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556). 

What I can see from your log is that you have a lot of exceptions that "crash threads" and my guess is that their resources arent properly deallocated because ot that. As a result, you run out of memory at the end of the log. Once out of memory things WILL go wrong. You can increase Java heap space to make it take longer to run out, but the real resolution would be to track down the causes of all those exceptions - which is why proper debug files are needed.

**Comment by orangpelupa** [comment] 2016-12-19 23:33
UMS wont eat 100% CPU when i started trace mode :(

have been trying to get it to 100% CPU, cant. weird.

**Comment by valib** [comment] 2016-12-19 23:47
@orangpelupa it seems like wrong UMS or Java instalation. What is your OS?

**Comment by orangpelupa** [comment] 2016-12-20 06:05
@valib im able to reproduce it while running trace mode :D  
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/662912/ums_dbg.zip)

**Comment by Nadahar** [comment] 2016-12-20 07:45
@orangpelupa I can see none of those "interesting" errors in your trace log that your previous log had. There is one error there caused by a bug in UMS, but it shouldn't cause a lot of CPU usage as far as I can tell.

I think you need to let it "record" in trace mode until you get a similar situation as the previous log.

**Comment by orangpelupa** [comment] 2016-12-20 08:42
@Nadahar its a similar situation. it was idle, and it hogs the CPU 100%. Hmm, i'll try running it without trace again and see whether the normal logs will have the previous errors. and then with trace again.

**Comment by orangpelupa** [comment] 2016-12-24 02:29
after a few days it finally 100% cpu again but it was not in trace mode. now running in trace mode.

**Comment by Nadahar** [comment] 2016-12-24 15:01
@orangpelupa Bugs can be much harder to experience when you want them to occur than when you don't.. I'd just keep running trace mode until it's "captured red handed". An easy way to run trace mode without having to select it and restart etc, is to modify the UMS shortcut (or copy it and modify the copy) so that the word ```trace``` is added after ```ums.exe```.

Example: Change
```
"C:\Program Files (x86)\Universal Media Server\UMS.exe"
```
into
```
"C:\Program Files (x86)\Universal Media Server\UMS.exe" trace
```

**Comment by orangpelupa** [comment] 2017-02-01 11:33
finally it eats CPU again :D 

altho this time it was on a fresh W10. 
https://drive.google.com/file/d/0B5r9wJYwSwdhNHRUUTFqd2RhLVE/view?usp=sharing

**Comment by Sami32** [comment] 2017-02-01 21:52
And me it's your log that eat my memory and CPU to 100% ;)
Notepad++ just give up...too huge for me and my old computer.

**Comment by Sami32** [comment] 2017-02-02 23:27
@orangpelupa You're running more than one instance of UMS, right ?

**Comment by orangpelupa** [comment] 2017-02-05 02:35
@sami32 nope, just one. The checkmark to only run one instance also checked. 

Sorry the log is so big. Like 1GB big. It was days or weeks before it starts hogging the cpu.

**Comment by Sami32** [comment] 2017-02-05 11:08
@orangpelupa So that's strange, because your _debug.log_ contain only this:
> DEBUG 2017-02-01 16:15:19.005 [main] Base path set to file:///C:/ProgramData/UMS/UMS.conf
> DEBUG 2017-02-01 16:15:19.036 [main] FileName set to UMS.conf
> DEBUG 2017-02-01 16:15:19.036 [main] Base path set to C:\ProgramData\UMS
> DEBUG 2017-02-01 16:15:19.067 [main] Reading log_level: "OFF" (default: "DEBUG")

And for me, it's happen only when i'm building with UMSbuilder or if an other instance is running at the same time.
So i'm not sure what really happen in your case..., but perhaps the next time this issue happen, you should check if an other _javaw.exe_ process didn't appear in your TaskBar as well.

**Comment by Nadahar** [comment] 2017-02-05 16:27
@orangpelupa I see three of these towards the end:
```logtalk
DEBUG 2017-02-01 16:11:05.426 [New I/O worker #3] net.pms.network.RequestHandlerV2 Caught exception: Java heap space
```
That means that you're out of memory. My guess is that there is some memory/resource leak that very slowly builds up over time and lead to this. 

Those can be very hard to find when they are very slow (leaking just a little). I don't know where to start looking tbh.

**Comment by Nadahar** [comment] 2017-02-05 16:41
There are some interesting exceptions here that probably is unrelated to this though.

 @SubJunk This one's for you I think:
```logtalk
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at net.pms.util.FileUtil.getFileNamePrettified(FileUtil.java:645)
	at net.pms.dlna.DLNAResource.getDisplayName(DLNAResource.java:1568)
	at net.pms.dlna.DLNAResource.getDisplayName(DLNAResource.java:1528)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:665)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:532)
	at net.pms.dlna.MediaMonitor.scanDir(MediaMonitor.java:105)
	at net.pms.dlna.MonitorEntry.discoverChildren(MonitorEntry.java:18)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1396)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1257)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1177)
	at net.pms.network.RequestV2.answer(RequestV2.java:685)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:300)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:256)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by orangpelupa** [comment] 2017-02-06 10:47
I don't think I blocked it off Internet. It even able to detect new updates and download and install it. 

I'll keep running it in trace mode to see if it can hog the cpu again in shorter time frame.

**Comment by Nadahar** [comment] 2017-02-06 11:42
@orangpelupa I you didn't block the internet there was something else strange there. A lot of lookups failed with "unknown host" for normal web addresses, which generally indicates that there's no access to a DNS server. I assumed that meant no internet access.

**Comment by ChadMarshall** [comment] 2017-07-14 12:21
Hit ctrl-alt-delete in the first place and see what is taking cpu usage. You may need to uninstall some programs that aren't working properly. Also I suggest virus boot time scan.

**Comment by SubJunk** [comment] 2019-09-09 09:29
This bug was caused by LG TVs visiting every folder on the server until it ran out of memory, and it has been fixed now with some smart memory management

**Closed by SubJunk** 2019-09-09 09:29 UTC
