### ISSUE TITLE
Thumbs regeneration by every refresh until restart

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#530] opened 2015-04-19 12:17 UTC
Clean v5.1.2 installed. Opening folder with one test file invokes thumb generation via FFmpeg. Every refresh of this file invokes never ending thumb generation instead loading it from cache. After UMS restart thumb is not regenerated again and cached one used.
Refresh=when file is stopped so file in folder is shown again. Also browsing outside and back again so with more files this behavior is overkill.
Correct behavior should be thumb generation only once and never again (until thumb position is changed etc.)

**Comment by ExSport** [comment] 2015-05-04 15:19
Now I know why browsing folder from HD camera with hundreds of TS files is so slow.
First time it completely disconnects my Panasonic TV but in the background it is still indexed so when I browse folder again after some minutes it starts listing files without disconnection but still slowly if I remember well. Hope it is due to this behavior so if it will be fixed it will be major improvement for my parents to browse similar folders with lot of files :+1: 
@SubJunk You tagged is as a bug so it seems you reproduced it, great!

**Comment by SubJunk** [comment] 2015-05-04 19:41
@ExSport I didn't reproduce it but may have seen it before, it does deserve to be looked into more

**Comment by ExSport** [comment] 2015-12-19 16:39
Hi all
Had someone time to look into it and reproduce it? I can reprocude it easily.
Clean DB - restart - browse some huge folder with e.g. .TS files. Go outside and back inside folder again. Any action which re-lists file in folder logs ffmpeg thumbs regeneration again and again...until restarting UMS.
Browsing other new folder makes same behavior so it slows down UMS listing rapidly.
Fixing it should be quite useful :+1: 
Thx!

**Comment by atamariya** [comment] 2016-08-20 13:52
I prefer commenting out the checkthumbnail() completely. The only drawback is resume files don't show proper thumbnail i.e. paused position.

`//						if (mediaRenderer.isUseMediaInfo()) {
//							dlna.checkThumbnail();
//						}
						inputStream = dlna.getThumbnailInputStream();
`

#987

**Comment by Sami32** [comment] 2016-10-29 13:16
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1068

**Comment by Nadahar** [comment] 2016-10-30 19:59
I don't think the rollbacks found in #1068 actually constitute a problem, just some strange logging practice on H2's behalf.

**Comment by klebom** [comment] 2017-05-19 19:31
This issue is still present in 7.0.0-b2. At least if I understand the reporter correctly.

Thumbnails for media files newly added to "Shared folders" are not stored in Media library until UMS is restarted and scans all of the shared folders directory tree. That means thumbnails can be generated again and again, once for every time you browse a folder with new media from a media player, until the point when the server is restarted.

Or to phrase it another way. Newly generated thumbnails missing in in the media library aren't added to it, unless doing the initial scan at server startup.

**Comment by Nadahar** [comment] 2017-05-19 19:33
@klebom We haven't had a release for a while now, but this *should* be fixed in the latest code. If you know how to build UMS you can try the latest from the "7.0.0" branch.

**Comment by SubJunk** [comment] 2017-05-20 05:05
@Nadahar I'm happy to do a release if you think it would be good. There's certainly a lot of value in the 7.0.0 branch since the b3 release, and I might make the next release `7.0.0-RC1`. Do you want there to be another 6.x release before 7.0.0 final?

**Comment by Nadahar** [comment] 2017-05-20 09:45
@SubJunk I think it could be useful with a 6.x because some much have happened independent from 7.0.0. It could also make it easier for us to differentiate potential issues.

**Comment by SubJunk** [comment] 2017-05-21 05:05
@Nadahar great, I'll do a 6.x release soon

**Comment by SubJunk** [comment] 2019-11-03 20:08
My understanding is that this has been fixed. If that's not the case please reopen

**Closed by SubJunk** 2019-11-03 20:08 UTC
Labels: bug
