### ISSUE TITLE
Some devices don't support double escaping during SetAVTransportUR

### ISSUE THREAD

**Issue by wist543** [UniversalMediaServer/UniversalMediaServer#758] opened 2015-12-17 12:31 UTC
I try to play some movies on my TV(UE32ES6300) but it doesn't work. As per logs I've seen that my TV responses 500 on SetAVTransportURI and 500 on Play (I think cause playlist is empty).
As per wireshark traces I've seen that soap element CurrentURIMetaData is under double xml escaping:
```
<CurrentURIMetaData>&amp;lt;item id="96$Temp" parentID="Temp" restricted="true"&amp;gt;&amp;lt;dc:title&amp;gt;Constantine.S01E01.rus.LostFilm.TV&amp;lt;/dc:title&amp;gt;&amp;lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="562569216" duration="00:43:09.00" resolution="720x400" bitrate="217242" nrAudioChannels="2" sampleFrequency="48000"&amp;gt;http://192.168.1.34:5001/get/96$Temp/Constantine.S01E01.rus.LostFilm.TV.avi&amp;lt;/res&amp;gt;&amp;lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&amp;gt;http://192.168.1.34:5001/get/96$Temp/thumbnail0000Constantine.S01E01.rus.LostFilm.TV.avi&amp;lt;/res&amp;gt;&amp;lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&amp;gt;http://192.168.1.34:5001/get/96$Temp/thumbnail0000Constantine.S01E01.rus.LostFilm.TV.avi&amp;lt;/res&amp;gt;&amp;lt;dc:date&amp;gt;2015-12-07T03:18:32&amp;lt;/dc:date&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.videoItem&amp;lt;/upnp:class&amp;gt;&amp;lt;/item&amp;gt;</CurrentURIMetaData>
```
Response:
500
```
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode><errorDescription>Invalid Args</errorDescription></UPnPError>
```
As per code I've seen that we have first escaping in DLNAResource.getDidlString() and second in cling library(XMLUtils during ActionCallback).

During debug if I change CurrentURIMetaData to value after first escaping all works fine.
```
<CurrentURIMetaData>&lt;item id="99$Temp" parentID="Temp" restricted="true"&gt;&lt;dc:title&gt;iZombie.s01e06.WEBDLRip.NewStudio&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="565422080" duration="00:42:31.00" resolution="720x400" bitrate="221642" nrAudioChannels="2" sampleFrequency="48000"&gt;http://192.168.1.34:5001/get/99$Temp/iZombie.s01e06.WEBDLRip.NewStudio.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&gt;http://192.168.1.34:5001/get/99$Temp/thumbnail0000iZombie.s01e06.WEBDLRip.NewStudio.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&gt;http://192.168.1.34:5001/get/99$Temp/thumbnail0000iZombie.s01e06.WEBDLRip.NewStudio.avi&lt;/res&gt;&lt;dc:date&gt;2015-12-10T02:19:47&lt;/dc:date&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;</CurrentURIMetaData>
```
Response:
200
```
<u:SetAVTransportURIResponse xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\">
```
**Maybe I did something wrong? I used last master branch.**

Here some traces:
```
DEBUG 2015-12-17 13:00:12.985 [AWT-EventQueue-0] Sending upnp AVTransport.SetAVTransportURI [CurrentURI, http://192.168.1.34:5001/get/54$Temp/D%3A%5Cfilms%5CSupergirl.S01E07.rus.LostFilm.TV.avi, CurrentURIMetaData, &lt;item id="54$Temp" parentID="Temp" restricted="true"&gt;&lt;dc:title&gt;Supergirl.S01E07.rus.LostFilm.TV&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="594188288" duration="00:43:43.00" resolution="720x400" bitrate="226512" nrAudioChannels="2" sampleFrequency="48000"&gt;http://192.168.1.34:5001/get/54$Temp/Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;dc:date&gt;2015-12-16T02:22:05&lt;/dc:date&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;] to [TV]UE32ES6300[0]
DEBUG 2015-12-17 13:00:13.065 [AWT-EventQueue-0] Action failed: Error: Invalid Args (HTTP response was: 500 Internal Server Error)
DEBUG 2015-12-17 13:00:13.975 [AWT-EventQueue-0] Sending upnp AVTransport.Play [Speed, 1] to [TV]UE32ES6300[0]
DEBUG 2015-12-17 13:00:16.142 [cling-23] AVTransportURI: http://192.168.1.34:5001/get/54$Temp/D%3A%5Cfilms%5CSupergirl.S01E07.rus.LostFilm.TV.avi
DEBUG 2015-12-17 13:00:16.142 [cling-23] AVTransportURIMetaData: &lt;item id="54$Temp" parentID="Temp" restricted="true"&gt;&lt;dc:title&gt;Supergirl.S01E07.rus.LostFilm.TV&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="594188288" duration="00:43:43.00" resolution="720x400" bitrate="226512" nrAudioChannels="2" sampleFrequency="48000"&gt;http://192.168.1.34:5001/get/54$Temp/Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;dc:date&gt;2015-12-16T02:22:05&lt;/dc:date&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;
DEBUG 2015-12-17 13:00:16.142 [cling-23] CurrentTrackMetaData: &lt;item id="54$Temp" parentID="Temp" restricted="true"&gt;&lt;dc:title&gt;Supergirl.S01E07.rus.LostFilm.TV&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="594188288" duration="00:43:43.00" resolution="720x400" bitrate="226512" nrAudioChannels="2" sampleFrequency="48000"&gt;http://192.168.1.34:5001/get/54$Temp/Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Supergirl.S01E07.rus.LostFilm.TV.avi&lt;/res&gt;&lt;dc:date&gt;2015-12-16T02:22:05&lt;/dc:date&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;
DEBUG 2015-12-17 13:00:16.242 [AWT-EventQueue-0] Action failed: Error: Transition not available (HTTP response was: 500 Internal Server Error)
```

**Comment by Nadahar** [comment] 2015-12-17 17:59
@wist543 I seems you have found a bug, but I'm not sure I understand what you do and how to reproduce it. Exactly how are you starting the playback?

**Comment by skeptical** [comment] 2015-12-17 17:59
@wist543 thanks for the extremely well-researched report :+1:.  A couple of questions:

> As per code I've seen that we have first escaping in DLNAResource.getDidlString() and second in cling library(XMLUtils during ActionCallback).

Can you point to where/how this second escaping in  ```ActionCallback``` via ```XMLUtils``` happens?  I've just checked the source and don't see it, but cling is very granulated and labrynthine and slippery, so I may have missed something.

UMS itself is double-transforming ampersands, i.e. ```<``` to ```&lt;``` to ```&amp;lt;``` in   [StringUtil.encodeXML()](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/util/StringUtil.java#L96) via ```DLNAResource.getDidlString()```, so possibly this is the source of the problem and cling is blameless here?

> During debug if I change CurrentURIMetaData to value after first escaping all works fine.

Since you don't describe exactly where/how you are intervening during debug, and assuming that cling isn't involved here, then the solution is that ums should send single-transformed amersands, i.e. ```&lt;```?

**Comment by Nadahar** [comment] 2015-12-17 18:03
@skeptical I've delt with ```encodeXML()``` before, and it has to be double escaped there normally. The reason is that the string is within a section that is again a payload in the xml. But, maybe it's being called from somewhere where that's not the case, that's why I wondered how the playback is initialized.

**Comment by skeptical** [comment] 2015-12-17 18:07
@Nadahar I know, but we can "re-single-escape" it when sending ```SetAVTransportURI```.

**Comment by wist543** [comment] 2015-12-17 18:45
@skeptical Second escaping is happened in org.fourthline.cling.model.XMLUtil.encodeText. From ActionCallback we go to SendingAction.sendRemoteRequest here we go to SOAPActionProcessorImpl.writeBody where we have writeBodyRequest and after toString(our document). Starting from here cling uses simple recursion and escapes all not Element nodes with not null values (in our case CurrentURIMetaData contains TextNode with escaping value) in XMLUtil.nodeToString (XMLUtil.encodeText).
@Nadahar I try to start playback from UI (button play)). Logical.pressPlay contains next logic - do setUri (here we send setAVTransportURI) and without checking any errors do play...

@skeptical Under debug I reverted value of CurrentURIMetaData in XMLUtil.encodeText of cling. I could try to do unescaping with result of DLNAResource.getDidlString but as I understand it's not right cause some attributes or elements should contain escaping symbols like dc:title for example.

**Comment by skeptical** [comment] 2015-12-17 19:08
@wist543 thx for the roadmap :-). A diff to explain exactly what precisely is meant by "I reverted value of CurrentURIMetaData in XMLUtil.encodeText" would be helpful too, but to make a long story short, the string returned from ```XMLUtil.encodeText``` should look like this?
```xml
<CurrentURIMetaData>&lt;item id="99$Temp" parentID="Temp" restricted="true"&gt;&lt;dc:title&gt;iZombie.s01e06.WEBDLRip.NewStudio&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="565422080" duration="00:42:31.00" resolution="720x400" bitrate="221642" nrAudioChannels="2" sampleFrequency="48000"&gt;http://192.168.1.34:5001/get/99$Temp/iZombie.s01e06.WEBDLRip.NewStudio.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&gt;http://192.168.1.34:5001/get/99$Temp/thumbnail0000iZombie.s01e06.WEBDLRip.NewStudio.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&gt;http://192.168.1.34:5001/get/99$Temp/thumbnail0000iZombie.s01e06.WEBDLRip.NewStudio.avi&lt;/res&gt;&lt;dc:date&gt;2015-12-10T02:19:47&lt;/dc:date&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;</CurrentURIMetaData>
```

**Comment by skeptical** [comment] 2015-12-17 19:43
@wist543 Here's a patch to test, it sends metadata withou xml-encoding. Remove the '.txt' extension, unzip, and put the enclosed [i]update.jar[/i] next to [i]ums.jar[/i] in your UMS program folder (and remove it after testing).  The diff is inside the jar if you want to apply it directly (and fix it, if required :-):

[update-ums-5.3.2-SNAPSHOT-unencode-xml.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/65851/update-ums-5.3.2-SNAPSHOT-unencode-xml.zip.txt)

**Comment by wist543** [comment] 2015-12-17 21:10
@skeptical thanks. I applied patch directly. all works fine. The fix is seemed like a hack) 
I finally enabled log of cling and there is of soap body before and after fix:
```
FINER: ===================================== SOAP BODY BEGIN ============================================
РґРµРє 18, 2015 12:37:54 AM org.fourthline.cling.transport.impl.SOAPActionProcessorImpl writeBody
FINER: <?xml version="1.0" encoding="utf-8" standalone="yes"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><CurrentURI>http://192.168.1.34:5001/get/54$Temp/D%3A%5Cfilms%5CBlindspot.S01E01.rus.LostFilm.TV.avi</CurrentURI><CurrentURIMetaData>&amp;lt;item id="54$Temp" parentID="Temp" restricted="true"&amp;gt;&amp;lt;dc:title&amp;gt;Blindspot.S01E01.rus.LostFilm.TV&amp;lt;/dc:title&amp;gt;&amp;lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="555167744" duration="00:43:16.00" resolution="720x400" bitrate="213833" nrAudioChannels="2" sampleFrequency="48000"&amp;gt;http://192.168.1.34:5001/get/54$Temp/Blindspot.S01E01.rus.LostFilm.TV.avi&amp;lt;/res&amp;gt;&amp;lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&amp;gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Blindspot.S01E01.rus.LostFilm.TV.avi&amp;lt;/res&amp;gt;&amp;lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&amp;gt;http://192.168.1.34:5001/get/54$Temp/thumbnail0000Blindspot.S01E01.rus.LostFilm.TV.avi&amp;lt;/res&amp;gt;&amp;lt;dc:date&amp;gt;2015-12-07T03:08:39&amp;lt;/dc:date&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.videoItem&amp;lt;/upnp:class&amp;gt;&amp;lt;/item&amp;gt;</CurrentURIMetaData></u:SetAVTransportURI></s:Body></s:Envelope>
РґРµРє 18, 2015 12:37:54 AM org.fourthline.cling.transport.impl.SOAPActionProcessorImpl writeBody
FINER: -===================================== SOAP BODY END ============================================
```
```
FINER: ===================================== SOAP BODY BEGIN ============================================
дек 18, 2015 12:53:12 AM org.fourthline.cling.transport.impl.SOAPActionProcessorImpl writeBody
FINER: <?xml version="1.0" encoding="utf-8" standalone="yes"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><CurrentURI>http://192.168.1.34:5001/get/87$Temp/D%3A%5Cfilms%5CMarvels.Daredevil.S01E03.rus.LostFilm.TV.avi</CurrentURI><CurrentURIMetaData>&lt;item id="87$Temp" parentID="Temp" restricted="true"&gt;&lt;dc:title&gt;Marvels.Daredevil.S01E03.rus.LostFilm.TV&lt;/dc:title&gt;&lt;res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/avi:DLNA.ORG_OP=01" size="646676480" duration="00:52:04.00" resolution="720x400" bitrate="206969" nrAudioChannels="2" sampleFrequency="48000"&gt;http://192.168.1.34:5001/get/87$Temp/Marvels.Daredevil.S01E03.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN"&gt;http://192.168.1.34:5001/get/87$Temp/thumbnail0000Marvels.Daredevil.S01E03.rus.LostFilm.TV.avi&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM"&gt;http://192.168.1.34:5001/get/87$Temp/thumbnail0000Marvels.Daredevil.S01E03.rus.LostFilm.TV.avi&lt;/res&gt;&lt;dc:date&gt;2015-12-09T03:33:24&lt;/dc:date&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;</CurrentURIMetaData></u:SetAVTransportURI></s:Body></s:Envelope>
дек 18, 2015 12:53:12 AM org.fourthline.cling.transport.impl.SOAPActionProcessorImpl writeBody
FINER: -===================================== SOAP BODY END ============================================
```

It's hard question: string returned from XMLUtil.encodeText should look like this?) I just can prove that it's work with my TV. I'm newbie in upnp and dlna but as per spec we should send DIDL-Lite template as value and this value should be escaping but I don't see that this value could be escaping twice. I think for good backward compatibility it could be new parameter in renderer, am I right? I could try to fix this issue right way. (adding < or &lt; in getDidlString depends on new parameter)
P.S. getDidlString has javadoc with comment "Returns an XML (DIDL) representation of the DLNA node" not "escaping xml".

**Comment by skeptical** [comment] 2015-12-17 23:14
@wist543

> The fix is seemed like a hack)

In my (somewhat limited :-) experience dlna doesn't actually work without lots of hacks, but in this case I think the fix is straightforward :-).

> It's hard question: string returned from XMLUtil.encodeText should look like this?

I only meant "it works ok if the final string looks like this?"

> as per spec we should send DIDL-Lite template as value and this value should be escaping but I don't see that this value could be escaping twice.

See @Nadahar's comment up above, the double-escaping is because of xml-within-xml in http responses to the renderer, which is the original purpose ```getDidlString()```.  It was re-used as-is for ```SetAVTransportURI``` (by me, I confess :P) and so far I didn't know that this may not always work.  I guess the underlying reason might possibly be that your renderer isn't expanding ```&amp;``` to ```&``` as the first step, i.e. if that replacement is done before the others, then it doesn't matter if the xml is single or double-escaped.

> I think for good backward compatibility it could be new parameter in renderer, am I right?

I'm pretty sure applying this fix will work for all renderers (i.e. cling is happy with only sending single-escaped xml  as you have just shown us :-).  The problem was that the input to ```XMLUtil.encodeText()``` was already double-escaped, so it returned the same string it received.  It's working for me either way (with Kodi as renderer), and it's hard to see how any renderer would work with double-escaped but fail with single-escaped, but I've been wrong before :).

**Comment by wist543** [comment] 2015-12-18 00:24
> I think the fix is straightforward :-)
As you wish) I just wanted to help here with more flexible fix.
> See @Nadahar's comment up above
I think he means using encodeXML() for attribute for DIDL like upnp:album, dc:title etc. So result of getDidlString is already double escaped for internal attribute if it's needed. With fix we have xml + escaping symbols for attribute so that's why all works fine. (cling escaped our xml and all works as per spec)

**Comment by skeptical** [comment] 2015-12-18 00:39
> cling escaped our xml and all works as per spec
@wist543 yes, the 'fix' is to let cling do the xml-encoding this context. But please send us a better more flexible fix if you would like, I don't mean to imply that this is the ultimate solution, or that your solution wouldn't be better.

**Comment by Nadahar** [comment] 2015-12-18 01:02
@wist543 I'm unsure what you mean in some sentences, and that might create some slight misinterpretations here. 

I agree with @skeptical that the proper solution here is to let ```cling``` do the escaping for ```AVTransportURI```. ```encodeXML``` was probably just a "loaner" in this context anyway. It's works well for it's prime task. 

Also as @skeptical says, I doubt that some renderers expect this URL to be double-escaped, it's more likely that some accepts it without knowing it. In the end it probably depends on what order the characters are decoded if the resulting string will be valid or not.

**Comment by skeptical** [comment] 2015-12-18 03:29
@Nadahar committed in 2880cee, if it's good enough for cling it's good enough for us I think.

@wist543 If you see weaknesses in this or in ```getDidlString()``` please submit a pull request, help is always welcome :).

**Comment by Nadahar** [comment] 2015-12-18 20:49
@wist543 Thank you for a detailed and thorough bug report. I'm closing this as it seems to be fixed. The fix will be in the next release.

**Closed by Nadahar** 2015-12-18 20:49 UTC
Labels: bug

**Comment by SubJunk** [comment] 2015-12-18 21:03
Great work guys :)
