### ISSUE TITLE
Issues with external disks and updates osx

### ISSUE THREAD

**Issue by maz4200** [UniversalMediaServer/UniversalMediaServer#2299] opened 2020-11-30 14:24 UTC
# How to contribute

In order to help diagnose and fix your issue we often need your "debug information". It's easy to save this information and attach it to a GitHub issue:

  * Start UMS.
  * Go to the `Logs` tab.
  * Press the `Create TRACE logs` button which restarts UMS in the "TRACE" mode. If that doesn't work for some reason, either select `Trace` from the `Log Level` dropdown at the bottom or set `log_level = TRACE` in the configuration file and restart UMS manually.
  * Reproduce the problem.
  * Click `Pack debug files` on the lower left.
  * Click `Zip selected files`.
  * Save the zip file to a location you will remember.
  * Attach the zip file to the GitHub issue.

**Comment by maz4200** [comment] 2020-11-30 14:36
After updating to 9.8.2 from working version of 9.8.1 (It took 8 attempts as auto downloads failed  {10.14.6} and manual downloads reported damaged dmg file) UMS can no longer access sub folders on my external media disk.
Can open root disk but no subfolders are ever shown. Share scan reports no files.
Attempted to reinstall download of 9.8.1 dmg from github - same error with corrupt dmg file reporting.
Reinstalled my original 9.8.1 app from my own backup and this woks and scans external disk subfolders and lets me save them as shares. 
No relevant issues or errors shown in logs even in Trace
Problems same on both Mojave 10.14.6 and Big Sur 11.1

**Comment by SubJunk** [comment] 2020-12-01 00:53
@maz4200 where were you downloading from manually? Auto downloads in the program come from SourceForge, and our main official mirror is FossHub. They are both pretty good, and especially FossHub seems to have exceptional speed and availability.
Can you try both versions from FossHub?

As for the actual bug, please attach TRACE logs. If you are concerned about privacy you can PM me on our forum.

**Comment by valib** [comment] 2020-12-01 09:11
Possible answer is here http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14448

**Comment by maz4200** [comment] 2020-12-01 12:31
In reply to SubJunk.
First attempt was autoupdate from 9.8.1 in Mojave - autoupdate crashed when partly complete. (Several times) Then tried manual update to all available 9.8.2 versions for mac at Fosshub and Github hub - all reported damaged dmg file.
Opened 9.8.1 in Big Sur and it completed an autoupdate to 9.8.2 and relaunched. App would no longer access any subfolders on my external usb hard drive - which had worked on 9.8.1.
Tried to revert to Fosshub and github versions of 9.8.1 but all gave damaged dmg error.
Reverted to my own ccc backup of 9.8.1 and this installed and worked properly showing all subfolders and allowing me to share their contents.
I have installed other 'unsigned' apps successfully on Big Sur so not directly the Apple issue.
As I am now running the old 9.8.1  version there are no Trace logs available that are relevant - not that anything related to the issue showed up in the logs I viewed under 9.8.2 - just sat looking at a blank dialogue waiting for it to populate with my media subfolders. 9.8.1 installed from my backup is working ok on my firestick/TV so will stay with this for now.

**Comment by Nadahar** [comment] 2020-12-01 15:33
The chance that a file is genuinely damaged is very slim - especially when you download it multiple times. HTTP (the transfer protocol used by "web servers") is using TCP, and TCP has built-in error correction. That means that everything is transferred in chunks (on the protocol level) and a checksum is created for each chunk. The recipient calculates the checksum as well, and if it doesn't match what the sender said, the chunk is requested for retransmission until it does match.

As such, files being corrupted during transfer is extremely rare, and having a genuinely corrupt file usually means that it either was stored in a corrupt state, or that the sender or recipient somehow corrupted it either before or after transfer.

This is why I claim that it's extremely likely that it *is* in fact the "Apple issue" whenever macOS claims a "damaged DMG file". I assume you have tried removing the file system attribute before concluding that it's not caused by the lack of an Apple signature?

**Comment by maz4200** [comment] 2020-12-01 16:49
Ok found a fix to the damaged dmg file error.
Tried again to install 9.8.1 dmg and got dmg file corruption header.
Opened disk utility and converted the dmg (no changed options) and then opened 9.8.1 converted dmg this worked .
Looking at the get info of the two dmg files shows that the conversion in disk utility strips info from the file header.
<img width="257" alt="Screen Shot 2020-12-01 at 16 39 30" src="https://user-images.githubusercontent.com/21952948/100769995-a9e00600-33f4-11eb-9152-c66b25e989f8.png">
<img width="261" alt="Screen Shot 2020-12-01 at 16 39 11" src="https://user-images.githubusercontent.com/21952948/100770000-ab113300-33f4-11eb-81cf-8bfc05e3e846.png">

Looks like the Apple OS doesn't like this header info

**Comment by Nadahar** [comment] 2020-12-01 19:36
There is no need to rebuild the image. Just clear the attribute with 'xattr' (it gets set whenever you download files from the Internet, which is why this isn't set on images you "create"). 

The first 3 steps here is just the usual clueless mumbo-jumbo, but step 4 is the real solution. No need to be an "advanced" user, Apple has chosen to make it so that you can't clear this attribute using the GUI tools, so you need to use a terminal. There's nothing "advanced" about unless one counts using a terminal as "advanced": https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

**Comment by SubJunk** [comment] 2020-12-01 21:45
Thanks for the support in this thread everyone. As for the bug with external drives, would you be willing to test versions if I build and upload them for you @maz4200 ?
There was a big refactoring done from 9.8.1 to 9.8.2 so it would be good to test before and after that to see if that was the cause of the problem. We also bumped Java from 14 to 15 so that would be my next thing to try.

**Comment by maz4200** [comment] 2020-12-02 12:44
Many thanks for all the responses and certainly I am very happy to test any future builds.
However, and perhaps someone can point out errors on my part the attribute removal command operation did not go smoothly for this app - although it seemed to for other app downloads I tried.

MacBook-Pro:~ maz3$ xattr -cr //Users/maz3/Downloads/internet/UMS-9.8.1.dmg
(This coomand seemed to work - however attempting to open the app still resulted on the damaged app error so tried with the app) 
MacBook-Pro:~ maz3$ xattr -cr //Applications/Universal Media Server 3.app
xattr: No such file: //Applications/Universal
xattr: No such file: Media
xattr: No such file: Server
xattr: No such file: 3.app
MacBook-Pro:~ maz3$ xattr -cr //Applications/UniversalMediaServer 3.app
xattr: No such file: //Applications/UniversalMediaServer
xattr: No such file: 3.app
MacBook-Pro:~ maz3$ xattr -cr //Applications/Universal Media Server 3.app
xattr: No such file: //Applications/Universal
xattr: No such file: Media
xattr: No such file: Server
xattr: No such file: 3.app
MacBook-Pro:~ maz3$ xattr -cr //Applications/Universal Media Server3.app
xattr: No such file: //Applications/Universal
xattr: No such file: Media
xattr: No such file: Server3.app
MacBook-Pro:~ maz3$ xattr -cr //Applications/UniversalMediaServer3.app
xattr: No such file: //Applications/UniversalMediaServer3.app
(not sure why it couldn't find that file as path copied directly from finder window save path option)

MacBook-Pro:~ maz3$ xattr -cr //Users/maz3/Downloads/UMS-9.8.2.dmg
MacBook-Pro:~ maz3$ xattr -cr /Applications/Universal Media Server 4.app
xattr: No such file: /Applications/Universal
xattr: No such file: Media
xattr: No such file: Server
xattr: No such file: 4.app
(Tried with the expand dmg file)
MacBook-Pro:~ maz3$ /Volumes/Universal Media Server 1/Universal Media Server.app
-bash: /Volumes/Universal: No such file or directory
(Tried with renaming the app to remove spaces in name)
MacBook-Pro:~ maz3$ xattr -cr //Applications/UniversalMediaServer2.app
xattr: [Errno 13] Permission denied: '//Applications/UniversalMediaServer2.app/Contents/PlugIns/adoptopenjdk-15.jre/Contents/Home/lib/server/classes_nocoops.jsa'
xattr: [Errno 13] Permission denied: '//Applications/UniversalMediaServer2.app/Contents/PlugIns/adoptopenjdk-15.jre/Contents/Home/lib/server/classes.jsa'
MacBook-Pro:~ maz3$ xattr -cr //Users/maz3/Downloads/UMS-9.8.2.dmg

I am sure that with further work and with also changing permissions of contents folders I could get this to work - but actually using the disk utility convert option works quickly neatly and more simply for me

**Comment by Nadahar** [comment] 2020-12-02 14:11
I don't have a recent enough macOS available to test, so it's a bit of a guesswork for me. The idea is to remove the attribute for the file that macOS claims is "damaged". I thought that was the DMG file. However, you must do this to the DMS and then "install" the application.

When it comes to spaces in file names in terminal, you must either escape each space with a `\` (so that each space is written as two characters, first the backslash and then the space `\ `) or you must enclose the whole path in quotes or double quotes (I don't remember which).

When it comes to permissions, you just need to add `sudo` before `xattr` and then enter your password upon request.

**Comment by SubJunk** [comment] 2020-12-14 08:14
Thanks @maz4200 
Those before and after testing versions are https://www.universalmediaserver.com/uploads/UMS-605f7c0.dmg and https://www.universalmediaserver.com/uploads/UMS-e883f32.dmg
If you can let me know how they go, I can try to make a fix

**Comment by SubJunk** [comment] 2021-06-03 07:34
Closing this due to @maz4200 not getting back to us. Feel free to reopen

**Closed by SubJunk** 2021-06-03 07:34 UTC
