### ISSUE TITLE
Can't Login to Settings

### ISSUE THREAD

**Issue by purevertigo** [UniversalMediaServer/UniversalMediaServer#3794] opened 2023-01-25 07:36 UTC
After upgrading to the latest windows release, every time I try to login to the settings (new) I get pushed back out. Does anyone know what is happening here?

I am happy to supply whatever you need or a reset would be fine provided my DLNA settings are kept.

**Comment by SubJunk** [comment] 2023-01-26 19:49
@purevertigo please provide logs, instructions are at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new

**Comment by purevertigo** [comment] 2023-01-28 09:02
I have attached logs. Hopefully, that helps.

[ums_dbg_2023-01-28-20-01.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10526821/ums_dbg_2023-01-28-20-01.zip)

**Comment by aspirisen** [comment] 2023-01-28 17:21
I have the same issue

**Comment by Mik-S-UMS** [comment] 2023-01-30 12:43
I'm having trouble with this too. I was testing connecting to UMS on my PC from my laptop and it will not let me login. It accepts the login details but just returns to the login screen. 


```
INFO  2023-01-30 12:37:51.097 [pool-6-thread-15] Finding user: mik2 
INFO  2023-01-30 12:37:51.097 [pool-6-thread-15] Got user from db: mik2
TRACE 2023-01-30 12:37:51.097 [pool-6-thread-15] Unlocking account for mik2
INFO  2023-01-30 12:37:51.379 [pool-6-thread-15] User mik2 logged
TRACE 2023-01-30 12:37:51.381 [pool-6-thread-15] Response sent to 192.168.1.86:
============================= GUI HTTPSERVER RESPONSE BEGIN ===============================
HTTP/1.1 200

HEADER:
  Date: Mon, 30 Jan 2023 12:37:51 GMT
  Content-type: application/json
  Content-length: 392

CONTENT:
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxOTIuMTY4LjEuODYiLCJpc3MiOiJVTVMiLCJpZCI6NCwiZXhwIjoxNjc1MDg5NDcxfQ.zy4L2HLysl44P2kz6znJ2xYNeeLtEmL8AZnOOhWIGAE","account":{"user":{"id":4,"displayName":"Mik Lappy","groupId":2,"lastLoginTime":1675082271380,"loginFailedTime":0,"loginFailedCount":0,"username":"mik2"},"group":{"id":2,"displayName":"player","permissions":{"value":0}}}}============================= GUI HTTPSERVER RESPONSE END =================================
```
[debug.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10535821/debug.zip)


Some other things I have noticed. 
The show password button does not work on user accounts.
If turning `Authenticate localhost as admin` on then it does not let you access settings, only **My account** and there is no way to turn this back off without editing ums.conf
![image](https://user-images.githubusercontent.com/66766335/215478394-f7991ec0-e811-41a9-ab53-6b2b190b4a68.png)
[debug.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10535821/debug.zip)

**Comment by paolostivanin** [comment] 2023-01-30 18:28
same here (UMS 13.1.0 on openSUSE)

**Comment by SubJunk** [comment] 2023-01-30 22:30
@SurfaceS any ideas?

**Comment by SurfaceS** [comment] 2023-01-31 16:10
@Mik-S-UMS "mik2" is part of group you named "player" that has no permissions at all.
With admin login "Mik", add some permissions to the "player" group.

**Comment by Mik-S-UMS** [comment] 2023-01-31 18:06
Same thing happened accessing the Admin account Mik remotely on the laptop. I was messing around with options and thought a second user might work if the first was already logged in on the main computer. I had originally set mik2 as Admin group but was messing around when that did not work either, I must have missed the permissions part. I was not keeping track of log files so that one might not have been helpful.

I had thought of some things to try to narrow it down but I can't get the web interface to load today. I deleted the users.mv.db file to start to test things like I had done before but now I am getting this error
```

DEBUG 2023-01-31 17:42:22.428 [main] Error with HttpURLConnection: {}
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at net.pms.util.APIUtils.getJson(APIUtils.java:971)
	at net.pms.util.APIUtils.setApiImageBaseURL(APIUtils.java:228)
	at net.pms.PMS.init(PMS.java:631)
	at net.pms.PMS.createInstance(PMS.java:867)
	at net.pms.PMS.main(PMS.java:1021)
ERROR 2023-01-31 17:42:22.431 [main] A serious error occurred during Universal Media Server initialization: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "element" is null
DEBUG 2023-01-31 17:42:22.431 [main] 
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "element" is null
	at net.pms.util.APIUtils.setApiImageBaseURL(APIUtils.java:232)
	at net.pms.PMS.init(PMS.java:631)
	at net.pms.PMS.createInstance(PMS.java:867)
	at net.pms.PMS.main(PMS.java:1021)
```

in the logs. I tried a fresh clean install and rebooted computer and it still does it. Why is there reference to google there? Is UMS relying on some remote service that may go down? I don't think I did anything else so don't know why its not working now.
[debug.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/10549437/debug.zip)

**Comment by SurfaceS** [comment] 2023-01-31 20:07
nothing to do with google, it's just a package (made by google) that convert JSON to java objects.

**Comment by Mik-S-UMS** [comment] 2023-02-01 16:12
OK that makes sense and glad it has already been fixed. It strange that it just happened after it was working fine. 
What causes this as someone on the forum has just posted the same problem? 

Could you send me a test build with this fixed so I can do a bit of testing on the login problem?

**Comment by SubJunk** [comment] 2023-02-01 20:50
I'll make a test build later today

**Comment by SurfaceS** [comment] 2023-02-01 20:56
> What causes this as few people on the forum has just posted the same problem?

fail to download apiImageBaseURL (SocketTimeoutException), so json data was null (NullPointerException).

**Comment by Mik-S-UMS** [comment] 2023-02-02 16:37
Thanks @SubJunk.
I tried to replicate the login problem with this test build and it is working now. I wonder if these 2 things were related.

**Comment by Mik-S-UMS** [comment] 2023-02-02 19:38
I went back to 13.1.0 to test something and found that turning off external network fixed the NPE error allowing the web interface to load.
Annoyingly the login problem has also gone too :(

**Comment by Mik-S-UMS** [comment] 2023-02-05 20:06
Looks like these 2 problems are not related, at least for [this](https://www.universalmediaserver.com/forum/viewtopic.php?t=15611) user on the forum. And another one [here](https://www.universalmediaserver.com/forum/viewtopic.php?p=46905#p46905) it seems.

They had the "element" is null error but after turning off external network they still could not login. They have tried deleting users.mv.db and creating a new user but made no difference. They have posted debug logs too.

Also it appears the option to turn off external network from the old GUI is broken, unchecking the box does not save to UMS.conf but turning it on does.

**Comment by SubJunk** [comment] 2023-02-05 20:14
@Mik-S-UMS I'm tagging the next release now. I can't reproduce the problem with the old GUI though. I'll look at the forum logs today

**Comment by SubJunk** [comment] 2023-02-09 07:56
It looks like this is confirmed fixed now

**Closed by SubJunk** 2023-02-09 07:56 UTC
