### ISSUE TITLE
Regression for Matroska files with profile AVC (High@L4.1) (CABAC / 4 Ref Frames)

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#720] opened 2015-11-06 16:23 UTC
@UniversalMediaServer/developers @SubJunk 
According to [this thread](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=5592) there's been a regression since 5.1.1 for Matroska files with `AVC (High@L4.1) (CABAC / 4 Ref Frames)`. According to the user 5.1.0 is working fine. It seems to me the problem is with transcoding the file.

He claims to have tested all versions since 5.1.0 and the problem is the same for all. I don't have the necessary knowledge about video codecs and how it's dealth with by UMS to tackle this one, but I hope one of you guys can and will.

**Comment by SubJunk** [comment] 2015-11-06 20:44
@Nadahar thanks for making the report. I've gone back on the forum. It's likely related to a refactoring I did of the renderer config he is using. We'll see when he produces logs.

**Comment by valib** [comment] 2015-11-06 21:48
@SubJunk actually he is using his own config and what is strange that the mime type for the .mkv video is set to video/avi

**Comment by SubJunk** [comment] 2015-11-07 04:07
@valib yeah you're right he's using his own config. It's normal for Samsung TVs to use video/avi for MKV files. I suspect the issue is the "TranscodedVideoFileSize = 1000000" but we'll see

**Comment by Nadahar** [comment] 2015-11-07 06:31
@SubJunk From what he's saying, that's not logical. If it works with 5.10 and not with 5.1.1 or anything thereafter with the same configuration, the problem can't be with the configuration..?

**Comment by SubJunk** [comment] 2015-11-07 10:21
I don't think there's much point speculating about this until we get before and after logs, we don't know which configuration has been used with the earlier versions until we have logs to prove it :)

**Comment by Nadahar** [comment] 2015-11-07 21:50
@SubJunk I think we're often waiting a long time for forum reply because e-mail notification is not enabled by default. To me, the norm is that e-mail notification is automaticly enabled for any threads I start or post in, and I think many people expects the same. Is that some setting you could change in the forum administrator?

**Comment by antonevane** [comment] 2015-12-30 00:09
Any updates?

**Comment by valib** [comment] 2015-12-30 00:25
@antonevane how we can investigate the problem when you didn't follow the instruction @SubJunk gave you at http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=5592  Without the logs we are blind and we need users support. If you are willing to help us please follow the instruction and provide that logs.

**Comment by Nadahar** [comment] 2015-12-30 00:25
@antonevane No, the user never submitted debug files so we could see what went wrong. If you have the same problem, you can help by [posting debug files] (http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556) in the [same thread] (http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=5592)

**Comment by JohnN194** [comment] 2016-05-22 13:51
God same 976.56 KB issue (described here: http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=5592), here's debug log attached (rename the TXT to ZIP and unpack)

[ums_debug.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276336/ums_debug.zip.txt)

**Comment by Nadahar** [comment] 2018-09-01 19:46
No interest, closing.

**Comment by SubJunk** [comment] 2020-07-03 04:01
We did change a bunch of Samsung configs in 5.1.1 so this makes sense, but it seems to me based on the logs from @JohnN194 it is obeying the rules of the renderer config properly. The reason that file is being transcoded is:

`File will not be streamed because the bitrate (25470268) is too high`

If that file streams well when the `[No Transcoding]` option is chosen then maybe we can make the bitrate in the renderer config higher than 25mbps to allow this to stream.

If you are still around John, then please reply to this and I'll reopen. I'm closing it for now because it has been so long

**Closed by SubJunk** 2020-07-03 04:01 UTC
Labels: bug:confirmed
