### ISSUE TITLE
Plugin Management tab: Deprecated plugins, misleading, unnecessary

### ISSUE THREAD

**Issue by tobiajo** [UniversalMediaServer/UniversalMediaServer#1276] opened 2017-05-18 08:50 UTC
In the GUI under Plugin Management one can Download and install selected plugins.

The issue is that these plugins is usually deprecated and does not work. This is very misleading for the user, since "install by clicking" is expected to work out-of-the-box. I think that it is also very ugly that the Available Plugins list contains plugins that does not work anymore.

My proposal is to remove the Plugin Management tab from GUI since it does not provide anything good for the user, just the opposite, it makes UMS look very unprofessional. Only manual-install plugins is suffcient and the way to go in my opinion.

@SubJunk

**Comment by Nadahar** [comment] 2017-05-18 12:34
I agree that this is bad, one option would be to update the list with working plugins and remove those not being maintained.

**Comment by SubJunk** [comment] 2017-05-19 07:07
Are any of the plugins still working?

**Comment by Nadahar** [comment] 2017-05-19 10:19
I have no idea, I assumed so. @valib uses Jumpy so I'd assume that still works at least.

**Comment by tobiajo** [comment] 2017-05-19 10:50
I have used Channels previously, but now the installation does not work properly and the actual channels are very outdated. Just by looking at the date on GMusic and MovieInfo, it seems that they probably are outdated too. Jumpy looks outdate too according to [the forum](http://www.universalmediaserver.com/forum/viewtopic.php?t=288):
> Many thanks to users new and old, but alas jumpy is no longer under development and has become incompatible with UMS versions above 6.5.3 due to api changes. If you would like to try jumpy anyway, UMS 6.5.3 is available in the Official Releases archive.

**Comment by tobiajo** [comment] 2017-05-19 10:51
I have used Channels previously, but now the installation does not work properly and the actual channels are very outdated. Just by looking at the date on GMusic and MovieInfo, it seems that they probably are outdated too. Jumpy also looks outdated according to [the forum](http://www.universalmediaserver.com/forum/viewtopic.php?t=288):
> Many thanks to users new and old, but alas jumpy is no longer under development and has become incompatible with UMS versions above 6.5.3 due to api changes. If you would like to try jumpy anyway, UMS 6.5.3 is available in the Official Releases archive.

**Comment by SharkHunter** [comment] 2017-05-19 10:57
GMusic stoppped working most likely due to google "fixing" something. Channels work on the same base as Jumpy (it worked for me yesterday) and yes some channels are outdated but some are updated (and some are updated on my computer only). Before you remove the tab just consider that the credentilas handling are placed on that tab.

**Comment by Nadahar** [comment] 2017-05-19 10:57
@tobiajo This is just the author that doesn't want to play ball. I've made a PR for Jumpy that fixes the few things that were broken - all he has to do is to click a button and jumpys code will be updated and work again. He's not interested in this for some reason unknown to me, and instead decided to retire jumpy. I have compiled the updated version, which @Sami32 made available in the same forum thread. We could offer this version for download with UMS.

**Comment by SharkHunter** [comment] 2017-05-19 11:02
@Nadahar - or one can argue that someone else thinks it's absolutly essential to break stuff that makes plugins not usable anymore. One could argue that it is not to "play ball" either. And if two parties disagree then one must yield in this case Infidel and me retired. You can clone Jumpy and maintain it. But you haven't done that so who isn't playing ball?

**Comment by Nadahar** [comment] 2017-05-19 11:14
@SharkHunter Do you really want to start that argument again? FYI, I was only responsible for one of the changes and it was in my opinion absolutely needed. I made the necessary fixes and offered them through a PR. I have left a lot of things alone to avoid breaking plugins, so those accusations simply aren't true.

I have cloned Jumpy, how would I otherwise be able to compile a fixed version? But, it seems that you are suggesting I should make a fork. Why would I do that, when I know so little about Jumpy and how it works? I can easily update a few calls to make them compatible with the changed API, but I have little idea of the inner workings of Jumpy, especially the Python "bridge". I would be completely lost. I also have more than enough on my plate already.

You "retiring" was your own choice, nobody asked you to do that - in fact quite the opposite.

**Comment by SharkHunter** [comment] 2017-05-19 11:23
> suggesting I should make a fork. Why would I do that, when I know so little about Jumpy and how it works
You are not interested in forking and Infidel is not interested in maintaining. You "blame" him for not playing ball. I'm saying you are equally much to blame since you have not forked. If it is as easy as pressing a button than why wouldn't you fork?
It is not just someone not playing ball. We have other things to do which are more fun. You are left in the project so all the things fall on you. Either you fork or you say it will not work.

**Comment by Nadahar** [comment] 2017-05-19 11:28
@SharkHunter Your argumentation isn't very logical to me. As I've said, I have made GitHub fork and compiled a working binary. Isn't that what you're accusing me of not bothering to do?

What I meant with forking was that I would continue the development of Jumpy, which isn't viable since I know so little about it. I don't think I could do anything that would satisfy you, you seem to wanna blame me for simply.... existing.

**Comment by tobiajo** [comment] 2017-05-19 12:07
Whatever, the organisation around having an up-to-date Plugin Management tab does not seem to work. I see two options:
1. Do something about it and keep an up-to-date tab, where the plugins always work.
2. Or simple remove the tab and only support manual-install plugins.

This is not my decision to make, but consensus regarding this issue should be reached.

**Comment by Nadahar** [comment] 2017-05-19 12:11
@tobiajo I agree, as you can see this has been somewhat of a "hot potato" internally and I think people have been a bit afraid to touch it not to step on anyone's toes. The decision is ultimately up to @SubJunk. I vote for just leaving the "updated" Jumpy there since there seems to be quite a number of users still using it.

**Comment by Sami32** [comment] 2017-05-19 12:34
@tobiajo From what i understood, some see this from the plugins possibilities point of view and some from UMS healty framework.  That's doesn't look too much compatible views, IMHO...

So it seem to me that no consensus can be obtained by now, and that will be the projet's owner decision @SubJunk 

I share your point, that keeping unsupported plugins is not responsable, fair for the users.

**Comment by tobiajo** [comment] 2017-05-19 12:53
@Sami32 yes, plugins from the tab that does not work will make users leave UMS instead of speak good about it for their friends.

I don't see why only manual-install plugins is not sufficient.

**Comment by Nadahar** [comment] 2017-05-19 13:06
@tobiajo 
> I don't see why only manual-install plugins is not sufficient.

In the case of Jumpy it's a bit special since the author refuses to update it so that it will work with the latest versions of UMS. That's why I though that offering a compatible version there could be a good idea. In general I agree, especially since the plugins offered are not being kept up-to-date and working.

**Comment by SharkHunter** [comment] 2017-05-21 07:14
@Nadahar - I don't know why I bother but anyhow. "In the case of Jumpy it's a bit special since the author refuses to update it" is to a bit of an "alternative fact". The truth is he doesn't think it's worth spending time doing this update. You claim "it's just to press a button" when we all know it takes some time to do a new release etc. Now I think someone else was really upset when it was his time that was being "wasted" (https://github.com/UniversalMediaServer/UniversalMediaServer/pull/942) but that was probably different? 
I agree with the statement that "it looks bad" that plugins doesn't work. But since there essentially have ever only been two plugin writers to the UMS universe that had some duration and now both left you should probably remove all plugins. Or how many of the plugins on this page do you think works? (http://www.universalmediaserver.com/plugins/). And they aren't updating either.
Stop pointing finger to JUmpy and either solve yourself or drop it completely.Infidel isn't refusing anything he simply doesn't want to it which is in his right.

**Comment by ExSport** [comment] 2017-05-21 07:20
Neverending story about cat and mouse...
Btw. MovieInfo (csfd) works for me :)

**Comment by SharkHunter** [comment] 2017-05-21 08:27
@ExSport - well does any other part of movieinfo work? Are you maintaining it? I ain't at least.
Every plugin I use works for me.

**Comment by ExSport** [comment] 2017-05-21 08:54
Must retest with latest versions but yes when I spotted e.g. csfd.cz parsing doesn't work I fixed it.
Same for imdb.com when someone asked for it that it didn't work.
Generally plugin works but as web sites change in time it is required to fix parsing sometimes.

**Comment by SharkHunter** [comment] 2017-05-21 08:59
@ExSport - yes that's the point here. I am not maintaing MovieInfo (I never was actually just fixed once and then was stucked with it) so if you are not planning of forking it it will die same just like Channels and Jumpy. Either someone starts maintaining them or the are dead. Saying stuff like "the author refuses" are misleading. The author "refused" maintain Movieinfo 5-6 years ago so I did it without saying stuff like "refused" and "doesn't play ball". I don't see the difference here.

**Comment by Nadahar** [comment] 2017-05-21 15:35
@SharkHunter 
>  I don't know why I bother but anyhow. "In the case of Jumpy it's a bit special since the author refuses to update it" is to a bit of an "alternative fact". The truth is he doesn't think it's worth spending time doing this update. You claim "it's just to press a button" when we all know it takes some time to do a new release etc. Now I think someone else was really upset when it was his time that was being "wasted" (#942) but that was probably different?

It's amusing that you're accusing me of providing "alternative facts". Have you picked up some argumentation techniques from a certain orange president? Explaining something to you is like talking to a wall, because you don't pay attention to anything that's said that doesn't fit your view, and you keep reiterating your false claims even if they are refuted in the previous comment. If I'm to take a "glass half-full" position I'd say your memory is very bad.

Since you have such trouble remembering, I'll have to remind you what have happened regarding the plugins: A long time ago, I submitted PRs to all the to me known plugins that weren't dead where all calls to then deprecated fields or methods had been updated:
* https://github.com/SharkHunter/MovieInfo/pull/6
* https://github.com/SharkHunter/Channel/pull/24
* https://github.com/SharkHunter/GMPMS/pull/1
* https://github.com/skeptical/jumpy/pull/1

Only one was merged, and that was the MovieInfo. Even if you don't have the "energy" to do a new release with these changes only, why not merge the fixes? That is as simple as pressing a button AFAIK. If you could be bothered to merge these, we could have gotten rid of a lot of deprecated fields and methods cluttering UMS' code when the next release was made for these plugins or you could find the time to do a release. But, you simply weren't interested in doing this, and instead there was a lot of arguments about "Why change something that's working", "I like it the way it is" etc. basicly stating that neither of you were interested in any changes as a matter of principle (or at least without giving any other reason for it). Dusings of arguments followed for every change that were to be made were there had to be a very good reason to actually change something in UMS, and you would decide what reasons were good or bad.

Time went by with endless discussions where you resisted any change that could potentially affect your plugins, and you ended up "retiring". I even offered to leave, but neither of you were interested because you "wanted to leave anyway". In fact you had all kind of explanations for how your "retirement" was *not* caused by the endless arguments about changing anything. Despite this, you now claim in a comment above:
> And if two parties disagree then one must yield in this case Infidel and me retired.

At one point in time, @valib discovered that Jumpy had stopped working with the latest version of UMS because of changes that were made *not only by me*. This was very minor stuff, so again I made a PR (when will I learn...?): https://github.com/skeptical/jumpy/pull/3

This ended up in yet another discussion where it was apparant (to me) that the main objective was to resist any change that could affect the plugins, that all code that (potentially) interact with the plugins should be frozen for eternity. I simply figured that there's nothing I can do about it, any amount of argumentation or reason will change anything, so I decided I wouldn't waste my time trying to keep the plugins working ever again. Yet you now accuse me of not bothering to do just that. I think I've been very forthcomming in my efforts to solve the issues between UMS and the plugins.

If anyone wants to fork any of them and keep them updated that would be great, but why should this be my responsibility? I find this completely unreasonable. If I actually used or was interested in the functionality of one I probably would, but to me they aren't that interesting. I've still made an effort to keep the wheels turning for those that think otherwise. Why should I do anything more?

**Comment by Sami32** [comment] 2017-05-21 19:05
So, the 3 plugins that still work, at least partially, should be set as manual download.
**As the first goal is the users satisfaction.**
The users will understand better that it is a separate add not anymore maintained by actual UMS developpers, but can benefit of it, and search help/trick on the forum if they want to.

That was my 2 cents.

**Comment by SubJunk** [comment] 2017-06-05 04:58
Let's keep the discussion civil in here please. There are too many ad hominem arguments lately in this and other PRs.

**Comment by mirh** [comment] 2017-07-25 11:59
> Or how many of the plugins on this page do you think works? (http://www.universalmediaserver.com/plugins/)

Somebody should update that page. 
Movieinfo 0.9.3 version was released in August 2015 actually

Channels and GMusic could point to Nadhar [egregious](https://github.com/Nadahar/Channel) [forks](https://github.com/Nadahar/GMPMS).. 

As for jumpy, I wouldn't know.. But I'm not sure why version 0.3.9b is reported when latest one is 0.3.10, a year newer (it also has broken website link)
Also also, UMS only offers you to download the former, for some reason.

**Comment by Nadahar** [comment] 2017-07-25 12:09
As for jumpy, [this branch](https://github.com/Nadahar/jumpy/tree/show_generic_images_adaptation) is working with latest master as far as I know (and it is a modified version of the latest jumpy).

**Comment by mirh** [comment] 2017-07-25 13:16
It should be what UMS automatically fetches then.

**Comment by Nadahar** [comment] 2017-07-25 13:17
I'm not really into plugins, but I thought it was.

**Comment by SubJunk** [comment] 2018-11-05 21:20
This has been done now

**Closed by SubJunk** 2018-11-05 21:20 UTC
