### ISSUE TITLE
Video stops and play the next file

### ISSUE THREAD

**Issue by junusung** [UniversalMediaServer/UniversalMediaServer#488] opened 2015-02-22 23:22 UTC
I've been using ps3 media server for a long time and recently switched to UMS 5.0.
5 out of 10 times, it stops playing after 30min or so and skips to the next file by itself.
Please help me on this problem. 

Thank you so much for your work and support!

The log file is attached.

**Comment by SubJunk** [comment] 2015-02-23 00:10
@junusung thanks for the report. I don't see a log file

**Comment by junusung** [comment] 2015-02-23 00:22
It says zip file is not supported...How do I upload the file?

**Comment by SubJunk** [comment] 2015-02-23 01:56
Instructions are at https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CONTRIBUTING.md

**Comment by junusung** [comment] 2015-02-23 03:28
http://www.universalmediaserver.com/forum/viewtopic.php?f=11&t=2991

Here you go.

**Comment by SubJunk** [comment] 2015-02-24 02:45
@junusung does this fix it? http://www.spirton.com/uploads/UMS/UMS-09d7631.exe

**Comment by junusung** [comment] 2015-02-24 02:53
It's for Mac OS X.

**Comment by SubJunk** [comment] 2015-02-24 03:42
@junusung I can't build for OS X but maybe @Optimusprimeums can help us out by building 09d7631

**Comment by Optimusprimeums** [comment] 2015-02-24 05:43
@junusung give me a couple of hours and i'll have it up

**Comment by Optimusprimeums** [comment] 2015-02-24 08:56
@SubJunk @junusung just building it now, had to learn to merge and fix errors to build a java 6 version. I think i have it worked out now

**Comment by Optimusprimeums** [comment] 2015-02-25 06:07
@junusung here's the test file. forgot to put up the link after i uploaded it
http://sourceforge.net/projects/unimediaserver/files/Other%20Releases/OS%20X/UMS-OSXJ6-09d7631.dmg/download

**Comment by junusung** [comment] 2015-02-25 17:39
Still experience same problem. I attached another log pack.

http://www.universalmediaserver.com/forum/viewtopic.php?f=11&t=2991&p=15143#p15143

**Comment by SubJunk** [comment] 2015-02-25 20:34
@Optimusprimeums it looks like that merge didn't include the commit that may have fixed this bug, so I'll do another merge

@junusung thanks for the logs, hopefully we'll have another build to test soon

**Comment by SubJunk** [comment] 2015-02-25 20:46
@Optimusprimeums can you please build the latest OSX-Java6 branch? :)

**Comment by Optimusprimeums** [comment] 2015-02-26 06:08
@SubJunk Sure i can

**Comment by Optimusprimeums** [comment] 2015-02-26 06:16
@SubJunk i'm not seeing any updates to that branch?

**Comment by SubJunk** [comment] 2015-02-26 06:27
@Optimusprimeums I derped when I should've pushed, fixed now :)

**Comment by Optimusprimeums** [comment] 2015-02-26 07:02
@junusung http://sourceforge.net/projects/unimediaserver/files/Other%20Releases/OS%20X/UMS-5.0.2-J6-a4e9440.dmg/download please check this version

**Comment by SubJunk** [comment] 2015-03-07 22:39
@junusung any news on this?

**Comment by junusung** [comment] 2015-03-09 16:05
Still having same problem. I'm currently using ps3 media server.

**Comment by Sami32** [comment] 2016-08-18 15:20
@junusung Did the latest UMS version solved this issue ?

**Comment by SubJunk** [comment] 2020-02-24 03:33
I opened up those old logs and they don't show any playback activity, so I don't think the bug was reproduced during those sessions of UMS use. Since there isn't any technical information to go on I'm closing this.

**Closed by SubJunk** 2020-02-24 03:33 UTC
