### ISSUE TITLE
Javaw.exe opening files and stopping parent folders being moved/deleted (Win 10 permission denied error)

### ISSUE THREAD

**Issue by ZZKJInc** [UniversalMediaServer/UniversalMediaServer#2465] opened 2021-04-24 01:20 UTC
this is a very random bug, maybe once every 24 fours, sometimes a little more.

I tried to move and delete a folder in a directory that was being scanned by UMS as a shared folder. 

In windows 10 pro I got a permission denied error when trying to move/delete this directory.

Looking into it the files were open in another process.

I used process explorer to ascertain that javaw.exe was opening these files and not closing them during the current UMS session. 

Quitting UMS freed javaw.exe hold(open file handle but never closed) on these files.

I was then able to delete the folders/files that javaw.exe had opened for UMS but not closed. Exiting UMS closed said files. 

Javaw.exe is not closing all the files it accesses while in memory.

**Comment by SubJunk** [comment] 2021-04-24 22:50
@ZZKJInc this is a bug for sure but I believe it is a bug with Windows or Java itself. We have looked at it before and it seems that we are doing what we can with it.
If it is the same bug, you can work around it by unchecking "Monitor played status of files" on the shared content tab for the parent folder.
If that doesn't work please let us know since that would be a different bug

**Comment by ZZKJInc** [comment] 2021-04-25 23:12
OK will do, I'll check back if that doesn't work.

P.S. This always occurs during the same operation. I have files auto downloading, a temp directory is created, all files are decompressed to this temp directory then once complete immediately moved to the final destination folder. The whole process is very quick as its automated. Its the final stage(moving), moving the files that cause Javaw.exe the problem. The files are almost definitely being scanned by UMS via Javaw.exe while the other process(nzbget) is trying to move them also. NZBGet fails and moves on to its next download as Javaw.exe has handles open for these files. At this point also javaw.exe never releases the files until UMS server has been exited/reloaded. Moving a file that has been freshly created seems to create the problem.

**Comment by StingeyNinja** [comment] 2021-07-08 02:28
I have exactly the same issue in the same scenario - files downloading into a temp folder before being moved on completion.  About 80% of the time, at least one file in the temp folder will have an open handle from javaw.exe and prevent the file from being moved and the temp folder deleted.

I would like the retain the "Monitor played status of files" feature though, so anything that could be done to resolve this would be great.

**Comment by valib** [comment] 2021-07-08 07:28
Please try to use your own temp folder than the default one for processing the dowloaded files

**Comment by SubJunk** [comment] 2021-07-08 07:56
@StingeyNinja next time it happens can you please attach logs, and let us know which file/s are locked? There may be a clue in the logs

**Comment by SubJunk** [comment] 2021-07-15 07:23
@StingeyNinja I haven't been able to reproduce this so far, and I spent a while on it today, so I need your help if this can be resolved. Please try to reproduce it with this version: https://www.universalmediaserver.com/uploads/UMS-2465-locked-folders-8d3734f.exe
That version has file watching but will not parse the new files for the Media Library automatically - so it's not a solution, but it is a way to narrow down which functionality is causing this problem.

**Comment by StingeyNinja** [comment] 2021-07-21 06:20
I'll try the build provided, and supply logs and filenames when/if the issue re-occurs

**Comment by StingeyNinja** [comment] 2021-08-04 12:29
I reproduced the issue with v10.8.2.  The log line where it all seems to start is:
`DEBUG 2021-08-04 10:13:56.097 [File watcher]`

Logs attached.  Sorry I wasn't running the build you provided at the time @SubJunk 
[ums_dbg_2021-08-04-21-01.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6931231/ums_dbg_2021-08-04-21-01.zip)
![2021-08-04](https://user-images.githubusercontent.com/44279024/128180794-abb00534-ee56-4d17-8482-01f31c06a437.png)

**Comment by SubJunk** [comment] 2021-08-07 03:06
@StingeyNinja cool, thanks. I can see some possibly-useful details in the logs. It would be great to get you to run that custom build still

**Comment by SubJunk** [comment] 2021-08-09 04:33
I have another build for testing if you can https://www.universalmediaserver.com/uploads/UMS-2465-files-locking-a556e9d.exe
This one doesn't have any noticeable differences, it will still parse the files as they're added

**Comment by SubJunk** [comment] 2021-08-23 04:56
I have just reproduced this and found something interesting - if I force garbage collection, the file is freed, which is a very good clue.

**Comment by StingeyNinja** [comment] 2021-08-29 04:01
In the absence of any other update, just confirming that I've downloaded the build provided above and I'm running it.  I'll report any issues as they occur.

**Comment by SubJunk** [comment] 2021-08-29 05:16
@StingeyNinja thanks! I think it should happen less often now than before, but will still happen sometimes. It seems that we are relying on Java to release the resource when it runs the garbage collector, instead of releasing it ourselves. I can do a kind of hack where we ask Java to run the garbage collector after parsing, which normally works but isn't completely reliable, so I'll try to find a real fix if it's possible. 
Some things I've seen say it's Java's own nio file service that is to blame, if that's the case we can use a different way to do file things

**Comment by StingeyNinja** [comment] 2021-09-14 00:45
Using the last test build provided, I just had another re-occurrence at timestamp that seemingly occurred from this line in the debug log:  `DEBUG 2021-09-13 12:24:54.676 [File watcher] ENTRY_CREATE`

I don't see the `javaw.exe` holding a handle open to that file now though, so it appears to have only been temporary.  Maybe UMS needs a little sleep before it processes a file that it's interested in, to allow for the _rename then move process_ that some downloaders use (i.e. uTorrent)?

[ums_dbg_2021-09-14-10-38.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7158100/ums_dbg_2021-09-14-10-38.zip)

**Comment by SubJunk** [comment] 2021-09-14 07:34
@StingeyNinja my understanding after debugging it is that javaw.exe will hold onto the file until Java decides to run its garbage collector. It decides when to run it and that timing is non-deterministic AFAIK - sometimes it will be 1 second and other times it can be 1 hour. I can manually request it to run the garbage collector and that will work 9/10 times, and maybe I should do that until the real fix happens

**Comment by SubJunk** [comment] 2021-09-14 08:02
@StingeyNinja here is a build that has that hack in it, please let me know how it goes :) https://www.universalmediaserver.com/uploads/UMS-2465-gc.exe

**Comment by SubJunk** [comment] 2021-10-13 02:58
I'm going to close this, happy to reopen it if the bug happens again

**Closed by SubJunk** 2021-10-13 02:58 UTC
