### ISSUE TITLE
UMS v8.2 - inconsistent behavior

### ISSUE THREAD

**Issue by ExSport** [UniversalMediaServer/UniversalMediaServer#1809] opened 2019-06-27 14:04 UTC
Installed new version v8.2 on parents Windows computer.
Shortly tested and spotted:
- different level of logging for video and picture parsing (audio not tested) as pictures parsing is logged as TRACE but video as DEBUG.
- renderer "resolving" is weird as sometimes UMS generates recognition info every second, see picture attached:
![image](https://user-images.githubusercontent.com/1260408/60272262-1dbeda80-98f4-11e9-8d1f-1aea32f0f1b2.png)

It was a short test so no logs. Will try to add them later (the initial scan generated log size of about 2GB, 400MB DB size = NAS shared with family videos and pictures).

**Comment by atamariya** [comment] 2019-08-30 09:49
LG TV queries for the complete DLNA tree. This is problematic if you also have media library enabled (check hide_media_library_folder in UMS.conf).

**Comment by ExSport** [comment] 2019-08-30 10:28
Hello @atamariya 
No, I don't share MediaLibrary folder, it is hidden. But it seems your answer is not related to this issue :)

**Comment by atamariya** [comment] 2019-08-30 11:19
Actually it is related. The flood of recognition message is for each request made by the TV.

**Comment by ExSport** [comment] 2019-08-30 11:50
Yay, ok, thanks @atamariya . I thought it is somehow cached so spamming will reduce somehow.
Anyway why such storm when Medialibrary is enabled to cache items but it is hidden from renderers. So at the time of initial indexing, UMS server must index all files but the folder structure visible by the renderers should be the same (but with much faster responses from UMS side at time of real request).
I thought this storm is because UMS switches between two different UUIDs for the same renderer with the same IP. So at time it switches from one to other (for same renderer but with different UUID and supported features/protocols/profiles), that it is the reason of such spam. For other renderers which announces itself as the only one identity, there is no such storm if I remember right.

**Comment by atamariya** [comment] 2019-08-30 12:02
In this case, problem with Media library (the folder) is that it contains many virtual folders (think artists, albums, date etc). If it's visible to LG, it queries for files till the last node which causes the storm. Other renderers are more sensible and only make requests when user clicks on an icon in the UI.

Caching is separate from media library folder - it simply means using a DB. Metadata is cached upon exploration - not at the startup.

**Comment by ExSport** [comment] 2019-08-30 12:19
This all I know @atamariya 
The problem is that MediaLibrary folder was hidden. And as you know, to enable caching, you need to enable MediaLibrary:
![image](https://user-images.githubusercontent.com/1260408/64019769-536c8380-cb30-11e9-8303-079c2359a64a.png)
And as you know, new UMS initiates shared folders scanning (analysis) every UMS restart or by clicking on magnification icon.
It means renderer should see same structure whenever scanning is in progress or not (or if caching/Medialibrary is enabled, with folder hidden). But it seems during scanning there was quite storm of renderer detection, not sure if it was because of running initial indexing or because UMS switched between two different UUIDs for the same renderer...

**Comment by atamariya** [comment] 2019-09-01 15:45
Each request from a renderer triggers a detection. If you see storm of those, that means there is a storm of those requests from renderer.

**Comment by ExSport** [comment] 2019-09-02 09:13
I understand but my understanding was that when UMS detects such renderer and displays it in GUI, there should be no additional storm in log like that (as the renderer was already detected). Maybe showing them only in deeper logging levels (Trace, all,...) so using e.g. TRACE logging, there will not be such spam complicating reading the logs and its troubleshooting? 👍

**Comment by Nadahar** [comment] 2019-09-02 12:46
The current code doesn't "care" if the renderer has already been detected. It will do the "detection" for each HTTP request.

**Comment by ExSport** [comment] 2019-09-02 13:09
Hi @Nadahar and @atamariya Thanks for clarification from both of you. As the GUI shows active/inactive renderer icons, I supposed it knows if the renderer was detected already and still online so it should be easy to lower the "detection spam" in logs, right? :-)
I have a lot of devices in network, which responds to UPnP/DLNA so my logs are full of such spamming lines complicating to see what is essential and what not...

**Comment by Nadahar** [comment] 2019-09-03 02:33
@ExSport The detection code is quite the mess, so I don't know if I'd say that making any changes to that is "easy". That said, it should be doable. The question is if it's worth the effort, AND if it's desirable to remove these as it can make debugging harder in some cases.

I guess this is up to the UMS devs.

**Comment by atamariya** [comment] 2019-09-03 04:37
@ExSport if you're not a developer, it should not bother you what's in the logs as long as it's not personal info. If you're a developer, a pull request, with whatever your desired log level is, is welcome.

@SubJunk can you mark this defect as "won't fix"? This would enable the developers to focus on more important defects.

**Comment by ExSport** [comment] 2019-09-03 08:10
@atamariya Few of PRs I already done but I am not pure Java programmer but Powershell guy more often :-)
I will try to check the code, maybe I will spend 20 times more time on it, but if it is doable, maybe it is worth to try it (in my logs 80% of lines are detection storm so relevant info is hidden there).
Btw. maybe doing a cleanup code in powershell will take much less time....I will check it when I will find free time 👍

**Comment by SubJunk** [comment] 2019-09-03 20:50
@ExSport I agree the problem here is with LG TVs themselves. We are doing the correct thing by logging it. If we weren't doing that, we might not know about the problem with LG TVs in the first place and that is useful information for us to know :)

**Closed by SubJunk** 2019-09-03 20:50 UTC
Labels: won't fix

**Comment by ExSport** [comment] 2019-09-04 08:53
@SubJunk Anyway if your read the issue you should know what was the point. Also you closed it completely but I suppose it is still inconsistent to log pictures and videos differently (debug/trace level difference) but this part of this "issue" was completely ignored ;-)

**Comment by ExSport** [comment] 2019-09-04 12:50
@SubJunk  @atamariya @Nadahar 
It seems the real "issue" is inconsistent level of logging as some are logged as DEBUG but the others as TRACE.
I already mentioned VIDEO/PICTURES discrepancies.
Now I opened UMS outside home to see the level of logging:
```
...
TRACE 2019-09-04 14:30:48.417 [HTTPv2 Request Worker 6] Stripping preceding slash from: /images/icon-256.png
TRACE 2019-09-04 14:30:48.417 [HTTPv2 Request Worker 6] Matched media renderer "Windows Media Player" based on address 192.168.1.151
DEBUG 2019-09-04 14:30:48.418 [HTTPv2 Request Worker 6] Recognized media renderer "Windows Media Player"
TRACE 2019-09-04 14:30:48.418 [HTTPv2 Request Worker 6] Received a request from Windows Media Player (192.168.1.151:63457):
...
TRACE 2019-09-04 14:46:34.228 [HTTPv2 Request Worker 7] Converting input stream image source to JPEG_MED format and type DLNAImage using the following parameters: PadToSize = False
TRACE 2019-09-04 14:46:34.238 [HTTPv2 Request Worker 8] Stripping preceding slash from: /get/53/JPEG_MED_IMG-888445f0fc1cc4decb6a4183477beeeb-V.jpg
TRACE 2019-09-04 14:46:34.238 [HTTPv2 Request Worker 8] Matched media renderer "Chromecast" based on address 192.168.1.122
DEBUG 2019-09-04 14:46:34.238 [HTTPv2 Request Worker 8] Recognized media renderer "Chromecast"
TRACE 2019-09-04 14:46:34.238 [HTTPv2 Request Worker 8] Received a request from Chromecast (192.168.1.122:44184):
...
```
I should expect "Recognized media renderer" should not be DEBUG but TRACE level as the other relevant ones.
In case DEBUG level is enabled in UMS GUI, you see "Recognized media renderer" SPAM only for every browsed file? If it is like that, it generates storm of irrelevant messages (irrelevant for DEBUG but good for TRACE)
Or am I totally wrong?

**Comment by Nadahar** [comment] 2019-09-04 13:32
I think you're partially wrong. This isn't normally spammed, it is caused by the behavior of this particular renderer. That said, there isn't really much "consistency" when it comes to log level. Different devs seem to have different idea of what a log level represents, and I can even be unsure what is the appropriate level myself.

`debug` is for debugging what's happening, `trace` is to follow everything in detail. As such, it's not always easy to decide if a particular log message belongs to one or the other. What I think you ask, is that the log level should vary depending on whether it's the first the that particular renderer is "detected" or not. That is surely extra trouble to do, for what seems to me like a very limited benefit.

If you don't want debug information in the log, I would recommend setting the log level to `info`. It should still pick up issues, while hiding information you don't want to see. The default log level has been set to `debug` in UMS, which I disagree with. I guess that ultimately is the *real* issue. IMO, anything below `info` is not intended for the average user.

**Comment by ExSport** [comment] 2019-09-04 14:00
I don't have any real environment where I can test UMS right now but you said it is behaviour of particular renderer. Log above is for Windows media player and Android MediaHouse. It is not log for LG TV :)
Yes, toy are right that from start, without checking the log I tried to imagine situation UMS will reduce logging or lowering it's level when renderer is already detected.
But now as I can see, there are e.g. five consecutive messages in log but one of them has different log level. If every renderer query for media file generates such log messages, I understand I want to see all of them but not only one which is useless when it is alone (debug level).
But if it is not the case UMS will log for each renderer media file request [Recognized media renderer "...."] message in debug log level, then it should be ok.
If UMS will write something like [File xyz.jpg requested by ZZZ renderer], such message is logical when generated for each request and has informational value also in case it is alone, but not the message mentioned above :))
I should install the latest UMS and try some renderer (have Android or Kodi only) browsing to see what is written in log for each requests (if it spams or not)...

**Comment by Nadahar** [comment] 2019-09-04 16:21
> Log above is for Windows media player and Android MediaHouse. It is not log for LG TV :)

Yes, but I don't consider what's logged there spam. I was referring to the repeated `debug` "detection" messages that you consider to be spam. As I said, I partially agree, in that it's not very logical seen from the outside, but it mirrors how the code actually works. So, it *is* useful if you compare a log with the actual code, as it confirms that this "stage" was entered. Personally I think the most "confusing" thing about this is the logic, or lack thereof, in the underlying code. The log output is simply a result of that.

When that is said, the logging in general could be improved so many places, both in what is being logged and what log level is being used. Considering that there are probably thousands of logging calls in the code base, trying to "overhaul" this and make it consistent is no small feat.

**Comment by SubJunk** [comment] 2019-09-05 07:57
If we ever get this project to such a complete state that our top priority is log levels I'll be very happy and will reopen this :)
