### ISSUE TITLE
PS3 Not finding nor playing m4a files with coverart ID3Tag under Windows XP SP3 (Invalid memory access)

### ISSUE THREAD

**Issue by RaveDave001** [UniversalMediaServer/UniversalMediaServer#976] opened 2016-08-05 05:06 UTC
A few nights ago, i attempted to play a folder which had 12 m4a files in it on my ps3, when i clicked on the folder, it came up on the screen "There are no tracks" i tried several other folders which had m4a files but the same message came up on them all. I am running the current version 6.5.0.

I decided to uninstall the new version and install older versions to see were this problem started from as i have had no problems playing m4a files before, the last version that displays m4a files is version 6.0.0 every version since has the same problem.

I am using the Windows java 7 version of UMS, i am running UMS of a Windows XP SP3 operating system, if you need anymore information please let me know.

Thanks

Dave

**Comment by Sami32** [comment] 2016-08-06 15:08
Follow these instructions: http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

Thanks

**Comment by RaveDave001** [comment] 2016-08-06 17:04
I made a post on the forum yesterday with the log as you have requested

http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=8546

Thanks

**Comment by valib** [comment] 2016-08-06 22:43
@UniversalMediaServer/developers it seems to me that we are dealing with the problem common also with issue repoted by @Sami32. The Invalid memory access `ERROR 2016-08-05 21:09:02.187 [New I/O worker #3] Error adding child: "02 - Keith Urban - John Cougar, John Deere, John 316.m4a"
java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:390)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at net.pms.dlna.$Proxy1.Open(Unknown Source)
	at net.pms.dlna.MediaInfo.Open(MediaInfo.java:249)
	at net.pms.dlna.LibMediaInfoParser.parse(LibMediaInfoParser.java:66)` means that there is either problem related to the OS  Win XP and MediaInfo or there is the insufficient memory of the PC and  the Maximum memory set to 742 MB as default during installation in that case is wrong and should be lowered. If the older MediaInfo versions works on that configuration we should recommend to users who are using that no longer supported OS versions to download the proper MediaInfo version and replace the version provided by the UMS.

**Comment by Sami32** [comment] 2016-08-07 00:38
@valib I tried before lowering the memory use and it didn't make thing better.
Strange because i didn't have problem with M4A so i will test again later.

@RaveDave001 For now, as a workaround, replace your _mediainfo.dll_ in _UniversalMediaServer_ folder by the MediaInfo 0.7.81 and give feedback, please.

**Comment by Nadahar** [comment] 2016-08-07 00:53
There are some bugs related to ```m4a``` and has been for a long time. I tried to solve it in my ```formats``` branch but I don't think I finished it. The problem is that ```mp4``` and ```m4a``` are identical in any way except the file name. You can't tell them apart with MediaInfo or in any other way because there are no difference. Yet, you want ```mp4``` to play as a video file and ```m4a``` to play as audio. My intended solution to this was to define that the "rules" for being an audio file were that the container had one track only and that track is audio. Everything else would be considered a video file. I did make some methods for this: ```isAudio()```, ```isVideo()``` and ```isImage()``` AFAICR, but this was never finished. There are some issues with the way the MediaInfo information is parsed in UMS regarding this if my memory serves me right.

I suspect this will reveal itself once the ```The Invalid memory access``` is resolved. There might be worth a try to rename a problematic file to ```mp4``` and see if that changes anything.

**Comment by Sami32** [comment] 2016-08-07 00:59
@Nadahar As told in my issue, i tried already MP4 and others, and have only problem with files having CoverArt/AlbumArt tag, it's why i suspect these M4A to have CoverArt as well.

**Comment by Nadahar** [comment] 2016-08-07 01:03
@Sami32 Ok, I don't remember the specifics, but I do remember that I found some issues with the logic and audio files in "video" containers. It's the same with ```mka``` files.

**Comment by Sami32** [comment] 2016-08-07 01:27
@Nadahar I didn't tried MKA. but i can remember the same little audio file play, display fine without CoverArt and give this error with coverart, same for MP4 videos.
So i eliminate the RAM from the equation, and saw that MediaInfo was not giving this error only if the version is >0.7.81. But when i tested MediaInfo as standalone, i didn't saw any output difference with the latest version.
It's why i suspect UMS, maybe in DLNAResource.java, but that could be Windows XP SP3 ?

**Comment by RaveDave001** [comment] 2016-08-08 01:11
As per your requests, i reinstalled v6.5.0 with clean install and did the following

1) Tried a folder with a single m4a file with no covert art, the file was found and played fine.
2) Tried a folder with a single m4a file with covert art, the file wasn't found.
3) Tried a folder with a single mp3 file with no covert art, the file was found and played fine.
4) Tried a folder with a single mp3 file with covert art, the file wasn't found.

I then replaced the mediainfo.dll file with v0.7.81 and then did the same four tests again, this time the m4a's both with and without cover art were found and played fine and the mp3's both with and without cover art were found and played fine.

If there are any other tests you want me to carry out just let me know

**Comment by Sami32** [comment] 2016-08-08 02:21
@RaveDave001 Thank you for your testing :+1: 

Yes, if you you can do the same tests on a other OS than Windows XP, to verify that's not coming from WinXP SP3.

Could you tell me what is your computer's processor and RAM amount, please ?

**Comment by RaveDave001** [comment] 2016-08-08 03:29
I'll try the tests on another OS tomorrow

My XP computer has an Intel Core 2 Duo E6750 processor and 4GB of RAM.

**Comment by Nadahar** [comment] 2016-08-08 05:24
Its apparant that this issue isn't related to what I am talking about. Things can have changed since I looked at it, and unfortunately I don't exactly remember the nature of the issues I found. 

It's really sad if MediaInfo have made change that is incompatible with Windows XP. One shouldn't think that should be needed, most changes to the Windows API's after that has been either minor or GUI related AFAIK.

**Comment by Sami32** [comment] 2016-08-08 15:34
@Nadahar 

> As of June 2016, Windows XP desktop market share is 9.78% according to NetMarketshare[13] (while StatCounter estimates at 6.5% globally[14] (3.46% across all platforms[15]) and the market share higher in e.g. China at 23%,[16][17] India;[18] Asia in general and Africa), making it the third most popular after Windows 7 and Windows 10 (and StatCounter also ranks after Windows 8.1 and OS X contrary to NetMarketshare's data).

**Comment by RaveDave001** [comment] 2016-08-08 18:49
I ran all the same tests today and also included a FLAC file with and without cover art on a fresh install of v0.6.5 on a laptop with Windows 7, an AMD Anthlon II P320 Processor & 3GB of RAM.

The mp3, m4a and flac files both with and without cover art were all found and played fine.

**Comment by Sami32** [comment] 2016-08-08 20:37
@RaveDave001 Thank you very much for your testing :+1: 

So it's look MediaInfo doesn't like Windows XP  :-(
Not sure if something can be done about that since it's not UMS fault...but as it's a duplicate of the issue #892 i will close it.

**Closed by Sami32** 2016-08-08 20:37 UTC
