### ISSUE TITLE
mencoder on macOS doesn't work

### ISSUE THREAD

**Issue by esabol** [UniversalMediaServer/UniversalMediaServer#1593] opened 2018-09-30 20:26 UTC
MacOS X High Sierra 10.13.6 (17G65)

mencoder error. This is with UMS 7.4.0, but it hasn't worked for many releases at least. I can't remember the last time mencoder worked.

The Logs window typically shows this:
```
14:57:56 INFO  Process "/Users/xxxxxxx/Downloads/Universal Media Server.app/Contents/Resources/osx/mencoder" has a return code of 1! Maybe an error occurred... check the log file
14:57:58 INFO  Started playing XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv on your PlayStation 4
14:58:02 INFO  Stopped playing XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv on your PlayStation 4
```

The TRACE log shows this:

```
TRACE 2018-09-30 14:58:49.738 [HTTPv2 Request Worker 3] Received a request from PlayStation 4 (192.168.1.4:57485):

GET /get/51/XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv_transcoded_to.ts HTTP/1.1

HEADER:
  Host: 192.168.1.101:5002
  User-Agent: MediaPlayer/4.00 libhttp/6.00 (PlayStation 4)
  Connection: Keep-Alive

 TRACE 2018-09-30 14:58:49.738 [HTTPv2 Request Worker 3] Asked stream chunk : TimeRange [start=null, end=null] of XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv and player FFmpeg
TRACE 2018-09-30 14:58:49.738 [HTTPv2 Request Worker 3] Setting lastStartPosition from time-seeking: 0.0
DEBUG 2018-09-30 14:58:49.738 [HTTPv2 Request Worker 3] Starting transcode/remux of XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv with media info: Container: MKV, Size: 973768788, Video Bitrate: 2747376, Video Tracks: 1, Video Codec: h264, Duration: 0:47:15.488, Video Resolution: 1280 x 544, Frame Rate Mode: VFR (VFR), AVC Level: 4.1, Audio Tracks: 1 [Audio Codec: Enhanced AC-3, Bitrate: 640000, Channels: 6, Sample Frequency: 48000 Hz], Subtitle Tracks: 5 [id: 0, type: SUBRIP, subtitles track title from metadata: English, lang: en], [id: 1, type: SUBRIP, subtitles track title from metadata: Swedish, lang: sv], [id: 2, type: SUBRIP, subtitles track title from metadata: Norwegian, lang: no], [id: 3, type: SUBRIP, subtitles track title from metadata: German, lang: de], [id: 4, type: SUBRIP, subtitles track title from metadata: Finnish, lang: fi], DLNAThumbnail: [Format = JPEG, Resolution = 320×136, Size = 11157, DLNA Profile = JPEG_RES_320_136], Mime Type: video/x-matroska
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Looking for an audio track with lang: eng
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Looking for an audio track with lang: fre
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Looking for an audio track with lang: jpn
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Looking for an audio track with lang: ger
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Looking for an audio track with lang: und
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Matched audio track: Audio Codec: Enhanced AC-3, Bitrate: 640000, Channels: 6, Sample Frequency: 48000 Hz
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Searching for a match for: und with eng and off
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Searching for a match for: und with * and eng
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Matched internal subtitles track: id: 0, type: SUBRIP, subtitles track title from metadata: English, lang: en
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Searching for a match for: und with * and und
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Switching from FFmpeg to MEncoder to transcode subtitles because the user setting is enabled.
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Searching for a match for: und with eng and off
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Searching for a match for: und with * and eng
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Matched internal subtitles track: id: 0, type: SUBRIP, subtitles track title from metadata: English, lang: en
TRACE 2018-09-30 14:58:49.739 [HTTPv2 Request Worker 3] Searching for a match for: und with * and und
TRACE 2018-09-30 14:58:49.740 [HTTPv2 Request Worker 3] Not muxing the video stream with tsMuxeR via MEncoder because the user setting is disabled
TRACE 2018-09-30 14:58:49.740 [HTTPv2 Request Worker 3] Using video bitrate limit from the general configuration (110 Mb/s)
TRACE 2018-09-30 14:58:49.740 [HTTPv2 Request Worker 3] Halving the video bitrate limit to 55000 kb/s
TRACE 2018-09-30 14:58:49.740 [HTTPv2 Request Worker 3] Adjusting the video bitrate limit to the H.264 Level 4.1-safe value of 31250 kb/s
DEBUG 2018-09-30 14:58:49.743 [mencoder-27] Starting "/Users/XXXXX/Downloads/Universal Media Server.app/Contents/Resources/osx/mencoder" -ss 0 "/Volumes/XXXXXXXX/TV Shows/XXXXXXXXX/XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv" -msglevel statusline=2 -oac lavc -of lavf -lavfopts format=mpegts -mpegopts format=mpeg2:muxrate=500000:vbuf_size=1194:abuf_size=64 -ovc lavc -channels 6 -lavdopts debug=0:threads=4 -lavcopts autoaspect=1:vcodec=libx264:acodec=ac3:abitrate=640:threads=8:o=preset=superfast,crf=19,g=250,i_qfactor=0.71,qcomp=0.6,level=3.1,weightp=0,8x8dct=0,aq-strength=0,me_range=16:vrc_maxrate=31250:vrc_buf_size=31250 -ass -ass-color FFFFFF00 -ass-border-color 00000000 -ass-font-scale 1.4 -font Arial -ass-force-style FontName=Arial,Outline=1,Shadow=1,MarginV=10 -noautosub -sid 0 -ofps 24000/1001 -lavdopts fast -mc 0 -noskip -af lavcresample=48000 -srate 48000 -o - -really-quiet -msglevel statusline=2
TRACE 2018-09-30 14:58:49.743 [mencoder-27] Setting FONTCONFIG_PATH to "/Users/xxxxx/Downloads/Universal Media Server.app/Contents/Resources/fonts"
TRACE 2018-09-30 14:58:49.799 [mencoder-27] Successfully initialized buffer to 52,428,800 bytes.
DEBUG 2018-09-30 14:58:49.799 [mencoder-27] Attaching thread: mencoder-27
DEBUG 2018-09-30 14:58:49.799 [mencoder-27] Unix process ID ("/Users/xxxxxx/Downloads/Universal Media Server.app/Contents/Resources/osx/mencoder"): 59809
TRACE 2018-09-30 14:58:49.800 [mencoder-27-Timer] buffered: 0 bytes / inputs: 0
TRACE 2018-09-30 14:58:49.848 [HTTPv2 Request Worker 3] Sleeping for 2500 milliseconds
TRACE 2018-09-30 14:58:50.170 [mencoder-27] EOF
INFO  2018-09-30 14:58:50.170 [mencoder-27] Process "/Users/xxxxxx/Downloads/Universal Media Server.app/Contents/Resources/osx/mencoder" has a return code of 1! Maybe an error occurred... check the log file
TRACE 2018-09-30 14:58:51.803 [mencoder-27-Timer] buffered: 0 bytes / inputs: 0
TRACE 2018-09-30 14:58:52.350 [HTTPv2 Request Worker 3] Finished sleeping for 2500 milliseconds
TRACE 2018-09-30 14:58:52.350 [HTTPv2 Request Worker 3] Did not send subtitle headers because dlna.getMediaSubtitle().isStreamable() is false
TRACE 2018-09-30 14:58:52.350 [HTTPv2 Request Worker 3] Format "mpegts" failed to match supported line f:avi      v:mp4|h264     a:aac-lc|ac3|mp3                           m:video/avi
TRACE 2018-09-30 14:58:52.350 [macOS Sleep Worker] Calling IOKitUtils.disableGoToSleep() to prevent macOS idle sleep
TRACE 2018-09-30 14:58:52.350 [HTTPv2 Request Worker 3] Format "mpegts" failed to match supported line f:mkv      v:h264         a:aac-lc|ac3|mp3                           m:video/x-matroska
TRACE 2018-09-30 14:58:52.351 [StartPlaying Event] Matched media renderer "PlayStation 4" based on address 192.168.1.4
TRACE 2018-09-30 14:58:52.351 [HTTPv2 Request Worker 3] Format "mpegts" failed to match supported line f:mkv      v:h264         a:he-aac        n:2                        m:video/x-matroska
TRACE 2018-09-30 14:58:52.351 [HTTPv2 Request Worker 3] Format "mpegts" failed to match supported line f:mp4      v:h264         a:aac-lc|ac3             w:3840   h:2160   m:video/mp4
TRACE 2018-09-30 14:58:52.351 [HTTPv2 Request Worker 3] Format "mpegts" failed to match supported line f:mp4      v:h264         a:he-aac        n:2      w:3840   h:2160   m:video/mp4
TRACE 2018-09-30 14:58:52.351 [HTTPv2 Request Worker 3] Format "mpegts" failed to match supported line f:mpegps   v:mpeg2        a:aac-lc|ac3|lpcm|mpa                      m:video/mpeg
TRACE 2018-09-30 14:58:52.351 [HTTPv2 Request Worker 3] Matched support line f:mpegts   v:mpeg2|h264   a:aac-lc|ac3|mpa                           m:video/mpeg
TRACE 2018-09-30 14:58:52.351 [HTTPv2 Request Worker 3] Ready to Stop: true
```

If I remove `-really-quiet` from the mencoder command line options and try to execute the mencoder command from the command line, it shows this:

```
%  "/Users/xxxxxx/Downloads/Universal Media Server.app/Contents/Resources/osx/mencoder" -v -ss 0 "/Volumes/xxxxxx/TV Shows/XXXXXXXXX/XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv" -msglevel statusline=2 -oac lavc -of lavf -lavfopts format=mpegts -mpegopts format=mpeg2:muxrate=500000:vbuf_size=1194:abuf_size=64 -ovc lavc -channels 6 -lavdopts debug=0:threads=4 -lavcopts autoaspect=1:vcodec=libx264:acodec=ac3:abitrate=640:threads=8:o=preset=superfast,crf=19,g=250,i_qfactor=0.71,qcomp=0.6,level=3.1,weightp=0,8x8dct=0,aq-strength=0,me_range=16:vrc_maxrate=31250:vrc_buf_size=31250 -ass -ass-color FFFFFF00 -ass-border-color 00000000 -ass-font-scale 1.4 -font Arial -ass-force-style FontName=Arial,Outline=1,Shadow=1,MarginV=10 -noautosub -sid 0 -ofps 24000/1001 -lavdopts fast -mc 0 -noskip -af lavcresample=48000 -srate 48000 -o - -msglevel statusline=2
MEncoder UNKNOWN-4.2.1 (C) 2000-2012 MPlayer Team
get_path('codecs.conf') -> '/Users/xxxxxx/.mplayer/codecs.conf'
Reading optional codecs config file /Users/xxxxxx/.mplayer/codecs.conf: No such file or directory
Reading optional codecs config file /Users/patricka/work/ps3mediaserver-maven/i386/target/bin-tools/target/etc/mplayer/codecs.conf: No such file or directory
Using built-in default codecs.conf.
init_freetype
get_path('font/font.desc') -> '/Users/xxxxxx/.mplayer/font/font.desc'
font: can't open file: /Users/xxxxxx/.mplayer/font/font.desc
font: can't open file: /Users/patricka/work/ps3mediaserver-maven/i386/target/bin-tools/target/share/mplayer/font/font.desc
Using MMX (with tiny bit MMX2) Optimized OnScreenDisplay
get_path('fonts') -> '/Users/xxxxxx/.mplayer/fonts'
Configuration: --cc=/usr/bin/gcc --disable-x11 --disable-gl --disable-qtx --disable-fontconfig --with-freetype-config=/Users/patricka/work/ps3mediaserver-maven/i386/target/bin-tools/target/bin/freetype-config --prefix=/Users/patricka/work/ps3mediaserver-maven/i386/target/bin-tools/target
[file] File size is 973768788 bytes
STREAM: [file] /Volumes/xxxxxx/TV Shows/XXXXXXXXX/XXXXXXXXX.720p.WEBRip.X264-XXXXX.mkv
STREAM: Description: File
STREAM: Author: Albeu
STREAM: Comment: based on the code from ??? (probably Arpi)
success: format: 0  data: 0x0 - 0x3a0a8854
libavformat version 54.29.105 (internal)
Configuration: --enable-gpl --enable-version3 --enable-nonfree --disable-doc --disable-debug --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-libfreetype --cc=/usr/bin/gcc --disable-vda --disable-libass --disable-fontconfig --disable-devices --disable-ffplay --disable-ffserver --disable-ffprobe --disable-shared --enable-static --prefix=/Users/patricka/work/ps3mediaserver-maven/i386/target/bin-tools/target
LAVF_check: Matroska / WebM
libavformat file format detected.
st:0 removing common factor 1000000 from timebase
st:1 removing common factor 1000000 from timebase
st:2 removing common factor 1000000 from timebase
st:3 removing common factor 1000000 from timebase
st:4 removing common factor 1000000 from timebase
st:5 removing common factor 1000000 from timebase
st:6 removing common factor 1000000 from timebase
[matroska,webm @ 0xed9340]File position before avformat_find_stream_info() is 5976
[h264 @ 0xee7160]Using externally provided dimensions
[h264 @ 0xee7160]no picture 
[matroska,webm @ 0xed9340]All info found
[matroska,webm @ 0xed9340]File position after avformat_find_stream_info() is 27426
==> Found video stream: 0
======= VIDEO Format ======
  biSize 81
  biWidth 1280
  biHeight 544
  biPlanes 0
  biBitCount 0
  biCompression 875967048='H264'
  biSizeImage 0
Unknown extra header dump: [1] [64] [0] [29] [ff] [e1] [0] [18] [67] [64] [0] [29] [ac] [d9] [80] [50] [4] [5b] [1] [10] [0] [0] [3e] [90] [0] [b] [b8] [0] [f1] [83] [19] [a0] [1] [0] [6] [68] [e9] [78] [23] [2c] [8b] 
===========================
[lavf] stream 0: video (h264), -vid 0
==> Found audio stream: 1
======= WAVE Format =======
Format Tag: 16709 (0x4145)
Channels: 6
Samplerate: 48000
avg byte/sec: 80000
Block align: 1
bits/sample: 0
cbSize: 0
==========================================================================
[lavf] stream 1: audio (eac3), -aid 0
[lavf] stream 2: subtitle (subrip), -sid 0, -slang eng, English
[lavf] stream 3: subtitle (subrip), -sid 1, -slang swe, Swedish
[lavf] stream 4: subtitle (subrip), -sid 2, -slang nor, Norwegian
[lavf] stream 5: subtitle (subrip), -sid 3, -slang ger, German
[lavf] stream 6: subtitle (subrip), -sid 4, -slang fin, Finnish
LAVF: 1 audio and 1 video streams found
LAVF: build 3546473
VIDEO:  [H264]  1280x544  0bpp  23.976 fps    0.0 kbps ( 0.0 kbyte/s)
[V] filefmt:44  fourcc:0x34363248  size:1280x544  fps:23.976  ftime:=0.0417
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
dec_audio: Allocating 1536000 + 131072 = 1667072 bytes for output buffer.
FFmpeg's libavcodec audio codec
libavcodec version 54.61.100 (internal)
Configuration: --enable-gpl --enable-version3 --enable-nonfree --disable-doc --disable-debug --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-libfreetype --cc=/usr/bin/gcc --disable-vda --disable-libass --disable-fontconfig --disable-devices --disable-ffplay --disable-ffserver --disable-ffprobe --disable-shared --enable-static --prefix=/Users/patricka/work/ps3mediaserver-maven/i386/target/bin-tools/target
INFO: libavcodec "eac3" init OK!
AUDIO: 48000 Hz, 6 ch, s16le, 640.0 kbit/13.89% (ratio: 80000->576000)
Selected audio codec: [ffeac3] afm: ffmpeg (FFmpeg E-AC-3)
==========================================================================
Writing to stdout
[file] File size is -1 bytes
STREAM: [file] -
STREAM: Description: File
STREAM: Author: Albeu
STREAM: Comment: based on the code from ??? (probably Arpi)
** MUXER_LAVF *****************************************************************
REMEMBER: MEncoder's libavformat muxing is presently broken and can generate
INCORRECT files in the presence of B-frames. Moreover, due to bugs MPlayer
will play these INCORRECT files as if nothing were wrong!
*******************************************************************************
OK, exit.
ALLOCATED STREAM N. 1, type=0
Opening video filter: [ass auto=1]
[lavc] query(Planar YV12) -> 1
[lavc] query(Planar I420) -> 1
[lavc] query(Planar IYUV) -> 1
[lavc] query(Packed UYVY) -> 0
[lavc] query(Packed YUY2) -> 0
[ass] auto-open
[ass] Raster: FreeType 2.4.10
[ass] Shaper: FriBidi 0.19.2 (SIMPLE)
[ass] Initialized
get_path('fonts') -> '/Users/xxxxxx/.mplayer/fonts'
[ass] Fontconfig disabled, only default font will be used.
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
INFO: libavcodec init OK!
Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
==========================================================================
ALLOCATED STREAM N. 2, type=1
Building audio filter chain for 48000Hz/6ch/s16le -> 48000Hz/0ch/??...
[libaf] Adding filter lavcresample 
[libaf] Removing filter lavcresample 
[libaf] Adding filter dummy 
[dummy] Was reinitialized: 48000Hz/6ch/s16le
[dummy] Was reinitialized: 48000Hz/6ch/s16le
[ac3 @ 0xee7160]channel_layout not specified
[ac3 @ 0xee7160]No channel layout specified. The encoder will guess the layout, but it might be incorrect.
Building audio filter chain for 48000Hz/6ch/s16le -> 48000Hz/6ch/floatle...
[dummy] Was reinitialized: 48000Hz/6ch/s16le
[libaf] Adding filter format 
[format] Changing sample format from little-endian 16-bit signed int to little-endian 32-bit float
[format] Accelerated little-endian 16-bit signed int to little-endian 32-bit float conversion
[dummy] Was reinitialized: 48000Hz/6ch/s16le
[format] Changing sample format from little-endian 16-bit signed int to little-endian 32-bit float
[format] Accelerated little-endian 16-bit signed int to little-endian 32-bit float conversion
[libaf] Reallocating memory in module format, old len = 0, new len = 49165
Increasing filtered audio buffer size from 0 to 49152
[h264 @ 0xee7160]Using externally provided dimensions
Unsupported PixelFormat 61
Unsupported PixelFormat 53
Unsupported PixelFormat 81
[h264 @ 0xee7160]no picture 
[h264 @ 0xee7160]no picture 
[ffmpeg] aspect_ratio: 0.000000
VDec: vo config request - 1280 x 544 (preferred colorspace: Planar YV12)
Trying filter chain: ass lavc
VDec: using Planar YV12 as output csp (no 0)
Movie-Aspect is 2.35:1 - prescaling to correct movie aspect.
VO Config (1280x544->1280x544,flags=0,'MPlayer',0x32315659)
REQ: flags=0x401  req=0x0  
videocodec: libavcodec (1280x544 fourcc=34363268 [h264])
Your options /preset=superfast,crf=19,g=250,i_qfactor=0.71,qcomp=0.6,level=3.1,weightp=0,8x8dct=0,aq-strength=0,me_range=16/ look like gibberish to me pal
FATAL: Cannot initialize video driver.

Exiting...
```

**Comment by SubJunk** [comment] 2018-09-30 20:50
Looks like a bug with our H.264 settings on macOS, which makes sense since they are really flaky and tailored to specific versions of MEncoder. Will look into it. Thanks for the details

**Comment by SubJunk** [comment] 2018-10-03 22:17
This is a duplicate of https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1309 so closing it and will post updates there

**Closed by SubJunk** 2018-10-03 22:17 UTC
Labels: bug
