### ISSUE TITLE
Vizio Smart TV - Streaming Issue

### ISSUE THREAD

**Issue by Ranger187** [UniversalMediaServer/UniversalMediaServer#253] opened 2014-03-07 23:19 UTC
Here is the original post: http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=487

Around page 9 I have tested in explicit detail the issues with Vizio's tv's.

For this example I am using a Vizio Razor series M501d-A2R 50" 3D.
# 
# SUPPORTED FORMATS

I have uploaded the PDF of the supported formats the M series (2013 models) can handle here: https://db.tt/E1N7Mvtn
# 
# ISSUES
1. TV has issues playing certain AVI's or other formats. It takes 1-30 minutes to start streaming.
2. TV can't play/stream Divx. (Changing the conf can resolve this, but it can take 1-30 minutes to stream!)
3. TV will "freeze" upon entering a folder with multiple files/formats.  You need to let it sit there for minutes before it refreshes and shows the content. The TV actually will try and PLAY every video file and get numerous errors (CHECK THIS POST: http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=487&p=9752#p9667"
4. TvMobili can successfully play all file types, so that means UMS is capable if we can resolve this.

**Comment by mfulgo** [comment] 2015-01-20 02:01
Okay, it looks like the underlying problem here is actually Netty 3.x. [If the kernel's send buffer fills up, it will suspend writing data to the client until the stream is finished being generated.](https://github.com/netty/netty/issues/3311)  In the case of transcoding large videos, that may be (and often is) longer than the TV is willing to wait before closing its request and opening a new one.  The issue is not present in Netty 4.x.

@SubJunk If I go to the trouble of migrating the 5.0.0 branch to Netty 4.0.25.Final, is that something you'll be wiling to merge?

**Comment by SubJunk** [comment] 2015-01-20 03:57
@mfulgo yes, I would love to have Netty updated to 4.x :)

**Comment by valib** [comment] 2015-01-20 22:24
@SubJunk, @mfulgo it would be nice to implement Netty 4.x but it means to rewrite RequestHandlerV2 and RequestV2 because they use methods not implemented in the version 4.x

**Comment by SubJunk** [comment] 2015-01-20 23:23
@valib since I'm looking to release 5.0.0 final soon (like maybe today? what do you think?) we could try for that in 6.0.0.

**Comment by valib** [comment] 2015-01-20 23:42
@SubJunk for me is version 5 working well and could be released, About implementation of Netty 4 I actually tried to implement it but I failed. I am not so good like @SharkHunter or @skeptical :)

**Comment by mfulgo** [comment] 2015-01-21 00:20
I'd say go ahead and release it, or at least, don't wait for my update to Netty 4.x.  I'm almost done knocking out all the compile errors from the switch over, but then there's some basic testing that needs to happen.

I can also take the opportunity to tear apart `RequestHandlerV2` and `RequestV2` and refactor them into something cleaner.

**Comment by Sami32** [comment] 2016-08-03 22:12
http://www.universalmediaserver.com/forum/search.php?keywords=vizio

**Comment by Sami32** [comment] 2016-08-08 20:57
@Ranger187 Do you have again this issue with your Vizio ?
If yes, do you accept to test 2 beta versions ?

**Comment by Ranger187** [comment] 2016-08-08 21:23
I've had it for 2 years. Gave up using UMS > TV and use UMS > PS4 or HD > TV.

**Comment by Sami32** [comment] 2016-08-09 00:58
@Ranger187 Could try with this version, please ? any feedback would be appreciate ;-)
https://we.tl/ZstD2XOIOF

Hoping for the best, but if not, could you post your log following these instructions, please ?
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by Sami32** [comment] 2016-09-07 18:19
@Ranger187 If no answer mean unsuccessful, could you try that version:
https://we.tl/SiuXehhCat
This link is valid until the14 septembre 2016.

**Comment by Ranger187** [comment] 2016-09-07 18:21
I'll try tonight. Do you want me to use the original file 2 posts above or the newest one you posted?

**Comment by Sami32** [comment] 2016-09-07 18:22
@Ranger187 Only the last one is again valid ;-)

**Comment by Ranger187** [comment] 2016-09-07 18:24
Ok. I'll try later tonight and post the results.

**Comment by Sami32** [comment] 2016-09-07 18:24
@Ranger187 Thanks for that ;-)

**Comment by Ranger187** [comment] 2016-09-07 18:56
It's "frozen" again on just listing the contents. Over 5 mins to list 20 files. Sigh. I posted a fix for this, I just have to go to the original post and find it.

**Comment by Ranger187** [comment] 2016-09-07 18:59
The apparent "fix" is:

`#TranscodeExtensions=dvr-ms,dvr,mkv,dv,ty,mov,ogm,hdmov,hdm,rmv,rmvb,rm,asf,evo,asx,flv,m2v,mpe,mod,tivo,ty,tmf,ts,tp,m2p,mp4,m4v,avi,wmv,wm,divx,div,flac,mlp,fla,wma,m4a,aac,dts,mka,ape,ogg,shn,mpc,ra,mp2,wv,oma,aa3,gif,png,arw,cr2,crw,dng,raf,mrw,nef,pef,tif,tiff
#StreamExtensions=avi`

**Comment by Sami32** [comment] 2016-09-07 19:34
@Ranger187 Thanks for your feedback :)

Could you post your log, please ?  following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

**Comment by Ranger187** [comment] 2016-09-07 19:36
Meh, after I rem the above out. Sure. It was transcoding an avi into an mpg. Wrong......

**Comment by Sami32** [comment] 2016-09-07 19:38
@Ranger187 If it's only a renderer configuration that's cool ;-)

Do every videos, music files playe correctly ? Do you any any connection improvement with this version ?

**Comment by Ranger187** [comment] 2016-09-07 19:39
Zero improvement. Unless you rem the above line out.

**Comment by Sami32** [comment] 2016-09-07 19:43
@Ranger187 Your log could help to a better diagnose your renderer issue.

**Comment by Sami32** [comment] 2016-09-07 20:54
@Ranger187 Did you tried to do a Wireshark session capture while using UMS and one while using TVMobili ?

That could help a lot if you could post them here that we can compare them and see what wrong with UMS.

**Comment by atamariya** [comment] 2016-09-08 10:44
@Ranger187 The first listing of the folder takes time because UMS is trying to generate thumbnails for the files. Subsequent requests should work much better with latest version of UMS. Or you can try the scan URL http://localhost:5001/console/scan .

**Comment by Sami32** [comment] 2016-09-09 00:00
@mfulgo Could you try this Netty 4.1.5 and DLNA improved version and give some feedback, please ?
https://we.tl/SiuXehhCat

For the testing purpose, could you try to set `transcode_block_multiple_connections=true` and `transcode_keep_first_connection =false` in your UMS.conf, and give feedback.
A trace log will be very helpfull to analyse and compare memory use, buffered Space and ArrayIndexOutOfBoundsException error.
 The number of client connections hooked into the server's buffer and locking it up should be affected by these settings.

Thanks.

**Comment by mfulgo** [comment] 2016-09-09 01:07
Hey Sami, I'll try to make some time this weekend to try it out! 

Best, 
-Matt

**Comment by Ranger187** [comment] 2016-09-10 19:26
The problem is Vizio doesn't generate ANY thumbnails.

**Comment by mfulgo** [comment] 2016-09-11 22:35
@Sami32 I just realize that you sent me an `.exe`; I'm running Linux.  Can you point me to a git hash, and I'll just build and run it from source?

Thanks,
-Matt

**Comment by Sami32** [comment] 2016-09-11 22:45
@mfulgo Sorry, i missed that you was on Linux.

PR #942 or this commit 0bef1f10eca2f1007355b5f4db9eb9139a7c0603
That's said, you could try the UMS.conf modification on your actuel version as well.

Thanks for your help,
Samuel

**Comment by mfulgo** [comment] 2016-09-12 03:26
Well, the short answer is that it's still buggy...

Simply selecting the folder that contains a _single_ 2.3GB video file causes the TV to freeze for several minutes while this happens:
```
22:58:23 INFO  Started playing large-video.m4v on your Vizio Smart TV
23:03:05 INFO  Stopped playing large-video.m4v on your Vizio Smart TV
23:03:14 WARN  Sending kill -14 to the Unix process: 11267
```

I expect the TV is still making the same two requests in order to get values for the date and duration of the video in its display.

At this point, I can select the video to play, the TV freezes, but **it does eventually play the video!** It just takes quite a few minutes before doing so.

Here's some log messages: https://gist.github.com/mfulgo/388fd99a5015f4319d01d7cfaac0ddd7

I'll see if I can dig deeper into this during the week to get you some more detailed logs, a better idea of what's going on, and to see if maybe there's a way to improve things.

**Comment by Sami32** [comment] 2016-09-12 16:13
@mfulgo Did you tried with `transcode_block_multiple_connections=true` and `transcode_keep_first_connection =false` ?

Did you have the same issue with a video file without subtitle ? As the one played in your log was with MEncoder engine, not the best one...

Thanks for testing ;-)

**Comment by SubJunk** [comment] 2020-02-10 01:31
@mfulgo @Ranger187 are you guys still around? We have an open Pull Request (https://github.com/UniversalMediaServer/UniversalMediaServer/pull/902) for updating to newer Netty versions and I would be interested in getting that tested by one of you to see if it affects this. I can build and upload it if you are available

**Comment by Ranger187** [comment] 2020-02-10 01:32
Still around!Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: SubJunk <notifications@github.com> Date: 2/9/20  8:31 PM  (GMT-05:00) To: UniversalMediaServer/UniversalMediaServer <UniversalMediaServer@noreply.github.com> Cc: Ranger187 <Ranger187@Gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [UniversalMediaServer/UniversalMediaServer] Vizio Smart TV -
  Streaming Issue (#253) @mfulgo @Ranger187 are you guys still around? We have an open Pull Request (#902) for updating to newer Netty versions and I would be interested in getting that tested by one of you to see if it affects this. I can build and upload it if you are available

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/UniversalMediaServer/UniversalMediaServer/issues/253?email_source=notifications\u0026email_token=AAOERFY3QM24WL32YPWPQ5DRCCVAJA5CNFSM4AM7QXUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELG7A2I#issuecomment-583921769",
"url": "https://github.com/UniversalMediaServer/UniversalMediaServer/issues/253?email_source=notifications\u0026email_token=AAOERFY3QM24WL32YPWPQ5DRCCVAJA5CNFSM4AM7QXUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELG7A2I#issuecomment-583921769",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SubJunk** [comment] 2020-02-10 01:35
@Ranger187 thanks for the reply, are you still using Windows? I can make you a Windows build to test

**Comment by Ranger187** [comment] 2020-02-10 01:36
Yes sir, but I no longer have a Vizio. This only affects that model?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: SubJunk <notifications@github.com> Date: 2/9/20  8:35 PM  (GMT-05:00) To: UniversalMediaServer/UniversalMediaServer <UniversalMediaServer@noreply.github.com> Cc: Ranger187 <Ranger187@Gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [UniversalMediaServer/UniversalMediaServer] Vizio Smart TV -
  Streaming Issue (#253) @Ranger187 thanks for the reply, are you still using Windows? I can make you a Windows build to test

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/UniversalMediaServer/UniversalMediaServer/issues/253?email_source=notifications\u0026email_token=AAOERF3DXYCBFW47KJE6UY3RCCVNTA5CNFSM4AM7QXUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELG7EYA#issuecomment-583922272",
"url": "https://github.com/UniversalMediaServer/UniversalMediaServer/issues/253?email_source=notifications\u0026email_token=AAOERF3DXYCBFW47KJE6UY3RCCVNTA5CNFSM4AM7QXUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELG7EYA#issuecomment-583922272",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SubJunk** [comment] 2020-02-10 01:37
Ah I see, I'm not surprised about that given all these problems :) Yes I think this is only relevant for Vizios. Let's see if @mfulgo still has his one

**Comment by mfulgo** [comment] 2020-02-10 02:30
Yeah, I'm still around and still have a Vizio... It may take me about 2 weeks to get to this, though. Are you looking for a quick turnaround?

**Comment by SubJunk** [comment] 2020-02-11 06:52
@mfulgo 2 weeks is ok :)

**Comment by SubJunk** [comment] 2020-02-14 02:31
@mfulgo the version for testing is https://www.universalmediaserver.com/uploads/UMS-253-1.exe

**Comment by SubJunk** [comment] 2020-02-23 22:09
@mfulgo 2 weeks reminder, no pressure just wanted to remind :)

**Comment by SubJunk** [comment] 2020-03-21 07:39
@mfulgo is that testing going to happen? If not I will close this issue.

**Comment by mfulgo** [comment] 2020-03-25 02:30
Yes, I am planning on testing this, but other things have taken precedence. Sorry for the delay. You're welcome to close it, and I'll comment on it when I get a chance to set up my desktop and try it. Hopefully soon.

**Comment by SubJunk** [comment] 2020-03-25 07:10
@mfulgo I'm not in a rush, just making sure the issue doesn't stall. We have many stalled issues and we are really trying to clean them up finally :)

**Closed** 2020-07-26 01:14 UTC
Labels: awaiting testing
